// angular-app/src/app/executions/pre-measurement-available/measurement-details.component.ts
import {Component, OnInit} from '@angular/core';
import {ActivatedRoute, Router} from '@angular/router';
import {NgClass, NgForOf, NgIf} from '@angular/common';
import * as L from 'leaflet';
import {PreMeasurementService} from '../../pre-measurement/pre-measurement-home/premeasurement-service.service';
import {ModalComponent} from '../../shared/components/modal/modal.component';
import {TeamsModel} from '../../models/teams.model';
import {TeamService} from '../../manage/team/team-service.service';
import {TableComponent} from '../../shared/components/table/table.component';
import {UtilsService} from '../../core/service/utils.service';
import {ScreenMessageComponent} from '../../shared/components/screen-message/screen-message.component';

import {
  trigger,
  state,
  style,
  animate,
  transition
} from '@angular/animations';
import {FormsModule} from '@angular/forms';
import {EstoqueService} from '../../stock/services/estoque.service';
import {Deposit} from '../../models/almoxarifado.model';
import {PreMeasurementResponseDTO} from '../../pre-measurement/pre-measurement-models';
import {Toast} from 'primeng/toast';
import {DelegateDTO, StockistModel} from '../executions.model';
import {User} from '../../models/user.model';

@Component({
  selector: 'app-pre-measurement-available',
  standalone: true,
  imports: [
    NgForOf,
    ModalComponent,
    TableComponent,
    NgIf,
    NgClass,
    FormsModule,
    Toast
  ],
  templateUrl: './measurement-details.component.html',
  styleUrl: './measurement-details.component.scss',
  animations: [
    trigger('fadeSlide', [
      transition(':enter', [ // Aparecendo
        style({opacity: 0, transform: 'translateY(-10px)'}),
        animate('500ms ease-out', style({opacity: 1, transform: 'translateY(0)'}))
      ]),
      transition(':leave', [ // Sumindo
        animate('500ms ease-in', style({opacity: 0, transform: 'translateY(-10px)'}))
      ])
    ])
  ]
})
export class MeasurementDetailsComponent implements OnInit {
  isMultiTeam: boolean = false;

  scrollLeft(slider: HTMLElement) {
    slider.scrollBy({left: -300, behavior: 'smooth'});
  }

  scrollRight(slider: HTMLElement) {
    slider.scrollBy({left: 300, behavior: 'smooth'});
  }

  preMeasurement: PreMeasurementResponseDTO = {
    city: '',
    contractId: 0,
    preMeasurementId: 0,
    preMeasurementStyle: '',
    preMeasurementType: '',
    status: '',
    teamName: '',
    totalPrice: '',
    depositName: '',
    step: 0,
    streets: [],
  }
  private map!: L.Map;
  streetId: number = 0;

  localStockStreet: {
    streetId: number;
    materialsInStock: {
      materialId: number;
      materialName: string;
      materialPower: string;
      materialAmp: string;
      materialLength: string;
      deposit: string;
      itemQuantity: number;
      availableQuantity: number
    }[];
    materialsInTruck: {
      materialId: number;
      materialName: string;
      materialPower: string;
      materialAmp: string;
      materialLength: string;
      deposit: string;
      itemQuantity: number;
      availableQuantity: number
    }[];
  }[] = [];

  teams: TeamsModel[] = [];

  reserveDTO: {
    preMeasurementId: number;
    stockistId: string,
    stockistName: string,
    preMeasurementStep: number,
    street: {
      preMeasurementStreetId: number;
      teamId: number;
      teamName: string,
      truckDepositName: string;
      prioritized: boolean;
      comment: string;
    }[]
  } = {
    preMeasurementId: 0,
    stockistId: '',
    stockistName: '',
    preMeasurementStep: 0,
    street: []
  };

  delegateDTO: DelegateDTO = {
    description: '',
    stockistId: '',
    stockistName: '',
    preMeasurementId: 0,
    preMeasurementStep: 0,
    teamId: 0,
  }


  constructor(private route: ActivatedRoute, protected router: Router, private preMeasurementService: PreMeasurementService,
              private teamService: TeamService, private executionService: PreMeasurementService, protected utils: UtilsService,
              private stockService: EstoqueService) {
  }

  ngOnInit() {
    this.route.queryParams.subscribe(params => {
      this.isMultiTeam = params['multiTeam'] === 'true';
    });
    const preMeasurementId = this.route.snapshot.paramMap.get('id');
    const step = this.route.snapshot.paramMap.get('step');
    if (preMeasurementId == null || step == null) {
      return
    }
    this.reserveDTO.preMeasurementId = Number(preMeasurementId);
    this.loadPreMeasurement(preMeasurementId, Number(step));
  }

  loadPreMeasurement(id: string, step: number) {
    this.preMeasurementService.getPreMeasurement(id, step).subscribe(preMeasurement => {
      this.preMeasurement = preMeasurement;
    });

    this.teamService.getTeams().subscribe({
      next: (response) => {
        this.teams = response;
      },
      error: (error: { error: { message: string } }) => {
        this.utils.showMessage(error.error.message, 'error');
      }
    });

    this.stockService.getStockists().subscribe({
      next: (response) => {
        this.stockists = response;
      },
      error: (error: { error: { message: string } }) => {
        this.utils.showMessage(error.error.message, 'error');
        this.utils.showMessage("Erro ao carregar Estoquistas", 'error');
      }
    });
  }

  getStreet(id: number) {
    return this.preMeasurement.streets.find(s => s.preMeasurementStreetId === id);
  }


  protected initMap(street: PreMeasurementResponseDTO['streets'][0]): void {
    const latitude = street.latitude;
    const longitude = street.longitude;
    this.streetId = street.preMeasurementStreetId;

    if (this.map) {
      this.map.remove();
    }

    let reserve = this.reserveDTO.street.find(r => r.preMeasurementStreetId === this.streetId);

    if (!reserve) {
      reserve = {
        preMeasurementStreetId: street.preMeasurementStreetId,
        teamId: 0,
        teamName: '',
        truckDepositName: '',
        prioritized: false,
        comment: ''
      };
      this.reserveDTO.street.push(reserve);
    }

    const team = this.getTeam(reserve.teamId);
    this.teamName = team ? "EQUIPE " + team.teamName.toUpperCase() : 'Nenhuma equipe selecionada'.toUpperCase();
    this.truckDepositName = this.getTeam(reserve.teamId)?.depositName || '';


    setTimeout(() => {
      this.map = L.map('map').setView([latitude, longitude], 15); // Coordenadas iniciais

      L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
        maxZoom: 19,
        attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
      }).addTo(this.map);

      const defaultIcon = L.icon({
        iconUrl: 'https://unpkg.com/leaflet@1.7.1/dist/images/marker-icon.png', // URL do ícone padrão
        iconSize: [25, 41], // Tamanho padrão do ícone
        iconAnchor: [12, 41], // Posição do ponto de ancoragem (base do ícone)
        popupAnchor: [1, -34], // Posição do popup
        shadowUrl: 'https://unpkg.com/leaflet@1.7.1/dist/images/marker-shadow.png', // Sombra do ícone
        shadowSize: [41, 41] // Tamanho da sombra
      });

      // Adicionar o marcador com o ícone SVG
      L.marker([latitude, longitude], {icon: defaultIcon}).addTo(this.map)
        .bindPopup('Localização da pré-medição')
        .openPopup();

    }, 200);

  }

  openModal: boolean = false;
  teamName: string = "";
  truckDepositName: string = "";

  selectTeam(team: TeamsModel) {
    const streetIndex = this.reserveDTO.street
      .findIndex(r => r.preMeasurementStreetId === this.streetId);
    if (streetIndex === -1) {
      this.openModal = false;
      return;
    }

    this.reserveDTO.street[streetIndex].teamId = Number(team.idTeam);
    this.reserveDTO.street[streetIndex].teamName = team.teamName;
    this.reserveDTO.street[streetIndex].truckDepositName = team.depositName;
    this.teamName = "EQUIPE " + team.teamName.toUpperCase();
    this.openModal = false;
  }

  getReserve() {
    return this.reserveDTO.street.find(r => r.preMeasurementStreetId === this.streetId) ||
      {
        preMeasurementStreetId: this.streetId,
        teamId: 0,
        teamName: '',
        truckDepositName: '',
        prioritized: false,
        comment: ''
      };
  }

  getTeam(teamId: number) {
    return this.teams.find(t => t.idTeam.toString() === teamId.toString());
  }

  getTruckMaterials(streetId: number) {
    if (!this.localStockStreet) return [];
    return this.localStockStreet.find(s => s.streetId === streetId)?.materialsInTruck || [];
  }

  finish: boolean = false;

  finishStreet() {
    const streetIndex = this.reserveDTO.street.findIndex(r => r.preMeasurementStreetId === this.streetId);
    if (streetIndex === -1) {
      return;
    }

    if (this.reserveDTO.street[streetIndex].teamId === 0) {
      this.utils.showMessage('Selecione uma equipe para continuar', 'warn');
      return;
    }

    this.preMeasurement.streets[streetIndex].status = 'VALIDATED';
    this.streetId = this.preMeasurement.streets[streetIndex + 1]?.preMeasurementStreetId || 0;
    this.utils.showMessage("Rua pendente salva com sucesso", 'success');
    this.utils.playSound("pop");
    if (this.streetId === 0) {
      this.finish = true;
      if (this.reserveDTO.stockistId.length === 0) {
        this.toggleSideBar();
      }
      return;
    }
    const street = this.getStreet(this.streetId);
    if (street) this.initMap(street);

  }

  isFullStock(): boolean {
    return this.localStockStreet.find(l => l.streetId == this.streetId)
      ?.materialsInTruck.every(t => t.availableQuantity >= t.itemQuantity) || false;
  }

  getReserveByStreetId(preMeasurementStreetId: number) {
    return this.reserveDTO.street.find(r => r.preMeasurementStreetId === preMeasurementStreetId) ||
      {
        preMeasurementStreetId: this.streetId,
        teamId: 0,
        teamName: '',
        truckDepositName: '',
        prioritized: false,
        comment: ''
      }
  }


  stockists: StockistModel[] = [];

  openDepositModal: boolean = false;

  toggleSideBar() {
    this.openDepositModal = !this.openDepositModal;

    const audio = new Audio('sci.mp3');
    audio.play().catch(err => {
      console.warn('Erro ao tentar tocar o som:', err);
    });
  }


  selectDeposits(stockist: string) {
    if (stockist === "Selecione") {
      this.utils.showMessage("A seleção do estoquista que irá gerenciar as reservas de materiais é obrigatória", 'warn');
      return;
    }
    this.reserveDTO.stockistId = stockist;
    this.reserveDTO.stockistName = this.stockists.find(s => s.userId === stockist)?.name || '';

    this.utils.showMessage("Estoquista responsável pelo gerenciamento definido com sucesso", 'info');
    this.openDepositModal = false;
  }


  togglePriority() {
    const streetIndex = this.reserveDTO.street.findIndex(r => r.preMeasurementStreetId === this.streetId);
    if (streetIndex === -1) {
      return;
    }

    this.utils.playSound("select");

    this.reserveDTO.street[streetIndex].prioritized = !this.reserveDTO.street[streetIndex].prioritized;
    let message: string;
    if (this.reserveDTO.street[streetIndex].prioritized) {
      message = "Prioridade definida para essa rua";
    } else {
      message = "Prioridade removida para essa rua";
    }
    this.utils.showMessage(message, 'info');
  }

  insertComment($event: Event) {
    const streetIndex = this.reserveDTO.street.findIndex(r => r.preMeasurementStreetId === this.streetId);
    if (streetIndex === -1) {
      return;
    }

    this.reserveDTO.street[streetIndex].comment = ($event.target as HTMLInputElement).value;
  }

  getComment() {
    const streetIndex = this.reserveDTO.street.findIndex(r => r.preMeasurementStreetId === this.streetId);
    if (streetIndex === -1) {
      return;
    }

    return this.reserveDTO.street[streetIndex].comment;
  }

  isPriority() {
    const streetIndex = this.reserveDTO.street.findIndex(r => r.preMeasurementStreetId === this.streetId);
    if (streetIndex === -1) {
      return;
    }

    return this.reserveDTO.street[streetIndex].prioritized;
  }
}

<div class="flex" #top>
  <div *ngIf="openDepositModal"
       class="fixed top-20 right-4 w-80 z-50 bg-white dark:bg-black dark:text-neutral-50 shadow-lg rounded-lg p-4"
       @fadeSlide>
    <h3 class="text-sm font-semibold text-gray-800 mb-3">Selecionar Estoquista Responsável</h3>
    <p class="text-xs font-light dark:font-dark">
      Para garantir o bom andamento da execução das ruas, é importante definir um estoquista responsável pelo gerenciamento de reserva
      dos materiais. Ele decidirá de onde os materiais serão retirados — seja do caminhão, do próprio almoxarifado ou de terceiros (Outra cidade).
    </p>

    <div class="space-y-2">
      <div>
        <label class="text-xs text-gray-500 mb-1 block mt-5">Primário</label>
        <select class="select select-sm select-bordered w-full" #stockist>
          <option disabled selected>Selecione</option>
          <ng-container *ngFor="let s of stockists">
            <option [value]="s.userId">{{ s.name }}
            </option>
          </ng-container>
        </select>
      </div>
    </div>

    <div class="mt-4 flex justify-end">
      <button class="btn btn-sm btn-primary" (click)="selectDeposits(stockist.value)">
        Salvar
      </button>
    </div>
  </div>
  <div *ngIf="finish && !openDepositModal" class="w-full  pt-8 px-6 bg-gray-50 overflow-auto" @fadeSlide>
    <div class="max-w-7xl mx-auto">
      <!-- Ações -->
      <div class="flex justify-between items-center mb-8">
        <h2 class="text-2xl font-semibold text-gray-800">
          Pré-medição - <span class="text-[#044686]">{{ preMeasurement.city }}</span>
        </h2>

        <div class="flex gap-4">
          <button
            (click)="router.navigate(['/pre-medicao/disponivel'])"
            class="flex items-center gap-2 px-4 py-2 rounded-lg bg-red-600 text-white hover:bg-red-700 transition">
            <span class="material-icons">close</span> Cancelar
          </button>
          <button
            (click)="dialog.show()"
            class="flex items-center gap-2 px-4 py-2 rounded-lg bg-[#044686] text-white hover:bg-indigo-700 transition">
            <span class="material-icons">save</span> Concluir
          </button>
        </div>
      </div>

      <div class="bg-white shadow rounded-lg overflow-hidden w-fit mb-3">
        <table class="min-w-fit text-sm text-gray-700">
          <thead class="bg-[#044686] text-white uppercase text-xs">
          <tr>
            <th class="px-4 py-2 text-left">Estoquista Responsável</th>
          </tr>
          </thead>
          <tbody class="divide-y divide-gray-200">
          <tr class="hover:bg-gray-50">
            <td class="px-4 py-2">{{ reserveDTO.stockistName }}</td>
          </tr>
          </tbody>
        </table>
      </div>

      <dialog #dialog class="modal">
        <div class="modal-box rounded-xl shadow-lg">
          <h3 class="font-bold text-lg mb-4 text-indigo-700">Confirmar envio dos dados</h3>

          <div class="flex justify-end gap-4">
            <button
              (click)="dialog.close()"
              class="flex items-center gap-2 px-4 py-2 rounded-lg bg-red-600 text-white hover:bg-red-700 transition">
              <span class="material-icons">close</span> Cancelar
            </button>
            <button
              class="flex items-center gap-2 px-4 py-2 rounded-lg bg-[#044686] text-white hover:bg-indigo-700 transition">
              <span class="material-icons">save</span> Concluir
            </button>
          </div>
        </div>
      </dialog>

      <!-- Tabela -->
      <div class="bg-white shadow rounded-lg overflow-hidden">
        <table class="min-w-full text-sm text-gray-700">
          <thead class="bg-[#044686] text-white uppercase text-xs">
          <tr>
            <th class="px-6 py-3 text-left"></th>
            <th class="px-6 py-3 text-left">Rua</th>
            <th class="px-6 py-3 text-left">Equipe</th>
            <th class="px-6 py-3 text-left">Almox. Prioritário</th>
            <th class="px-6 py-3 text-left">Comentário</th>
          </tr>
          </thead>
          <tbody class="divide-y divide-gray-200">
          <tr *ngFor="let street of preMeasurement.streets" class="hover:bg-gray-50">
            @let reserve = getReserveByStreetId(street.preMeasurementStreetId) ;
            <td class="px-6 py-2"><span class="material-icons text-orange-500 cursor-pointer"
                                        *ngIf="reserve.prioritized">warning_amber</span></td>
            <td class="px-6 py-4">{{ street.street }}</td>
            <td class="px-6 py-4">{{ reserve.teamName }}</td>
            <td class="px-6 py-4">{{ reserve.truckDepositName }}</td>
            <td class="px-6 py-4">{{ reserve.comment }}</td>
          </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div *ngIf="finish && openDepositModal" class="w-full  pt-8 px-6 bg-gray-50 overflow-auto" @fadeSlide>
    <div class="flex flex-col gap-4">
      <div class="skeleton h-8 w-full"></div>
      <div class="skeleton h-4 w-full mb-2"></div>
      <div class="skeleton h-4 w-full mb-2"></div>
      <div class="skeleton h-4 w-full mb-2"></div>
      <div class="skeleton h-4 w-full mb-2"></div>
      <div class="skeleton h-4 w-full mb-2"></div>
      <div class="skeleton h-4 w-full mb-2"></div>
    </div>
  </div>
  <div class="w-full" *ngIf="!finish" @fadeSlide>
    <div class="pt-2 w-full pl-2 flex items-center justify-between">
      <div class="breadcrumbs text-sm">
        <ul class="select-none">
          <li><a href="/">Início</a></li>
          <li><a href="/execucoes/lista-medicoes">Execuçoes pendentes</a></li>
          <li>Medição</li>
        </ul>
      </div>
      <h3 class="text-medium pr-5 hidden lg:block">{{ getStreet(streetId)?.street || 'Selecione uma rua' }}</h3>
    </div>

    <div>

      <div class="relative w-full overflow-hidden">
        <div
          class="flex overflow-x-auto scroll-smooth no-scrollbar ml-10 mr-10"
          #slider>
          <ng-container *ngFor="let street of preMeasurement.streets">
            <div
              *ngIf="street.status !== 'VALIDATED'"
              @fadeSlide
              [class.selected]="streetId === street.preMeasurementStreetId"
              (click)="initMap(street);"
              class="mb-4 border p-4 rounded w-96 cursor-pointer transform transition-transform duration-300 hover:scale-105 hover:translate-x-2
            hover:translate-y-2 m-2 card-execution select-none">
              <h3 class="text-lg font-semibold mb-2">{{ street.street }}</h3>
              <p class="text-sm text-gray-600 dark:text-neutral-100">{{ street.items.length }} itens pendentes de
                reserva</p>
            </div>
          </ng-container>
        </div>

        <!-- Navegação -->
        <button
          class="absolute left-2 top-1/2 -translate-y-1/2 material-icons text-neutral-700 "
          (click)="scrollLeft(slider)">
          arrow_back_ios
        </button>
        <button
          class="absolute right-2 top-1/2 -translate-y-1/2 material-icons text-neutral-700"
          (click)="scrollRight(slider)">
          arrow_forward_ios
        </button>
      </div>

    </div>


    <div class="w-full pl-2 xl:flex pb-2 pt-2 justify-center">
      <div class="xl:w-1/3 2xl:w-1/4 h-full rounded" [class.border]="streetId > 0" [class.p-3]="streetId > 0">
        @if (streetId === 0) {
          <div class="flex flex-col gap-4">
            <div class="skeleton h-32 w-full"></div>
            <div class="skeleton h-4 w-28"></div>
            <div class="skeleton h-4 w-full mb-2"></div>
            <div class="skeleton h-4 w-full mb-2"></div>
          </div>
        } @else {
          <div class="flex flex-col gap-3 h-full">

            <div class="flex justify-end border-b pb-2">
              <div class="flex gap-2">
                <span class="px-3 py-1 text-xs font-medium bg-blue-100 text-blue-800 rounded-full shadow-sm">
                  {{ getStreet(streetId)?.latitude || 'Latitude não informada' }}
                </span>
                <span class="px-3 py-1 text-xs font-medium bg-blue-100 text-blue-800 rounded-full shadow-sm">
                  {{ getStreet(streetId)?.longitude || 'Longitude não informada' }}
                </span>
              </div>
            </div>

            <div class="h-[300px] rounded overflow-hidden">
              <div id="map" class="h-full w-full" [class.-z-10]="openModal || openDepositModal"></div>
            </div>

            <div class="flex items-center gap-2 border-b pb-2">
              <span
                class="material-icons text-neutral-500 cursor-pointer select-none
                transition-all duration-300 ease-in-out hover:text-orange-600 hover:scale-110"
                (click)="togglePriority()"
                [ngClass]="isPriority() ? 'warning text-orange-500' : ''">
                warning_amber
              </span>
              <span class="text-xs">{{ isPriority() ? 'Com prioridade' : 'Sem prioridade' }}</span>
            </div>

            <div
              class="flex justify-between items-center text-xs font-medium px-3 py-2 rounded-md border bg-white shadow-sm transition-all duration-200"
              [ngClass]="{
                            'text-orange-500 border-orange-300 bg-orange-50': teamName === 'NENHUMA EQUIPE SELECIONADA',
                            'text-gray-700 border-gray-200': teamName !== 'NENHUMA EQUIPE SELECIONADA'
                          }">
              {{ teamName }}

              <div *ngIf="truckDepositName !== ''" class="lg:tooltip cursor-pointer" data-tip="Dados de contato">
                <span class="material-icons" (click)="openModal=true">call</span>
              </div>
            </div>


            <div class="border rounded p-2">
              <textarea
                (input)="insertComment($event)"
                [value]="getComment()"
                placeholder="Adicionar comentário"
                class="w-full text-xs outline-none resize-none h-10">
              </textarea>
            </div>

            <button
              (click)="openModal = true"
              class="btn bg-indigo-600 text-white hover:bg-indigo-700 shadow w-full py-2 rounded transition-transform">
              Selecionar Equipe
            </button>

            <button
              (click)="finishStreet()"
              class="btn bg-indigo-600 text-white hover:bg-indigo-700 shadow w-full py-2 rounded transition-transform">
              Concluir Rua
            </button>
          </div>
        }
      </div>


      <div class="xl:ml-2 xl:pl-2 2xl:w-1/2 mt-2 xl:mt-0 xl:w-[60%]">

        <div class="flex flex-col gap-4" *ngIf="truckDepositName === ''">
          <div class="skeleton h-32 w-full"></div>
          <div class="skeleton h-4 w-28"></div>
          <div class="skeleton h-4 w-full mb-2"></div>
          <div class="skeleton h-4 w-full mb-2"></div>
        </div>

        <div *ngIf="truckDepositName !== ''" class="rounded border bg-white shadow-sm overflow-hidden">
          <!-- Header -->
          <div class="flex items-center justify-between px-4 py-3 border-b bg-gray-50">
            <h3 class="text-sm font-semibold text-gray-800">
              {{ truckDepositName }}
            </h3>
            <span class="material-icons cursor-pointer" title="Clique para mais informações" (click)="openModal = true">info</span>
            @if (isFullStock()) {
              <span class="bg-green-100 text-green-800 text-xs font-medium px-3 py-1 rounded-full shadow-sm">
                Todos os itens possuem estoque
              </span>
            } @else {
              <span class="bg-red-100 text-red-800 text-xs font-medium px-3 py-1 rounded-full shadow-sm">
                Existem itens que não possuem estoque
              </span>
            }
          </div>

          <!-- Tabela -->
          <app-table [className]="'table w-full text-sm text-left text-gray-700 border-t'">
            <tr header class="bg-gray-100 text-xs uppercase text-gray-600">
              <th></th>
              <th>Material</th>
              <th>Potência</th>
              <th>Corrente (A)</th>
              <th>Tamanho</th>
              <th>Quantidade</th>
              <th>Qtde. Estoque</th>
            </tr>


            <tr body *ngFor="let m of getTruckMaterials(streetId); index as index;" class="hover:bg-gray-50">
              <td>{{ index + 1 }}</td>
              <td>{{ m.materialName }}</td>
              <td>{{ m.materialPower }}</td>
              <td>{{ m.materialAmp }}</td>
              <td>{{ m.materialLength }}</td>
              <td class="font-semibold text-blue-600">{{ m.itemQuantity }}</td>
              <td class="font-semibold"
                  [ngClass]="m.availableQuantity >= m.itemQuantity ? 'text-green-600' : 'text-red-600'">{{ m.availableQuantity }}
              </td>
            </tr>

          </app-table>
        </div>

      </div>

    </div>

  </div>


  <app-modal [modalOpen]="openModal" (modalClose)="openModal = false" classModal="xl:w-[50vw] p-0 z-10">
    @if (truckDepositName === '') {
      <div class="overflow-x-auto rounded-box border border-base-content/5 bg-base-100 cursor-pointer">
        <table class="table text-left text-gray-700 border-t">
          <!-- head -->
          <thead>
          <tr class="bg-gray-200 text-xs uppercase text-gray-600">
            <th>Equipe</th>
            <th>Motorista</th>
            <th>Eletricista</th>
            <th>Placa do veículo</th>
            <th>Região geográfica</th>
          </tr>
          </thead>
          <tbody>
          <!-- row 1 -->
          <tr class="hover:bg-blue-100 hover:text-blue-700" *ngFor="let team of teams; let i = index"
              (click)="selectTeam(team)">
            <td>{{ team.teamName }}</td>
            <td>{{ team.driver.driverName }}</td>
            <td>{{ team.electrician.electricianName }}</td>
            <td>{{ team.plate }}</td>
            <td>{{ team.regionName }}</td>
          </tr>
          </tbody>
        </table>
      </div>
    } @else {
      <div class="overflow-x-auto rounded-box border border-base-content/5 bg-base-100 cursor-pointer">
        <table class="table text-left text-gray-700 border-t">
          <!-- head -->
          <thead>
          <tr class="bg-gray-200 text-xs uppercase text-gray-600">
            <th>{{ getTeam(getReserve().teamId)?.electrician?.electricianName }}</th>
            <th>{{ getTeam(getReserve().teamId)?.driver?.driverName }}</th>
          </tr>
          </thead>
          <tbody>
          <!-- row 1 -->
          <tr class="hover:bg-blue-100 hover:text-blue-700">
            <td>Telefone não cadastrado {{ 1 }}</td>
            <td>Telefone não cadastrado {{ 2 }}</td>
          </tr>
          </tbody>
        </table>
      </div>
    }
  </app-modal>

  <
  <p-toast/>
</div>

// react-app/src/features/executions/pages/MeasurementDetails.tsx
import { useEffect, useMemo, useRef, useState } from 'react';
import { useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { useAppStore } from '@/store/use-app-store';
import { useNotify } from '@/shared/hooks/use-notify';
import { preMeasurementsApi } from '@/features/pre-measurement/api/preMeasurementsApi';
import type {
  AvailableStockByStreet,
  DelegateExecutionDTO,
  PreMeasurementResponseDTO,
} from '@/features/pre-measurement/types/types';
import { manageApi } from '@/features/manage/api/manageApi';
import type { TeamModel } from '@/features/manage/types/manageTypes';
import { stockistApi } from '../../stock/api/stockist-api';
import type { StockistModel } from '@/features/requests/types/reservation';
import { Modal, ModalBody, ModalFooter, ModalHeader } from '@/shared/ui/modal';
import { GlassListbox } from '@/shared/components/glass-list-box';

const findFirstPendingStreetId = (
  preMeasurement: PreMeasurementResponseDTO,
  completedStreetIds: number[],
) => {
  const pending = preMeasurement.streets.find(
    (street) => !completedStreetIds.includes(street.preMeasurementStreetId),
  );
  return pending?.preMeasurementStreetId ?? 0;
};

export default function MeasurementDetails() {
  const { id = '' } = useParams<{ id: string }>();
  const [searchParams] = useSearchParams();
  const isMultiTeam = searchParams.get('multiTeam') === 'true';

  const navigate = useNavigate();
  const { notify } = useNotify();
  const setPageContext = useAppStore((state) => state.setPageContext);

  const [loading, setLoading] = useState(true);
  const [showMessage, setShowMessage] = useState(false);

  const [preMeasurement, setPreMeasurement] = useState<PreMeasurementResponseDTO | null>(null);
  const [teams, setTeams] = useState<TeamModel[]>([]);
  const [stockists, setStockists] = useState<StockistModel[]>([]);

  const [delegateDTO, setDelegateDTO] = useState<DelegateExecutionDTO>({
    preMeasurementId: 0,
    description: '',
    stockistId: '',
    stockistName: '',
    stockistPhone: '',
    stockistDepositName: '',
    stockistDepositAddress: '',
    preMeasurementStep: 0,
    teamId: 0,
    comment: '',
    street: [],
  });

  const [streetId, setStreetId] = useState(0);
  const [completedStreetIds, setCompletedStreetIds] = useState<number[]>([]);
  const [finish, setFinish] = useState(false);

  const [openTeamModal, setOpenTeamModal] = useState(false);
  const [openStockistPanel, setOpenStockistPanel] = useState(false);
  const [selectedStockistId, setSelectedStockistId] = useState('');

  const [localStockStreet, setLocalStockStreet] = useState<AvailableStockByStreet[]>([]);
  const streetsSliderRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    setPageContext(['Pré-medições', 'Delegar Execução'], 'Delegar Execução');

    if (!id) return;

    setLoading(true);

    Promise.all([
      preMeasurementsApi.getPreMeasurement(id),
      manageApi.getTeams(),
      stockistApi.getStockists(),
    ])
      .then(([preMeasurementData, teamsData, stockistsData]) => {
        if (preMeasurementData.status !== 'AVAILABLE') {
          notify('Essa pré-medição não está disponível para delegação.', 'warn');
          navigate('/pre-medicao/disponivel', { replace: true });
          return;
        }

        setPreMeasurement(preMeasurementData);
        setTeams(teamsData);
        setStockists(stockistsData);
        setStreetId(preMeasurementData.streets[0]?.preMeasurementStreetId ?? 0);

        setDelegateDTO((previous) => ({
          ...previous,
          preMeasurementId: preMeasurementData.preMeasurementId,
          preMeasurementStep: preMeasurementData.step,
          description: `Etapa ${preMeasurementData.step} - ${preMeasurementData.city}`,
        }));

        if (!isMultiTeam) {
          setOpenTeamModal(true);
        }
      })
      .catch((error: unknown) => {
        const message = error instanceof Error ? error.message : 'Erro ao carregar pré-medição.';
        notify(message, 'error');
      })
      .finally(() => setLoading(false));
  }, [id, isMultiTeam, navigate, notify, setPageContext]);

  const ensureStreetReserve = (streetIdParam: number) => {
    setDelegateDTO((previous) => {
      const exists = previous.street.some((street) => street.preMeasurementStreetId === streetIdParam);
      if (exists) return previous;

      return {
        ...previous,
        street: [
          ...previous.street,
          {
            preMeasurementStreetId: streetIdParam,
            teamName: '',
            truckDepositName: '',
            prioritized: false,
          },
        ],
      };
    });
  };

  useEffect(() => {
    if (streetId > 0) {
      ensureStreetReserve(streetId);
    }
  }, [streetId]);

  const currentStreetReserve = useMemo(
    () => delegateDTO.street.find((street) => street.preMeasurementStreetId === streetId) ?? null,
    [delegateDTO.street, streetId],
  );

  const streetTeam = useMemo(
    () => teams.find((team) => team.teamName === currentStreetReserve?.teamName) ?? null,
    [currentStreetReserve?.teamName, teams],
  );

  const currentStreet = useMemo(
    () => preMeasurement?.streets.find((street) => street.preMeasurementStreetId === streetId) ?? null,
    [preMeasurement, streetId],
  );

  const loadStockByTeam = (teamId: number) => {
    if (!preMeasurement) return;

    preMeasurementsApi
      .getStockAvailable(preMeasurement.preMeasurementId, teamId)
      .then((data) => setLocalStockStreet(data))
      .catch(() => setLocalStockStreet([]));
  };

  const scrollStreets = (offset: number) => {
    streetsSliderRef.current?.scrollBy({ left: offset, behavior: 'smooth' });
  };

  const openStockistSelector = () => {
    setSelectedStockistId(delegateDTO.stockistId || '');
    setOpenStockistPanel(true);
  };

  const selectTeam = (team: TeamModel) => {
    if (!preMeasurement) return;

    if (isMultiTeam) {
      if (!streetId) return;

      setDelegateDTO((previous) => {
        const hasCurrent = previous.street.some((street) => street.preMeasurementStreetId === streetId);

        if (!hasCurrent) {
          return {
            ...previous,
            street: [
              ...previous.street,
              {
                preMeasurementStreetId: streetId,
                teamName: team.teamName,
                truckDepositName: team.depositName,
                prioritized: false,
              },
            ],
          };
        }

        return {
          ...previous,
          street: previous.street.map((street) =>
            street.preMeasurementStreetId === streetId
              ? {
                  ...street,
                  teamName: team.teamName,
                  truckDepositName: team.depositName,
                }
              : street,
          ),
        };
      });

      loadStockByTeam(Number(team.idTeam));
      notify(`Equipe ${team.teamName} definida para a rua atual.`, 'success');
      setOpenTeamModal(false);
      return;
    }

    setDelegateDTO((previous) => ({
      ...previous,
      teamId: Number(team.idTeam),
      street: preMeasurement.streets.map((street) => ({
        preMeasurementStreetId: street.preMeasurementStreetId,
        teamName: team.teamName,
        truckDepositName: team.depositName,
        prioritized: false,
      })),
    }));

    loadStockByTeam(Number(team.idTeam));
    setFinish(true);
    setOpenTeamModal(false);

    if (!delegateDTO.stockistId) {
      openStockistSelector();
    }
  };

  const selectStockist = () => {
    if (!selectedStockistId) {
      notify('A seleção do estoquista é obrigatória.', 'warn');
      return;
    }

    const stockist = stockists.find((item) => item.userId === selectedStockistId);
    if (!stockist || !preMeasurement) return;

    setDelegateDTO((previous) => ({
      ...previous,
      stockistId: stockist.userId,
      stockistName: stockist.name,
      stockistDepositName: stockist.depositName,
      stockistDepositAddress: stockist.depositAddress ?? '',
      stockistPhone: stockist.depositPhone ?? '',
      description: `Etapa ${preMeasurement.step} - ${preMeasurement.city}`,
    }));

    if (!isMultiTeam) {
      setFinish(true);
    }

    notify('Estoquista responsável definido com sucesso.', 'success');
    setOpenStockistPanel(false);
  };

  const togglePriority = () => {
    if (!streetId) return;

    setDelegateDTO((previous) => ({
      ...previous,
      street: previous.street.map((street) =>
        street.preMeasurementStreetId === streetId
          ? {
              ...street,
              prioritized: !street.prioritized,
            }
          : street,
      ),
    }));
  };

  const finishStreet = () => {
    if (!preMeasurement || !currentStreetReserve) return;

    if (!currentStreetReserve.teamName) {
      notify('Selecione a equipe da rua antes de concluir.', 'warn');
      return;
    }

    setCompletedStreetIds((previous) => {
      const next = previous.includes(streetId) ? previous : [...previous, streetId];

      const nextStreetId = findFirstPendingStreetId(preMeasurement, next);
      if (nextStreetId === 0) {
        setFinish(true);
        if (!delegateDTO.stockistId) {
          openStockistSelector();
        }
      } else {
        setStreetId(nextStreetId);
      }

      return next;
    });

    notify('Rua salva com sucesso.', 'success');
  };

  const getTruckMaterials = (streetIdParam: number) =>
    localStockStreet.find((street) => street.streetId === streetIdParam)?.materialsInTruck ?? [];

  const sendData = async () => {
    if (!delegateDTO.stockistId) {
      notify('Selecione o estoquista responsável antes de continuar.', 'warn');
      openStockistSelector();
      return;
    }

    if (delegateDTO.street.length === 0) {
      notify('Nenhuma rua foi selecionada para delegação.', 'warn');
      return;
    }

    setLoading(true);
    try {
      await preMeasurementsApi.delegateExecution(delegateDTO);
      setShowMessage(true);
      notify('Execução delegada com sucesso.', 'success');
    } catch (error: unknown) {
      const message = error instanceof Error ? error.message : 'Erro ao delegar execução.';
      notify(message, 'error');
    } finally {
      setLoading(false);
    }
  };

  if (loading) {
    return (
      <section className="flex min-h-64 items-center justify-center p-4 md:p-6">
        <i className="pi pi-spin pi-spinner text-2xl text-blue-500" />
      </section>
    );
  }

  if (!preMeasurement) {
    return null;
  }

  if (showMessage) {
    return (
      <section className="p-4 md:p-6">
        <div className="mx-auto max-w-4xl rounded-2xl border border-emerald-200 bg-emerald-50 p-8 text-center dark:border-emerald-900/40 dark:bg-emerald-950/20">
          <i className="pi pi-check-circle text-5xl text-emerald-500" />
          <h2 className="mt-4 text-xl font-semibold text-emerald-800 dark:text-emerald-200">
            Execução delegada com sucesso
          </h2>
          <p className="mt-2 text-sm text-emerald-700 dark:text-emerald-300">
            A pré-medição está disponível na tela de gerenciamento de estoque - pré-instalação.
          </p>
          <button
            type="button"
            onClick={() => navigate('/requisicoes/instalacoes/gerenciamento-estoque')}
            className="mt-4 rounded-xl bg-emerald-600 px-4 py-2 text-sm font-semibold text-white hover:bg-emerald-500"
          >
            Abrir gerenciamento de estoque
          </button>
        </div>
      </section>
    );
  }

  return (
    <section className="space-y-4 p-4 md:p-6">
      <header className="rounded-xl border border-slate-200 bg-white px-4 py-3 dark:border-zinc-800 dark:bg-zinc-900">
        <h1 className="text-base font-semibold text-slate-800 dark:text-zinc-100">
          Pré-medição - {preMeasurement.city}
        </h1>
        <p className="text-xs text-slate-500 dark:text-zinc-400">Etapa {preMeasurement.step}</p>
      </header>

      {openStockistPanel && (
        <div className="rounded-2xl border border-blue-200 bg-blue-50 p-4 dark:border-blue-900/40 dark:bg-blue-950/20">
          <h3 className="text-sm font-semibold text-blue-800 dark:text-blue-200">Selecionar Estoquista Responsável</h3>
          <p className="mt-1 text-xs text-blue-700 dark:text-blue-300">
            Defina quem irá gerenciar a reserva dos materiais para a execução.
          </p>

          <div className="mt-3 flex flex-wrap items-center gap-2">
            <div className="min-w-72">
              <GlassListbox
                value={selectedStockistId}
                onChange={(value) => setSelectedStockistId(value ?? '')}
                placeholder="Selecione"
                options={[
                  { value: '', label: 'Selecione' },
                  ...stockists.map((stockist) => ({
                    value: stockist.userId,
                    label: stockist.name,
                  })),
                ]}
              />
            </div>

            <button
              type="button"
              onClick={selectStockist}
              className="rounded-xl bg-blue-600 px-3 py-2 text-sm font-semibold text-white hover:bg-blue-500"
            >
              Salvar
            </button>
          </div>
        </div>
      )}

      {finish ? (
        <div className="space-y-4">
          <div className="flex flex-wrap items-center justify-between gap-2">
            <h2 className="text-lg font-semibold text-slate-800 dark:text-zinc-100">Resumo da Delegação</h2>
            <div className="flex gap-2">
              <button
                type="button"
                onClick={() => navigate('/pre-medicao/disponivel')}
                className="rounded-xl border border-slate-300 px-3 py-1.5 text-sm font-semibold text-slate-700 hover:bg-slate-100 dark:border-zinc-700 dark:text-zinc-200 dark:hover:bg-zinc-800"
              >
                Cancelar
              </button>
              <button
                type="button"
                onClick={() => setOpenTeamModal(true)}
                className="rounded-xl border border-slate-300 px-3 py-1.5 text-sm font-semibold text-slate-700 hover:bg-slate-100 dark:border-zinc-700 dark:text-zinc-200 dark:hover:bg-zinc-800"
              >
                Editar equipe
              </button>
              <button
                type="button"
                onClick={openStockistSelector}
                className="rounded-xl border border-slate-300 px-3 py-1.5 text-sm font-semibold text-slate-700 hover:bg-slate-100 dark:border-zinc-700 dark:text-zinc-200 dark:hover:bg-zinc-800"
              >
                Editar estoquista
              </button>
              <button
                type="button"
                onClick={() => void sendData()}
                className="rounded-xl bg-slate-900 px-3 py-1.5 text-sm font-semibold text-white hover:bg-slate-700 dark:bg-zinc-100 dark:text-zinc-900 dark:hover:bg-zinc-300"
              >
                Continuar
              </button>
            </div>
          </div>

          {!!delegateDTO.stockistName && (
            <div className="rounded-xl border border-slate-200 bg-white p-3 text-sm dark:border-zinc-800 dark:bg-zinc-900">
              <p><strong>Estoquista:</strong> {delegateDTO.stockistName}</p>
              <p><strong>Depósito:</strong> {delegateDTO.stockistDepositName || '-'}</p>
              <p><strong>Telefone:</strong> {delegateDTO.stockistPhone || '-'}</p>
            </div>
          )}

          <div className="rounded-xl border border-slate-200 bg-white p-3 dark:border-zinc-800 dark:bg-zinc-900">
            <label className="mb-2 block text-xs font-semibold uppercase tracking-wider text-slate-500 dark:text-zinc-400">
              Comentário para a equipe
            </label>
            <textarea
              value={delegateDTO.comment}
              onChange={(event) =>
                setDelegateDTO((previous) => ({
                  ...previous,
                  comment: event.target.value,
                }))
              }
              rows={3}
              placeholder="Inserir comentário para a equipe (se necessário)"
              className="w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm dark:border-zinc-700 dark:bg-zinc-900"
            />
          </div>

          <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white dark:border-zinc-800 dark:bg-zinc-900">
            <div className="overflow-x-auto">
              <table className="min-w-[760px] w-full">
                <thead className="bg-slate-50 text-left text-xs uppercase tracking-wider text-slate-500 dark:bg-zinc-900/50 dark:text-zinc-400">
                  <tr>
                    <th className="px-4 py-3">Prioridade</th>
                    <th className="px-4 py-3">Rua</th>
                    <th className="px-4 py-3">Equipe</th>
                    <th className="px-4 py-3">Almox. Prioritário</th>
                  </tr>
                </thead>
                <tbody>
                  {preMeasurement.streets.map((street) => {
                    const reserve =
                      delegateDTO.street.find((item) => item.preMeasurementStreetId === street.preMeasurementStreetId) ??
                      null;

                    return (
                      <tr key={street.preMeasurementStreetId} className="border-t border-slate-100 dark:border-zinc-800">
                        <td className="px-4 py-3">
                          {reserve?.prioritized ? (
                            <i className="pi pi-exclamation-triangle text-amber-500" />
                          ) : (
                            <span className="text-xs text-slate-400">-</span>
                          )}
                        </td>
                        <td className="px-4 py-3 text-sm text-slate-700 dark:text-zinc-200">{street.address}</td>
                        <td className="px-4 py-3 text-sm text-slate-700 dark:text-zinc-200">{reserve?.teamName || '-'}</td>
                        <td className="px-4 py-3 text-sm text-slate-700 dark:text-zinc-200">{reserve?.truckDepositName || '-'}</td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      ) : (
        <div className="space-y-4">
          {isMultiTeam && (
            <div className="relative rounded-2xl border border-slate-200 bg-white p-3 dark:border-zinc-800 dark:bg-zinc-900">
              <div ref={streetsSliderRef} className="no-scrollbar flex gap-2 overflow-x-auto px-8 pb-1">
                {preMeasurement.streets.map((street) => {
                  const selected = street.preMeasurementStreetId === streetId;
                  const completed = completedStreetIds.includes(street.preMeasurementStreetId);
                  const reserve = delegateDTO.street.find(
                    (item) => item.preMeasurementStreetId === street.preMeasurementStreetId,
                  );

                  return (
                    <button
                      key={street.preMeasurementStreetId}
                      type="button"
                      onClick={() => setStreetId(street.preMeasurementStreetId)}
                      className={`min-w-[280px] rounded-xl border p-4 text-left transition ${
                        selected
                          ? 'border-orange-400 bg-slate-100 dark:bg-zinc-800'
                          : 'border-slate-200 hover:scale-[1.02] dark:border-zinc-700'
                      }`}
                    >
                      <p className="text-sm font-semibold text-slate-800 dark:text-zinc-100">{street.address}</p>
                      <p className="mt-1 text-xs text-slate-500 dark:text-zinc-400">
                        {street.items.length} itens pendentes de reserva
                      </p>
                      <p className="mt-2 text-xs font-semibold">
                        {completed ? 'RUA CONCLUÍDA' : reserve?.teamName ? 'EQUIPE DEFINIDA' : 'PENDENTE'}
                      </p>
                    </button>
                  );
                })}
              </div>
              <button
                type="button"
                onClick={() => scrollStreets(-300)}
                className="absolute left-2 top-1/2 -translate-y-1/2 text-slate-500 transition hover:text-slate-700 dark:text-zinc-400 dark:hover:text-zinc-200"
                aria-label="Voltar ruas"
              >
                <i className="pi pi-chevron-left" />
              </button>
              <button
                type="button"
                onClick={() => scrollStreets(300)}
                className="absolute right-2 top-1/2 -translate-y-1/2 text-slate-500 transition hover:text-slate-700 dark:text-zinc-400 dark:hover:text-zinc-200"
                aria-label="Avançar ruas"
              >
                <i className="pi pi-chevron-right" />
              </button>
            </div>
          )}

          <div className="grid grid-cols-1 gap-4 xl:grid-cols-[minmax(0,1fr)_360px]">
            <div className="rounded-2xl border border-slate-200 bg-white p-4 dark:border-zinc-800 dark:bg-zinc-900">
              <div className="mb-3 flex flex-wrap items-center justify-between gap-2 border-b border-slate-100 pb-3 dark:border-zinc-800">
                <h3 className="text-sm font-semibold text-slate-700 dark:text-zinc-200">
                  {currentStreet?.address ?? 'Selecione uma rua'}
                </h3>
                <button
                  type="button"
                  onClick={togglePriority}
                  className={`inline-flex items-center gap-2 rounded-lg border px-2.5 py-1 text-xs font-semibold transition ${
                    currentStreetReserve?.prioritized
                      ? 'border-amber-300 bg-amber-50 text-amber-700 dark:border-amber-800 dark:bg-amber-900/30 dark:text-amber-300'
                      : 'border-slate-300 text-slate-600 hover:bg-slate-100 dark:border-zinc-700 dark:text-zinc-300 dark:hover:bg-zinc-800'
                  }`}
                >
                  <i className="pi pi-exclamation-triangle" />
                  {currentStreetReserve?.prioritized ? 'Com prioridade' : 'Sem prioridade'}
                </button>
              </div>

              <div className="space-y-3 text-sm text-slate-600 dark:text-zinc-300">
                <p>
                  <strong>Equipe:</strong>{' '}
                  {streetTeam ? `EQUIPE ${streetTeam.teamName.toUpperCase()}` : 'NENHUMA EQUIPE SELECIONADA'}
                </p>
                <p>
                  <strong>Almoxarifado do caminhão:</strong>{' '}
                  {currentStreetReserve?.truckDepositName || '-'}
                </p>

                <div className="flex flex-wrap gap-2 pt-1">
                  <button
                    type="button"
                    onClick={() => setOpenTeamModal(true)}
                    className="rounded-xl bg-blue-600 px-3 py-1.5 text-xs font-semibold text-white hover:bg-blue-500"
                  >
                    Selecionar Equipe
                  </button>

                  {isMultiTeam && (
                    <button
                      type="button"
                      onClick={finishStreet}
                      className="rounded-xl bg-slate-900 px-3 py-1.5 text-xs font-semibold text-white hover:bg-slate-700 dark:bg-zinc-100 dark:text-zinc-900 dark:hover:bg-zinc-300"
                    >
                      Concluir Rua
                    </button>
                  )}
                </div>
              </div>
            </div>

            <div className="rounded-2xl border border-slate-200 bg-white p-4 dark:border-zinc-800 dark:bg-zinc-900">
              <h3 className="mb-2 text-sm font-semibold text-slate-700 dark:text-zinc-200">Estoque no caminhão</h3>

              <div className="max-h-[330px] overflow-auto">
                {getTruckMaterials(streetId).length === 0 ? (
                  <p className="text-xs text-slate-500 dark:text-zinc-400">
                    Nenhum material em estoque para a rua/equipe selecionada.
                  </p>
                ) : (
                  <table className="w-full text-xs">
                    <thead>
                      <tr className="text-left text-slate-500 dark:text-zinc-400">
                        <th className="pb-2">Material</th>
                        <th className="pb-2 text-right">Nec.</th>
                        <th className="pb-2 text-right">Disp.</th>
                      </tr>
                    </thead>
                    <tbody>
                      {getTruckMaterials(streetId).map((material) => (
                        <tr key={`${material.materialId}-${material.deposit}`} className="border-t border-slate-100 dark:border-zinc-800">
                          <td className="py-2 pr-2 text-slate-700 dark:text-zinc-200">{material.materialName}</td>
                          <td className="py-2 text-right text-slate-600 dark:text-zinc-300">{material.itemQuantity}</td>
                          <td className="py-2 text-right">
                            <span className={material.availableQuantity >= material.itemQuantity ? 'text-emerald-600' : 'text-rose-600'}>
                              {material.availableQuantity}
                            </span>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                )}
              </div>
            </div>
          </div>
        </div>
      )}

      <Modal open={openTeamModal} onClose={() => setOpenTeamModal(false)} className="max-w-3xl">
        <ModalHeader title="Selecionar Equipe Operacional" onClose={() => setOpenTeamModal(false)} />
        <ModalBody>
          <div className="overflow-hidden rounded-xl border border-slate-200 dark:border-zinc-800">
            <div className="overflow-x-auto">
              <table className="min-w-full text-sm">
                <thead className="bg-slate-50 text-left text-xs uppercase tracking-wider text-slate-500 dark:bg-zinc-900/50 dark:text-zinc-400">
                  <tr>
                    <th className="px-4 py-3">Equipe</th>
                    <th className="px-4 py-3">Colaboradores</th>
                    <th className="px-4 py-3">Placa</th>
                    <th className="px-4 py-3">Região</th>
                  </tr>
                </thead>
                <tbody>
                  {teams.map((team) => (
                    <tr
                      key={team.idTeam}
                      onClick={() => selectTeam(team)}
                      className="cursor-pointer border-t border-slate-100 transition hover:bg-blue-50 dark:border-zinc-800 dark:hover:bg-blue-900/20"
                    >
                      <td className="px-4 py-3 text-slate-700 dark:text-zinc-200">{team.teamName}</td>
                      <td className="px-4 py-3 text-slate-600 dark:text-zinc-300">{team.memberNames.join(', ')}</td>
                      <td className="px-4 py-3 text-slate-600 dark:text-zinc-300">{team.plate}</td>
                      <td className="px-4 py-3 text-slate-600 dark:text-zinc-300">{team.regionName}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </ModalBody>
        <ModalFooter>
          <button
            type="button"
            onClick={() => setOpenTeamModal(false)}
            className="rounded-lg border border-slate-300 px-3 py-1.5 text-sm font-semibold text-slate-700 hover:bg-slate-100 dark:border-zinc-700 dark:text-zinc-200 dark:hover:bg-zinc-800"
          >
            Fechar
          </button>
        </ModalFooter>
      </Modal>
    </section>
  );
}
