// react-app/src/features/stock/pages/stockists.tsx
import { useState, useEffect, useMemo } from 'react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { useAuthStore } from '@/core/auth/useAuthStore';
import { useAppStore } from '@/store/use-app-store';
import { useNotify } from '@/shared/hooks/use-notify';
import { Modal, ModalHeader, ModalBody, ModalFooter } from '@/shared/ui/modal';
import { GlassListbox } from '@/shared/components/glass-list-box';
import { EmbeddedDocPanel } from '@/shared/components/embedded-doc-panel';
import { useUsers } from '@/features/manage/hooks/useUsers';

import { stockKeys } from '@/features/stock/api/query-keys';
import { useStockists } from '@/features/stock/hooks/use-stockists';
import { useDeposits } from '@/features/stock/hooks/use-deposits';
import type { Deposit } from '@/features/stock/types/types';
import { stockistApi } from '../api/stockist-api';
import { Table, TableRow, TableHead, TableHeader, TableCell, TableBody } from '@/shared/components/ui/table';
import {showPhoneFormatted} from '@/shared/utils/formatters';

export default function Stockists() {
  const { setPageContext } = useAppStore();
  const { user } = useAuthStore();
  const { notify } = useNotify();
  const queryClient = useQueryClient();

  const [modalOpen, setModalOpen] = useState(false);
  const [deleteId, setDeleteId] = useState<number | null>(null);
  const [docOpen, setDocOpen] = useState(false);
  const [form, setForm] = useState({ depositId: '', userId: '' });

  useEffect(() => {
    setPageContext(['Configurações', 'Estoquistas'], 'Estoquistas');
  }, [setPageContext]);

  const { data: stockists = [], isLoading } = useStockists();
  const { data: depositsRaw = [] } = useDeposits();
  const { data: users = [] } = useUsers();

  const isAdmin = user?.roles.includes('ADMIN') ?? false;
  const saveMutation = useMutation({
    mutationFn: ({ depositId, userId }: { depositId: string; userId: string }) => stockistApi.insertStockist({
      depositIdDeposit: Number(depositId),
      userIdUser: userId,
    }),
    onSuccess: async () => {
      await queryClient.invalidateQueries({ queryKey: stockKeys.stockists() });
    },
  });
  const deleteMutation = useMutation({
    mutationFn: (id: number) => stockistApi.deleteStockist(id),
    onSuccess: async () => {
      await queryClient.invalidateQueries({ queryKey: stockKeys.stockists() });
    },
  });

  const deposits = useMemo(
    () => (depositsRaw as Deposit[]).filter((deposit) => !deposit.isTruck),
    [depositsRaw],
  );
  const hasNoDeposits = deposits.length === 0;

  return (
    <section className="p-4 md:p-6 space-y-4">
      <div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
        <div>
          <h1 className="text-2xl font-semibold text-slate-800 dark:text-zinc-100">Estoquistas</h1>
          <p className="text-sm text-slate-500 dark:text-zinc-400">
            Cadastre e gerencie os responsáveis pelos almoxarifados do sistema.
          </p>
        </div>

        <div className="flex flex-wrap gap-2">
          <button
            type="button"
            onClick={() => setDocOpen(true)}
            className="flex items-center gap-2 rounded-xl border border-slate-200 dark:border-zinc-700 px-4 py-2 text-sm font-semibold text-slate-700 dark:text-zinc-200 hover:bg-slate-50 dark:hover:bg-zinc-800 transition-colors"
          >
            <i className="pi pi-book text-sm" /> Como cadastrar
          </button>

          {isAdmin && (
            <button
              type="button"
              onClick={() => {
                setForm({ depositId: '', userId: '' });
                setModalOpen(true);
              }}
              disabled={hasNoDeposits}
              className="flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2 text-sm font-semibold text-white hover:bg-indigo-500 disabled:opacity-60 disabled:cursor-not-allowed transition-colors"
            >
              <i className="pi pi-plus text-sm" /> Novo Estoquista
            </button>
          )}
        </div>
      </div>

      <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
        <div className="rounded-2xl border border-neutral-200 bg-white p-4 shadow-sm dark:border-neutral-800 dark:bg-neutral-900">
          <p className="text-sm text-slate-500 dark:text-zinc-400">Estoquistas vinculados</p>
          <p className="mt-2 text-3xl font-semibold text-slate-900 dark:text-zinc-100">{stockists.length}</p>
        </div>

        <div className="rounded-2xl border border-neutral-200 bg-white p-4 shadow-sm dark:border-neutral-800 dark:bg-neutral-900">
          <p className="text-sm text-slate-500 dark:text-zinc-400">Almoxarifados disponíveis</p>
          <p className="mt-2 text-3xl font-semibold text-slate-900 dark:text-zinc-100">{deposits.length}</p>
        </div>

        <div className="rounded-2xl border border-neutral-200 bg-white p-4 shadow-sm dark:border-neutral-800 dark:bg-neutral-900">
          <p className="text-sm text-slate-500 dark:text-zinc-400">Usuários ativos</p>
          <p className="mt-2 text-3xl font-semibold text-slate-900 dark:text-zinc-100">{users.length}</p>
        </div>
      </div>

      {hasNoDeposits && !isLoading ? (
        <div className="rounded-2xl border border-amber-200 bg-amber-50 p-5 dark:border-amber-900 dark:bg-amber-950/30">
          <h3 className="text-base font-semibold text-amber-900 dark:text-amber-100">
            Antes de vincular estoquistas...
          </h3>
          <p className="mt-1 text-sm text-amber-800 dark:text-amber-200">
            Você precisa cadastrar almoxarifados para liberar este fluxo.
          </p>
          <button
            type="button"
            onClick={() => window.location.assign('/estoque/almoxarifados')}
            className="mt-4 inline-flex items-center gap-2 rounded-xl bg-amber-600 px-4 py-2 text-sm font-semibold text-white hover:bg-amber-500 transition-colors"
          >
            <i className="pi pi-home text-sm" />
            Cadastrar Almoxarifados
          </button>
        </div>
      ) : (

        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Usuário</TableHead>
              <TableHead>Almoxarifado</TableHead>
              <TableHead>Contato</TableHead>
              <TableHead>Ações</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {stockists.map((stockist) => {
              const deposit = deposits.find((d) => d.idDeposit === stockist.depositId);

              return (
                <TableRow key={stockist.stockistId ?? stockist.userId}>
                  <TableCell>
                    <p className="font-medium">{stockist.name}</p>
                  </TableCell>
                  <TableCell>
                    <div>
                      <p className="font-semibold">{stockist.depositName}</p>
                      <p className="text-xs text-slate-500 dark:text-zinc-400">{deposit?.depositRegion ?? ''}</p>
                    </div>
                  </TableCell>
                  <TableCell>
                    <p 
                      className="text-sm text-slate-600 dark:text-zinc-300" >
                      {deposit?.depositPhone && deposit.depositPhone !== '' ? showPhoneFormatted(deposit.depositPhone) : 'Telefone não cadastrado'}
                    </p>
                  </TableCell>
                  <TableCell>
                    <div className="flex items-center gap-2 justify-end">
                      <button
                        type="button"
                        onClick={() => {
                          setForm({ depositId: stockist.depositId.toString(), userId: stockist.userId });
                          setModalOpen(true);
                        }}
                        className="rounded-lg border border-slate-200 dark:border-zinc-700 p-2 text-sm font-semibold text-slate-600 dark:text-zinc-400 hover:bg-slate-50 dark:hover:bg-zinc-800 transition-colors">
                        <i className="pi pi-pencil text-sm" />
                      </button>
                      <button
                        type="button"
                        onClick={() => setDeleteId(stockist.stockistId ?? null)}
                        className="rounded-lg border border-neutral-200 dark:border-zinc-700 p-2 text-sm font-semibold text-red-600 hover:bg-red-50 transition-colors"
                      >
                        <i className="pi pi-trash text-sm" />
                      </button>
                    </div>
                  </TableCell>
                </TableRow>
              )
            })}
          </TableBody>
        </Table>

      )}

      <EmbeddedDocPanel
        open={docOpen}
        onClose={() => setDocOpen(false)}
        title="Cadastro de Estoquistas"
        description="Guia para cadastrar responsáveis por almoxarifados e estruturar o controle de estoque."
        url="https://lumosip.com.br/como-usar/04-stock/01-stockist-management/"
      />

      <Modal open={modalOpen} onClose={() => setModalOpen(false)} confirmation>
        <ModalHeader title="Vincular Estoquista" onClose={() => setModalOpen(false)} />
        <ModalBody className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-slate-700 dark:text-zinc-200 mb-1">Almoxarifado*</label>
            <GlassListbox
              searchable={true}
              value={form.depositId}
              onChange={(value) => setForm((previous) => ({ ...previous, depositId: value ?? '' }))}
              placeholder="Selecione o almoxarifado"
              options={[
                ...deposits.map((deposit) => ({
                  value: String(deposit.idDeposit),
                  label: deposit.depositName,
                })),
              ]}
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-slate-700 dark:text-zinc-200 mb-1">Usuário*</label>
            <GlassListbox
              value={form.userId}
              onChange={(value) => setForm((previous) => ({ ...previous, userId: value ?? '' }))}
              placeholder="Selecione o usuário"
              searchable={true}
              options={[
                ...users
                  .filter((user) => {
                    const roles = user.role.map((role) => role.roleName);
                    return roles.includes('ESTOQUISTA')
                      || roles.includes('ESTOQUISTA_CHEFE')
                      || roles.includes('ADMIN');
                  })
                  .sort((a, b) => a.name.localeCompare(b.name))
                  .map((managedUser) => ({
                    value: managedUser.userId,
                    label: `${managedUser.name} ${managedUser.lastname}`,
                  })),
              ]}
            />
          </div>
        </ModalBody>
        <ModalFooter>
          <button
            type="button"
            onClick={() => setModalOpen(false)}
            className="rounded-xl border border-slate-200 dark:border-zinc-700 px-4 py-2 text-sm font-semibold text-slate-600 dark:text-zinc-400 hover:bg-slate-50 dark:hover:bg-zinc-800 transition-colors"
          >
            Cancelar
          </button>
          <button
            type="button"
            disabled={!form.depositId || !form.userId || saveMutation.isPending}
            onClick={() =>
              saveMutation.mutate(
                { depositId: form.depositId, userId: form.userId },
                {
                  onSuccess: () => {
                    notify('Estoquista cadastrado.', 'success');
                    setModalOpen(false);
                    setForm({ depositId: '', userId: '' });
                  },
                  onError: (error: unknown) => {
                    const message = (error as { response?: { data?: { message?: string } } })?.response?.data?.message;
                    notify(message ?? 'Erro ao cadastrar estoquista.', 'error');
                  },
                },
              )
            }
            className="rounded-xl bg-indigo-600 px-4 py-2 text-sm font-semibold text-white hover:bg-indigo-500 disabled:opacity-50 transition-colors"
          >
            {saveMutation.isPending && <i className="pi pi-spin pi-spinner mr-1.5 text-xs" />}
            Vincular
          </button>
        </ModalFooter>
      </Modal>

      <Modal open={deleteId !== null} onClose={() => setDeleteId(null)} confirmation>
        <ModalHeader title="Remover Estoquista" onClose={() => setDeleteId(null)} />
        <ModalBody>
          <p className="text-sm text-slate-600 dark:text-zinc-300">
            Confirma a remoção deste estoquista do almoxarifado?
          </p>
        </ModalBody>
        <ModalFooter>
          <button
            type="button"
            onClick={() => setDeleteId(null)}
            className="rounded-xl border border-slate-200 dark:border-zinc-700 px-4 py-2 text-sm font-semibold text-slate-600 dark:text-zinc-400 hover:bg-slate-50 dark:hover:bg-zinc-800 transition-colors"
          >
            Cancelar
          </button>
          <button
            type="button"
            disabled={deleteMutation.isPending}
            onClick={() =>
              deleteId !== null &&
              deleteMutation.mutate(deleteId, {
                onSuccess: () => {
                  notify('Estoquista removido.', 'success');
                  setDeleteId(null);
                },
                onError: (error: unknown) => {
                  const message = (error as { response?: { data?: { message?: string } } })?.response?.data?.message;
                  notify(message ?? 'Erro ao remover estoquista.', 'error');
                  setDeleteId(null);
                },
              })
            }
            className="rounded-xl bg-red-600 px-4 py-2 text-sm font-semibold text-white hover:bg-red-500 disabled:opacity-50 transition-colors"
          >
            {deleteMutation.isPending && <i className="pi pi-spin pi-spinner mr-1.5 text-xs" />}
            Remover
          </button>
        </ModalFooter>
      </Modal>
    </section>
  );
}

// angular-app/src/app/stock/stockists/stockists.component.ts
import {NgClass, NgForOf, NgIf} from '@angular/common';
import {Component} from '@angular/core';
import {FormsModule, NgForm} from '@angular/forms';
import {Title} from '@angular/platform-browser';
import {Router} from '@angular/router';
import {catchError, finalize, forkJoin, map, of, switchMap, tap, throwError} from 'rxjs';
import {Toast} from 'primeng/toast';
import {Select} from 'primeng/select';
import {Tag} from 'primeng/tag';
import {StockService} from '../services/stock.service';
import {Deposit} from '../dto/almoxarifado.model';
import {
    CreateStockistRequest,
    StockistManagement,
    UpdateStockistRequest
} from '../dto/stockist.model';
import {UserService} from '../../manage/user/user-service.service';
import {SharedState} from '../../core/service/shared-state';
import {Utils} from '../../core/service/utils';
import {UtilsService} from '../../core/service/utils.service';
import {AuthService} from '../../core/auth/auth.service';
import {LoadingComponent} from '../../shared/components/loading/loading.component';
import {ModalComponent} from '../../shared/components/modal/modal.component';
import {ButtonComponent} from '../../shared/components/button/button.component';
import { GuideStateComponent } from '../../guide-state/guide-state.component';
import { LoadingOverlayComponent } from '../../shared/components/loading-overlay/loading-overlay.component';

interface UserOption {
    userId: string;
    name: string;
    email: string;
    username: string;
    role: string[];
    status: boolean;
}

interface StockistFormValue {
    stockistId: number | null;
    depositIdDeposit: number | null;
    userIdUser: string | null;
    notificationCode: string;
}

@Component({
    selector: 'app-stockists',
    standalone: true,
    imports: [
        FormsModule,
        NgIf,
        NgForOf,
        NgClass,
        Toast,
        Select,
        Tag,
        LoadingComponent,
        ModalComponent,
        ButtonComponent,
        GuideStateComponent,
        LoadingOverlayComponent,
        LoadingComponent
    ],
    templateUrl: './stockists.component.html',
    styleUrl: './stockists.component.scss'
})
export class StockistsComponent {
    formOpen = false;
    formSubmitted = false;
    loading = false;
    isInitialLoading = true;
    saving = false;
    showConfirmation = false;
    isFallbackData = false;

    deposits: Deposit[] = [];
    availableUsers: UserOption[] = [];
    stockists: StockistManagement[] = [];
    selectedStockist: StockistManagement | null = null;

    stockist: StockistFormValue = this.createEmptyForm();

    constructor(
        private stockService: StockService,
        private userService: UserService,
        private authService: AuthService,
        private utils: UtilsService,
        private title: Title,
        protected router: Router
    ) {
        this.title.setTitle('Configurações - Estoquistas');
        SharedState.setCurrentPath(['Configurações', 'Estoquistas']);
        this.loadPageData();
    }

    setOpen(force?: boolean) {
        this.formOpen = force ?? !this.formOpen;

        if (!this.formOpen) {
            this.resetForm();
        }
    }

    onSubmit(form: NgForm) {
        this.formSubmitted = true;

        if (form.invalid || !this.stockist.depositIdDeposit || !this.stockist.userIdUser) {
            return;
        }

        if (this.hasDuplicateAssociation()) {
            this.utils.showMessage(
                'Esse usuário já está vinculado ao almoxarifado selecionado.',
                'warn',
                'Vínculo duplicado'
            );
            return;
        }

        this.saving = true;

        const payload = this.buildPayload();
        const request$ = this.stockist.stockistId
            ? this.stockService.updateStockist(payload as UpdateStockistRequest)
            : this.stockService.insertStockist(payload as CreateStockistRequest);

        request$
            .pipe(
                switchMap(() => this.loadStockists()),
                tap(stockists => {
                    this.stockists = stockists;
                    this.utils.showMessage(
                        this.stockist.stockistId ? 'Estoquista atualizado com sucesso.' : 'Estoquista cadastrado com sucesso.',
                        'success',
                        'Estoque'
                    );
                    this.setOpen(false);
                }),
                catchError(err => {
                    this.utils.showMessage(err?.error?.message ?? 'Não foi possível salvar o estoquista.', 'error', 'Atenção');
                    return throwError(() => err);
                }),
                finalize(() => this.saving = false)
            )
            .subscribe();
    }

    editStockist(stockist: StockistManagement) {
        this.stockist = {
            stockistId: stockist.stockistId,
            depositIdDeposit: stockist.depositIdDeposit,
            userIdUser: stockist.userIdUser,
            notificationCode: stockist.notificationCode || this.generateUuid()
        };
        this.formSubmitted = false;
        this.formOpen = true;
    }

    confirmDelete(stockist: StockistManagement) {
        if (!stockist.stockistId) {
            this.utils.showMessage(
                'Esse registro veio do endpoint legado de consulta e não possui identificador para exclusão direta.',
                'info',
                'Ação indisponível'
            );
            return;
        }

        this.selectedStockist = stockist;
        this.showConfirmation = true;
    }

    deleteStockist() {
        if (!this.selectedStockist?.stockistId) {
            this.showConfirmation = false;
            return;
        }

        this.saving = true;
        this.stockService.deleteStockist(this.selectedStockist.stockistId)
            .pipe(
                switchMap(() => this.loadStockists()),
                tap(stockists => {
                    this.stockists = stockists;
                    this.showConfirmation = false;
                    this.selectedStockist = null;
                    this.utils.showMessage('Estoquista removido com sucesso.', 'success', 'Estoque');
                }),
                catchError(err => {
                    this.showConfirmation = false;
                    this.utils.showMessage(err?.error?.message ?? 'Não foi possível remover o estoquista.', 'error', 'Atenção');
                    return throwError(() => err);
                }),
                finalize(() => this.saving = false)
            )
            .subscribe();
    }

    getUserLabel(userId: string | null): string {
        if (!userId) {
            return '';
        }

        const user = this.availableUsers.find(item => item.userId === userId);
        return user ? `${user.name} (${user.email})` : '';
    }

    getDepositLabel(depositId: number | null): string {
        if (!depositId) {
            return '';
        }

        return this.deposits.find(item => item.idDeposit === depositId)?.depositName ?? '';
    }

    getSeverity(roles: string[]): 'success' | 'info' | 'contrast' | 'warn' {
        if (roles.includes('ADMIN')) {
            return 'contrast';
        }

        if (roles.includes('ESTOQUISTA_CHEFE')) {
            return 'success';
        }

        if (roles.includes('ESTOQUISTA')) {
            return 'info';
        }

        return 'warn';
    }

    private loadPageData() {
        this.isInitialLoading = true;

        forkJoin({
            deposits: this.stockService.getDeposits().pipe(
                map(deposits => deposits.filter(deposit => !deposit.isTruck))
            ),
            users: this.userService.getUsers().pipe(
                map(users => users
                    .filter(user => user.status)
                    .map(user => ({
                        userId: user.userId,
                        name: `${user.name} ${user.lastname}`.trim(),
                        email: user.email,
                        username: user.username,
                        role: user.role ?? [],
                        status: user.status
                    }))
                    .sort((a, b) => a.name.localeCompare(b.name, 'pt-BR'))
                )
            ),
            stockists: this.loadStockists()
        }).subscribe({
            next: ({deposits, users, stockists}) => {
                this.deposits = deposits;
                this.availableUsers = users;
                this.stockists = stockists;
                this.isInitialLoading = false;
            },
            error: err => {
                this.isInitialLoading = false;
                Utils.handleHttpError(err, this.router);
            }
        });
    }

    private loadStockists() {
        return this.stockService.getStockists().pipe(
            map(stockists => {
                this.isFallbackData = false;
                return stockists.map(stockist => ({
                        stockistId: null,
                        depositIdDeposit: stockist.depositId,
                        userIdUser: stockist.userId,
                        notificationCode: this.generateUuid(),
                        userName: stockist.name,
                        userEmail: '',
                        userRoles: [],
                        depositName: stockist.depositName,
                        depositAddress: stockist.depositAddress,
                        depositPhone: stockist.depositPhone,
                        depositRegion: stockist.region
                    } satisfies StockistManagement));
            }),
            catchError(() => this.stockService.getStockists().pipe(
                map(stockists => {
                    this.isFallbackData = true;
                    return stockists.map(stockist => ({
                        stockistId: null,
                        depositIdDeposit: stockist.depositId,
                        userIdUser: stockist.userId,
                        notificationCode: this.generateUuid(),
                        userName: stockist.name,
                        userEmail: '',
                        userRoles: [],
                        depositName: stockist.depositName,
                        depositAddress: stockist.depositAddress,
                        depositPhone: stockist.depositPhone,
                        depositRegion: stockist.region
                    } satisfies StockistManagement));
                })
            ))
        );
    }

    private createEmptyForm(): StockistFormValue {
        return {
            stockistId: null,
            depositIdDeposit: null,
            userIdUser: null,
            notificationCode: this.generateUuid(),
        };
    }

    private resetForm() {
        this.formSubmitted = false;
        this.stockist = this.createEmptyForm();
    }

    private buildPayload(): CreateStockistRequest | UpdateStockistRequest {
        return {
            depositIdDeposit: this.stockist.depositIdDeposit!,
            userIdUser: this.stockist.userIdUser!,
        };
    }

    private hasDuplicateAssociation(): boolean {
        return this.stockists.some(existing =>
            existing.userIdUser === this.stockist.userIdUser &&
            existing.depositIdDeposit === this.stockist.depositIdDeposit &&
            existing.stockistId !== this.stockist.stockistId
        );
    }

    private generateUuid(): string {
        if (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function') {
            return crypto.randomUUID();
        }

        return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, character => {
            const random = Math.floor(Math.random() * 16);
            const value = character === 'x' ? random : (random & 0x3) | 0x8;
            return value.toString(16);
        });
    }
}

<p-toast></p-toast>

<app-guide-state
  *ngIf="deposits.length === 0 && !isInitialLoading"
  icon="pi pi-file"
  title="Antes de vincular estoquistas..."
  subtitle="Você precisa preparar a base do sistema antes de continuar."
  [steps]="[
    [true, 'Cadastrar Almoxarifados']
  ]"
  [hasButtonLabel]="true"
  buttonLabel="Cadastrar Almoxarifados"
  buttonRoute="/estoque/almoxarifados"
  buttonIcon="pi pi-home"
></app-guide-state>

<app-loading *ngIf="isInitialLoading"></app-loading>

<div class="w-full px-4 py-6 relative" *ngIf="deposits.length > 0">
    <app-loading-overlay [loading]="loading"></app-loading-overlay>

    <div class="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between mb-6">
        <div>
            <h2 class="text-2xl font-semibold text-gray-800 dark:text-white">
                Estoquistas
            </h2>
            <p class="text-sm text-gray-500 dark:text-gray-400">
                Cadastre e gerencie os responsáveis pelos almoxarifados do sistema.
            </p>
        </div>

        <button
            class="btn btn-primary flex items-center gap-2 w-full sm:w-auto"
            type="button"
            (click)="setOpen()">
            <i class="pi pi-user-plus"></i>
            {{ formOpen ? 'Fechar cadastro' : 'Novo estoquista' }}
        </button>
    </div>

    <div class="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
        <div class="rounded-2xl border border-neutral-200 dark:border-neutral-800 bg-white dark:bg-neutral-900 p-4 shadow-sm">
            <p class="text-sm text-gray-500 dark:text-gray-400">Estoquistas vinculados</p>
            <p class="text-3xl font-semibold text-gray-900 dark:text-white mt-2">{{ stockists.length }}</p>
        </div>

        <div class="rounded-2xl border border-neutral-200 dark:border-neutral-800 bg-white dark:bg-neutral-900 p-4 shadow-sm">
            <p class="text-sm text-gray-500 dark:text-gray-400">Almoxarifados disponíveis</p>
            <p class="text-3xl font-semibold text-gray-900 dark:text-white mt-2">{{ deposits.length }}</p>
        </div>

        <div class="rounded-2xl border border-neutral-200 dark:border-neutral-800 bg-white dark:bg-neutral-900 p-4 shadow-sm">
            <p class="text-sm text-gray-500 dark:text-gray-400">Usuários ativos</p>
            <p class="text-3xl font-semibold text-gray-900 dark:text-white mt-2">{{ availableUsers.length }}</p>
        </div>
    </div>

    <app-loading *ngIf="loading"></app-loading>

    <div
        *ngIf="!loading && formOpen"
        class="mb-6 rounded-2xl border border-neutral-200 dark:border-neutral-800 bg-white dark:bg-neutral-900 p-5 md:p-6 shadow-sm">
        <div class="flex items-start justify-between gap-4 mb-5">
            <div>
                <h3 class="text-lg font-semibold text-gray-900 dark:text-white">
                    {{ stockist.stockistId ? 'Editar vínculo de estoquista' : 'Novo vínculo de estoquista' }}
                </h3>
                <p class="text-sm text-gray-500 dark:text-gray-400">
                    Cada registro relaciona um usuário a um almoxarifado.
                </p>
            </div>

            <button
                class="btn btn-ghost btn-sm"
                type="button"
                (click)="setOpen(false)">
                <i class="pi pi-times"></i>
            </button>
        </div>

        <form #stockistForm="ngForm" (ngSubmit)="onSubmit(stockistForm)" class="flex flex-col gap-5">
            <div class="grid grid-cols-1 xl:grid-cols-2 gap-4">
                <div class="flex flex-col gap-2">
                    <label for="userIdUser" class="text-sm font-medium text-gray-700 dark:text-gray-200">
                        Usuário
                    </label>

                    <p-select
                        inputId="userIdUser"
                        name="userIdUser"
                        [(ngModel)]="stockist.userIdUser"
                        [options]="availableUsers"
                        optionLabel="name"
                        optionValue="userId"
                        placeholder="Selecione o usuário"
                        [filter]="true"
                        filterBy="name,email,username"
                        appendTo="body"
                        styleClass="w-full">
                        <ng-template let-user pTemplate="item">
                            <div class="flex flex-col py-1">
                                <span class="font-medium">{{ user.name }}</span>
                                <small class="text-gray-500">{{ user.email }}</small>
                            </div>
                        </ng-template>
                    </p-select>

                    <small *ngIf="!stockist.userIdUser && formSubmitted" class="text-red-600 dark:text-red-400">
                        Selecione um usuário.
                    </small>
                </div>

                <div class="flex flex-col gap-2">
                    <label for="depositIdDeposit" class="text-sm font-medium text-gray-700 dark:text-gray-200">
                        Almoxarifado
                    </label>

                    <p-select
                        inputId="depositIdDeposit"
                        name="depositIdDeposit"
                        [(ngModel)]="stockist.depositIdDeposit"
                        [options]="deposits"
                        optionLabel="depositName"
                        optionValue="idDeposit"
                        placeholder="Selecione o almoxarifado"
                        [filter]="true"
                        filterBy="depositName,depositCity,depositState"
                        appendTo="body"
                        styleClass="w-full">
                        <ng-template let-deposit pTemplate="item">
                            <div class="flex flex-col py-1">
                                <span class="font-medium">{{ deposit.depositName }}</span>
                                <small class="text-gray-500">
                                    {{ deposit.depositCity }} - {{ deposit.depositState }}
                                </small>
                            </div>
                        </ng-template>
                    </p-select>

                    <small *ngIf="!stockist.depositIdDeposit && formSubmitted" class="text-red-600 dark:text-red-400">
                        Selecione um almoxarifado.
                    </small>
                </div>
            </div>

            <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div class="rounded-xl bg-neutral-50 dark:bg-neutral-950/60 border border-neutral-200 dark:border-neutral-800 p-4">
                    <p class="text-xs uppercase tracking-wide text-gray-500 dark:text-gray-400 mb-2">
                        Preview do usuário
                    </p>
                    <p class="font-medium text-gray-900 dark:text-white">
                        {{ getUserLabel(stockist.userIdUser) || 'Nenhum usuário selecionado' }}
                    </p>
                </div>

                <div class="rounded-xl bg-neutral-50 dark:bg-neutral-950/60 border border-neutral-200 dark:border-neutral-800 p-4">
                    <p class="text-xs uppercase tracking-wide text-gray-500 dark:text-gray-400 mb-2">
                        Preview do almoxarifado
                    </p>
                    <p class="font-medium text-gray-900 dark:text-white">
                        {{ getDepositLabel(stockist.depositIdDeposit) || 'Nenhum almoxarifado selecionado' }}
                    </p>
                </div>
            </div>

            <div class="flex flex-col-reverse sm:flex-row sm:justify-end gap-3 pt-2 border-t border-neutral-200 dark:border-neutral-800">
                <button
                    type="button"
                    class="btn btn-ghost"
                    (click)="setOpen(false)">
                    Cancelar
                </button>

                <button
                    type="submit"
                    class="btn btn-primary"
                    [disabled]="saving">
                    <i class="pi pi-save"></i>
                    {{ stockist.stockistId ? 'Atualizar vínculo' : 'Salvar vínculo' }}
                </button>
            </div>
        </form>
    </div>

    <div
        *ngIf="!loading"
        class="rounded-2xl border border-neutral-200 dark:border-neutral-800 bg-white dark:bg-neutral-900 shadow-sm overflow-hidden">
        <div class="flex flex-col gap-2 md:flex-row md:items-center md:justify-between px-5 py-4 border-b border-neutral-200 dark:border-neutral-800">
            <div>
                <h3 class="font-semibold text-gray-900 dark:text-white">Vínculos cadastrados</h3>
                <p class="text-sm text-gray-500 dark:text-gray-400">
                    Lista de usuários que já atuam como estoquistas.
                </p>
            </div>

            <span
                *ngIf="isFallbackData"
                class="inline-flex items-center gap-2 rounded-full border border-amber-300 bg-amber-50 px-3 py-1 text-xs font-medium text-amber-700 dark:border-amber-900 dark:bg-amber-950/60 dark:text-amber-300">
                <i class="pi pi-info-circle"></i>
                Dados carregados pelo endpoint legado
            </span>
        </div>

        <div *ngIf="stockists.length === 0" class="px-5 py-12 text-center">
            <i class="pi pi-users text-4xl text-gray-300 dark:text-gray-700"></i>
            <h4 class="mt-4 text-lg font-semibold text-gray-900 dark:text-white">Nenhum estoquista cadastrado</h4>
            <p class="mt-2 text-sm text-gray-500 dark:text-gray-400">
                Crie o primeiro vínculo para liberar fluxos que dependem de estoquistas no sistema.
            </p>
        </div>

        <div *ngIf="stockists.length > 0" class="hidden md:block overflow-x-auto">
            <table class="table w-full">
                <thead>
                <tr>
                    <th>Usuário</th>
                    <th>Perfis</th>
                    <th>Almoxarifado</th>
                    <th>Contato</th>
                    <th class="text-right">Ações</th>
                </tr>
                </thead>
                <tbody>
                    <tr *ngFor="let item of stockists" class="hover:bg-gray-50 dark:hover:bg-neutral-800/70">
                        <td>
                            <div class="flex flex-col">
                                <span class="font-medium text-gray-900 dark:text-white">{{ item.userName }}</span>
                                <small class="text-gray-500 dark:text-gray-400">
                                    {{ item.userEmail || item.userIdUser }}
                                </small>
                            </div>
                        </td>

                        <td>
                            <div class="flex flex-wrap gap-2">
                                <p-tag
                                    *ngFor="let role of item.userRoles"
                                    [severity]="getSeverity([role])"
                                    [value]="role">
                                </p-tag>

                                <span *ngIf="item.userRoles.length === 0" class="text-sm text-gray-400">
                                    Não informado
                                </span>
                            </div>
                        </td>

                        <td>
                            <div class="flex flex-col">
                                <span class="font-medium text-gray-900 dark:text-white">{{ item.depositName }}</span>
                                <small class="text-gray-500 dark:text-gray-400">
                                    {{ item.depositRegion || item.depositAddress || 'Sem complemento cadastrado' }}
                                </small>
                            </div>
                        </td>

                        <td class="text-sm text-gray-600 dark:text-gray-300">
                            {{ item.depositPhone || 'Telefone não informado' }}
                        </td>

                        <td>
                            <div class="flex items-center justify-end gap-2">
                                <button
                                    type="button"
                                    class="btn btn-ghost btn-sm"
                                    (click)="editStockist(item)">
                                    <i class="pi pi-pencil"></i>
                                </button>

                                <button
                                    type="button"
                                    class="btn btn-ghost btn-sm text-red-600 dark:text-red-400"
                                    [disabled]="!item.stockistId"
                                    (click)="confirmDelete(item)">
                                    <i class="pi pi-trash"></i>
                                </button>
                            </div>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>

        <div *ngIf="stockists.length > 0" class="md:hidden flex flex-col gap-3 p-4">
            <div
                *ngFor="let item of stockists"
                class="rounded-2xl border border-neutral-200 dark:border-neutral-800 bg-neutral-50/80 dark:bg-neutral-950/40 p-4">
                <div class="flex items-start justify-between gap-3">
                    <div>
                        <h4 class="font-semibold text-gray-900 dark:text-white">{{ item.userName }}</h4>
                        <p class="text-sm text-gray-500 dark:text-gray-400">{{ item.userEmail || item.userIdUser }}</p>
                    </div>

                    <div class="flex items-center gap-1">
                        <button
                            type="button"
                            class="btn btn-ghost btn-xs"
                            (click)="editStockist(item)">
                            <i class="pi pi-pencil"></i>
                        </button>

                        <button
                            type="button"
                            class="btn btn-ghost btn-xs text-red-600 dark:text-red-400"
                            [disabled]="!item.stockistId"
                            (click)="confirmDelete(item)">
                            <i class="pi pi-trash"></i>
                        </button>
                    </div>
                </div>

                <div class="flex flex-wrap gap-2 mt-3">
                    <p-tag
                        *ngFor="let role of item.userRoles"
                        [severity]="getSeverity([role])"
                        [value]="role">
                    </p-tag>

                    <span *ngIf="item.userRoles.length === 0" class="text-sm text-gray-400">
                        Perfil não informado
                    </span>
                </div>

                <div class="mt-4 space-y-2 text-sm text-gray-600 dark:text-gray-300">
                    <p><span class="font-medium">Almoxarifado:</span> {{ item.depositName }}</p>
                    <p><span class="font-medium">Local:</span> {{ item.depositRegion || item.depositAddress || 'Sem complemento cadastrado' }}</p>
                    <p><span class="font-medium">Contato:</span> {{ item.depositPhone || 'Telefone não informado' }}</p>
                </div>
            </div>
        </div>
    </div>

    <app-modal [modalOpen]="showConfirmation" [confirmation]="true" (modalClose)="showConfirmation = false">
        <div class="text-center">
            <h3 class="mb-3 text-lg font-semibold text-gray-900 dark:text-white">Remover vínculo?</h3>
            <p class="mb-6 text-sm text-gray-500 dark:text-gray-400">
                Essa ação remove o estoquista do almoxarifado selecionado.
            </p>

            <div class="flex justify-center gap-3">
                <app-button
                    title="Cancelar"
                    classButton="btn btn-outline"
                    (click)="showConfirmation = false">
                </app-button>

                <app-button
                    title="Excluir"
                    classButton="btn btn-error"
                    (click)="deleteStockist()">
                </app-button>
            </div>
        </div>
    </app-modal>
</div>
