// angular-app/src/app/manage/account/account.component.ts
import {Component} from '@angular/core';
import {AlertMessageComponent} from "../../shared/components/alert-message/alert-message.component";
import {ButtonComponent} from "../../shared/components/button/button.component";
import {FormsModule, NgForm} from "@angular/forms";
import {ModalComponent} from "../../shared/components/modal/modal.component";
import {NgForOf, NgIf} from "@angular/common";
import {TableComponent} from "../../shared/components/table/table.component";
import {Router} from '@angular/router';
import {UserService} from '../user/user-service.service';
import {UtilsService} from '../../core/service/utils.service';
import {AuthService} from '../../core/auth/auth.service';
import {Title} from '@angular/platform-browser';
import {catchError, tap, throwError} from 'rxjs';
import {SharedState} from '../../core/service/shared-state';
import {Chip} from 'primeng/chip';
import {Dialog} from 'primeng/dialog';
import {Password} from 'primeng/password';
import {Message} from 'primeng/message';
import {Divider} from 'primeng/divider';
import {Button} from 'primeng/button';

@Component({
    selector: 'app-account',
    standalone: true,
    imports: [
        AlertMessageComponent,
        ButtonComponent,
        FormsModule,
        ModalComponent,
        NgForOf,
        NgIf,
        Chip,
        Dialog,
        Password,
        Message,
        Divider,
        Button
    ],
    templateUrl: './account.component.html',
    styleUrl: './account.component.scss'
})
export class AccountComponent {

    user: {
        userId: string,
        username: string,
        name: string,
        lastname: string,
        email: string,
        year: string;
        month: string;
        day: string;
        role: string[],
        status: boolean
        sel: boolean
    } = {
        userId: '',
        username: '',
        name: '',
        lastname: '',
        email: '',
        year: '',
        month: '',
        day: '',
        role: [],
        status: false,
        sel: false
    };

    password: {
        oldPassword: string,
        password: string,
        passwordConfirm: string,
    } = {
        oldPassword: '',
        password: '',
        passwordConfirm: '',
    }

    errorPassword: string = ''
    showPassword: boolean[] = [false, false, false];

    constructor(protected router: Router, private userService: UserService, protected utils: UtilsService,
                protected authService: AuthService, private titleService: Title) {

        SharedState.setCurrentPath(['Configurações','Minha Conta']);
        this.titleService.setTitle("Configurações de Acesso");
        const uuid = authService.getUser().uuid;

        this.userService.getUser(uuid).subscribe(
            user => {
                this.user = user;
            });

    }


    months: {
        number: string,
        name: string,
    }[] = [
        {number: '1', name: "Janeiro"},
        {number: '2', name: "Fevereiro"},
        {number: '3', name: "Março"},
        {number: '4', name: "Abril"},
        {number: '5', name: "Maio"},
        {number: '6', name: "Junho"},
        {number: '7', name: "Julho"},
        {number: '8', name: "Agosto"},
        {number: '9', name: "Setembro"},
        {number: '10', name: "Outubro"},
        {number: '11', name: "Novembro"},
        {number: '12', name: "Dezembro"},
    ];

    formSubmitted: boolean = false;
    serverMessage: string | null = null;
    alertType: string | null = null;
    loading: boolean = false;
    openConfirmationModal: boolean = false;
    usernamePattern: string = '^[a-zA-Z0-9._-]{3,20}$';
    emailPattern: string = '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$';
    private email: string = "";

    getMonth(monthNumber: string) {
        return this.months.find(m => m.number === monthNumber);
    }

    getMaxDay(month: string, year: string): number {
        const daysInMonth: Record<number, number> = {
            1: 31, // Janeiro
            2: this.isLeapYear(year) ? 29 : 28, // Fevereiro
            3: 31, // Março
            4: 30, // Abril
            5: 31, // Maio
            6: 30, // Junho
            7: 31, // Julho
            8: 31, // Agosto
            9: 30, // Setembro
            10: 31, // Outubro
            11: 30, // Novembro
            12: 31, // Dezembro
        };
        return daysInMonth[parseInt(month, 10)] || 31; // Valor padrão para meses inválidos
    }

    isLeapYear(strYear: string): boolean {
        const year = parseInt(strYear, 10);
        return (year % 4 === 0 && year % 100 !== 0) || year % 400 === 0;
    }


    submitUser(passForm: NgForm) {
        if (passForm.invalid) {
            return;
        }

        if (this.password.password !== this.password.passwordConfirm) {
            this.errorPassword = "As senhas não conferem, tente novamente.";
            return;
        }

        this.userService.setPassword(this.user.userId, this.password).pipe(
            tap(
                response => {
                    this.alertType = 'alert-success';
                    this.serverMessage = response.message;
                    this.openConfirmationModal = false;
                }
            ),
            catchError(err => {
                this.alertType = "alert-error";
                // @ts-ignore
                this.serverMessage(err.error.message);
                throw err;
            })
        ).subscribe();

    }

    togglePasswordVisibility(number: number) {
        this.showPassword[number] = !this.showPassword[number];
    }

}

<div class="flex flex-col w-full max-w-5xl mx-auto px-6 py-6 gap-8">
  <div class="flex items-center gap-4 border-b border-neutral-200 dark:border-neutral-800 pb-6">
    <div
      class="w-14 h-14 rounded-full bg-neutral-200 dark:bg-neutral-700 flex items-center justify-center text-xl font-bold">
      {{ user.username.charAt(0).toUpperCase() }}
    </div>

    <div class="flex flex-col min-w-0">
      <h2 class="font-semibold text-lg truncate">{{ user.username }}</h2>
      <p class="text-sm text-neutral-500 truncate">{{ user.email }}</p>
    </div>
  </div>

  <section class="flex flex-col gap-4">
    <div>
      <h3 class="font-semibold text-base">Conta</h3>
      <p class="text-sm text-neutral-500">
        Informações básicas do seu perfil.
      </p>
    </div>

    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">

      <div
        class="rounded-lg border border-neutral-200 dark:border-neutral-800 p-4 hover:bg-neutral-50 dark:hover:bg-neutral-900 transition">
        <div class="flex items-center justify-between mb-1">
          <span class="font-medium">Nome</span>
          <span class="material-icons text-neutral-400 text-base">person</span>
        </div>
        <p class="text-sm text-neutral-600 dark:text-neutral-400">
          {{ user.name }} {{ user.lastname }}
        </p>
      </div>


      <div class="rounded-lg border border-neutral-200 dark:border-neutral-800 p-4">
        <div class="flex items-center justify-between mb-2">
          <span class="font-medium">Funções no Sistema</span>
          <span class="material-icons text-neutral-400 text-base">psychology</span>
        </div>

        <div class="flex flex-wrap gap-2 select-none">
          <p-chip
            *ngFor="let role of user.role"
            [label]="role"
            class="text-xs">
          </p-chip>
        </div>

      </div>
    </div>
  </section>
  <section class="flex flex-col gap-4">
    <div>
      <h3 class="font-semibold text-base">Segurança</h3>
      <p class="text-sm text-neutral-500">
        Gerencie credenciais e informações sensíveis.
      </p>
    </div>

    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">

      <div class="rounded-lg border border-neutral-200 dark:border-neutral-800 p-4">
        <div class="flex items-center justify-between mb-1">
          <span class="font-medium">Aniversário</span>
          <span class="material-icons text-neutral-400 text-base">cake</span>
        </div>
        <p class="text-sm text-neutral-600 dark:text-neutral-400">
          {{ user.day }} de {{ getMonth(user.month.toString())?.name }} de {{ user.year }}
        </p>
      </div>
      <button
        (click)="user.userId !== '' ? openConfirmationModal = true : (serverMessage = 'Usuário não encontrado')"
        class="flex items-center justify-between rounded-lg border border-red-300 dark:border-red-700 p-4 text-red-600 hover:bg-red-50 dark:hover:bg-red-900/20 transition">

        <span class="font-medium">Alterar senha</span>
        <span class="material-icons text-base">security</span>
      </button>
    </div>
  </section>

  <p-dialog
    header="Alterar senha"
    [(visible)]="openConfirmationModal"
    [modal]="true"
    [closable]="false"
    [style]="{ width: '420px' }"
    styleClass="rounded-lg">

    <form #passForm="ngForm" (ngSubmit)="submitUser(passForm)" class="flex flex-col gap-4">

      <!-- Senha atual -->
      <div class="flex flex-col gap-1">
        <label class="text-sm font-medium">Senha atual</label>

        <p-password
          name="oldPassword"
          [(ngModel)]="password.oldPassword"
          [feedback]="false"
          [toggleMask]="true"
          required
          placeholder="Digite sua senha atual"
          inputStyleClass="w-full">
        </p-password>

        <small *ngIf="passForm.submitted && !password.oldPassword"
               class="text-red-500">
          Campo obrigatório
        </small>
      </div>

      <!-- Nova senha -->
      <div class="flex flex-col gap-1">
        <label class="text-sm font-medium">Nova senha</label>

        <p-password
          name="password"
          [(ngModel)]="password.password"
          [toggleMask]="true"
          [feedback]="true"
          required
          minlength="8"
          placeholder="Digite sua nova senha"
          inputStyleClass="w-full">
        </p-password>

        <small *ngIf="passForm.submitted && (password.password?.length ?? 0) < 8"
               class="text-orange-500">
          Mínimo de 8 caracteres
        </small>
      </div>

      <!-- Confirmar senha -->
      <div class="flex flex-col gap-1">
        <label class="text-sm font-medium">Confirmar nova senha</label>

        <p-password
          name="passwordConfirm"
          [(ngModel)]="password.passwordConfirm"
          [toggleMask]="true"
          [feedback]="false"
          required
          placeholder="Confirme sua nova senha"
          inputStyleClass="w-full">
        </p-password>

        <small *ngIf="passForm.submitted && password.passwordConfirm !== password.password"
               class="text-red-500">
          As senhas não coincidem
        </small>
      </div>

      <!-- Erro backend -->
      <p-message
        *ngIf="errorPassword"
        severity="error"
        [text]="errorPassword">
      </p-message>

      <p-divider></p-divider>

      <!-- Ações -->
      <div class="flex justify-end gap-2">
        <p-button
          label="Cancelar"
          severity="secondary"
          [outlined]="true"
          type="button"
          (onClick)="openConfirmationModal = false; loading = false">
        </p-button>

        <p-button
          label="Confirmar"
          type="submit"
          [loading]="loading"
          severity="primary">
        </p-button>
      </div>

    </form>

  </p-dialog>


</div>

// react-app/src/features/manage/pages/Account.tsx
import { useState, useEffect } from 'react';
import { useMutation } from '@tanstack/react-query';
import { useAppStore } from '@/store/use-app-store';
import { useAuthStore } from '@/core/auth/useAuthStore';
import { useNotify } from '@/shared/hooks/use-notify';
import { Modal, ModalBody, ModalFooter, ModalHeader } from '@/shared/ui/modal';
import { manageApi } from '@/features/manage/api/manageApi';
import { passwordChangeSchema } from '@/features/manage/validations/userSchema';

export default function Account() {
  const { setPageContext } = useAppStore();
  const { user } = useAuthStore();
  const { notify } = useNotify();
  const changePasswordMutation = useMutation({
    mutationFn: ({ currentPassword, newPassword }: { currentPassword: string; newPassword: string }) =>
      manageApi.changePassword(currentPassword, newPassword),
  });

  const [pwModal, setPwModal] = useState(false);
  const [current, setCurrent] = useState('');
  const [next, setNext] = useState('');
  const [confirm, setConfirm] = useState('');
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    setPageContext(['Configurações', 'Minha Conta'], 'Minha Conta');
  }, [setPageContext]);

  const handleChangePassword = async () => {
    const validation = passwordChangeSchema.safeParse({
      currentPassword: current,
      nextPassword: next,
      confirmPassword: confirm,
    });
    if (!validation.success) {
      notify(validation.error.issues[0]?.message ?? 'Dados inválidos.', 'warn');
      return;
    }
    setSaving(true);
    try {
      await changePasswordMutation.mutateAsync({ currentPassword: current, newPassword: next });
      notify('Senha alterada com sucesso.', 'success');
      setPwModal(false);
      setCurrent(''); setNext(''); setConfirm('');
    } catch (err: unknown) {
      const msg = (err as { response?: { data?: { message?: string } } })?.response?.data?.message ?? 'Não foi possível alterar a senha.';
      notify(msg, 'error');
    } finally {
      setSaving(false);
    }
  };

  const inputClass = 'w-full rounded-xl border border-slate-200 dark:border-zinc-700 bg-white dark:bg-zinc-900 px-3 py-2.5 text-sm text-slate-800 dark:text-zinc-100 placeholder:text-slate-400 outline-none focus:border-indigo-400 transition-colors';

  const infoCard = (label: string, value: string | undefined) => (
    <div key={label} className="rounded-xl border border-slate-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 p-4">
      <p className="text-xs font-medium text-slate-500 dark:text-zinc-400 mb-1">{label}</p>
      <p className="text-sm font-semibold text-slate-800 dark:text-zinc-100 truncate">{value || '—'}</p>
    </div>
  );

  return (
    <section className="p-4 md:p-6 max-w-3xl mx-auto space-y-6">
      {/* Profile header */}
      <div className="flex items-center gap-4 pb-6 border-b border-slate-200 dark:border-zinc-800">
        <div className="w-14 h-14 rounded-full bg-gradient-to-br from-indigo-500 to-purple-600 flex items-center justify-center text-xl font-bold text-white shadow-sm">
          {user?.fullName?.charAt(0)?.toUpperCase() ?? 'U'}
        </div>
        <div className="min-w-0">
          <h2 className="text-lg font-semibold text-slate-800 dark:text-zinc-100 truncate">{user?.username}</h2>
          <p className="text-sm text-slate-500 dark:text-zinc-400 truncate">{user?.email}</p>
        </div>
      </div>

      {/* Account info */}
      <div>
        <h3 className="text-base font-semibold text-slate-800 dark:text-zinc-100 mb-1">Conta</h3>
        <p className="text-sm text-slate-500 dark:text-zinc-400 mb-4">Informações básicas do seu perfil.</p>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
          {infoCard('Nome completo', user?.fullName)}
          {infoCard('Usuário', user?.username)}
          {infoCard('E-mail', user?.email)}
          {infoCard('Tenant', user?.tenant)}
        </div>

        {/* Roles */}
        {user?.roles && user.roles.length > 0 && (
          <div className="mt-3 rounded-xl border border-slate-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 p-4">
            <p className="text-xs font-medium text-slate-500 dark:text-zinc-400 mb-2">Funções no sistema</p>
            <div className="flex flex-wrap gap-2">
              {user.roles.map(role => (
                <span key={role}
                  className="inline-flex rounded-full bg-indigo-50 dark:bg-indigo-900/20 px-3 py-1 text-xs font-semibold text-indigo-700 dark:text-indigo-300">
                  {role}
                </span>
              ))}
            </div>
          </div>
        )}
      </div>

      {/* Security */}
      <div>
        <h3 className="text-base font-semibold text-slate-800 dark:text-zinc-100 mb-1">Segurança</h3>
        <p className="text-sm text-slate-500 dark:text-zinc-400 mb-4">Gerencie credenciais e informações sensíveis.</p>
        <div className="rounded-xl border border-slate-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 p-4 flex items-center justify-between">
          <div>
            <p className="text-sm font-medium text-slate-700 dark:text-zinc-200">Senha</p>
            <p className="text-xs text-slate-500 dark:text-zinc-400 mt-0.5">Altere sua senha de acesso</p>
          </div>
          <button type="button" onClick={() => setPwModal(true)}
            className="rounded-xl border border-slate-200 dark:border-zinc-700 px-4 py-2 text-sm font-semibold text-slate-700 dark:text-zinc-200 hover:bg-slate-50 dark:hover:bg-zinc-800 transition-colors">
            Alterar senha
          </button>
        </div>
      </div>

      {/* Change password modal */}
      <Modal open={pwModal} onClose={() => { setPwModal(false); setCurrent(''); setNext(''); setConfirm(''); }} confirmation>
        <ModalHeader title="Alterar Senha" onClose={() => setPwModal(false)} />
        <ModalBody className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-slate-700 dark:text-zinc-200 mb-1">Senha atual</label>
            <input type="password" value={current} onChange={e => setCurrent(e.target.value)} autoFocus
              placeholder="Digite sua senha atual" className={inputClass} />
          </div>
          <div>
            <label className="block text-sm font-medium text-slate-700 dark:text-zinc-200 mb-1">Nova senha</label>
            <input type="password" value={next} onChange={e => setNext(e.target.value)}
              placeholder="Mínimo 8 caracteres" className={inputClass} />
          </div>
          <div>
            <label className="block text-sm font-medium text-slate-700 dark:text-zinc-200 mb-1">Confirmar nova senha</label>
            <input type="password" value={confirm} onChange={e => setConfirm(e.target.value)}
              placeholder="Repita a nova senha" className={inputClass} />
          </div>
          {next && confirm && next !== confirm && (
            <p className="text-xs text-red-500">As senhas não conferem.</p>
          )}
        </ModalBody>
        <ModalFooter>
          <button type="button" onClick={() => { setPwModal(false); setCurrent(''); setNext(''); setConfirm(''); }}
            className="rounded-xl border border-slate-200 dark:border-zinc-700 px-4 py-2 text-sm font-semibold text-slate-600 dark:text-zinc-400 hover:bg-slate-50 dark:hover:bg-zinc-800 transition-colors">
            Cancelar
          </button>
          <button type="button" disabled={!current || !next || !confirm || saving}
            onClick={() => void handleChangePassword()}
            className="rounded-xl bg-indigo-600 px-4 py-2 text-sm font-semibold text-white hover:bg-indigo-500 disabled:opacity-50 transition-colors">
            {saving && <i className="pi pi-spin pi-spinner mr-1.5 text-xs" />}
            Salvar
          </button>
        </ModalFooter>
      </Modal>
    </section>
  );
}
