// react-app/src/features/manage/pages/Settings.tsx
import { useEffect, useMemo, useState } from 'react';
import { Outlet, useNavigate, useOutlet } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';

import { useAppStore } from '@/store/use-app-store';
import { useNotify } from '@/shared/hooks/use-notify';
import { useNotificationStore } from '@/core/notifications/useNotificationStore';
import { useAuthStore } from '@/core/auth/useAuthStore';
import { useUsers } from '@/features/manage/hooks/useUsers';
import { useTeams } from '@/features/manage/hooks/useTeams';
import type { ManagedUser } from '@/features/manage/types/manageTypes';
import { contractsApi } from '@/features/contract/api/contractsApi';
import { contractKeys } from '@/features/contract/api/contractQueryKeys';
import { useCatalogue } from '@/features/stock/hooks/use-catalogue';
import { useDeposits } from '@/features/stock/hooks/use-deposits';
import { useStockists } from '@/features/stock/hooks/use-stockists';

interface OnboardingStep {
  id: string;
  title: string;
  description: string;
  helper: string;
  icon: string;
  route: string;
  ctaLabel: string;
  done: boolean;
  metric: string;
  blockers: string[];
  externalUrl?: boolean;
  disabled: boolean;
}

const EMBEDDED_ROUTE_MAP: Record<string, string> = {
  '/configuracoes/usuarios': 'usuarios',
  '/configuracoes/equipes': 'equipes',
  '/configuracoes/estoquistas': 'estoquistas',
  '/estoque/almoxarifados': 'almoxarifados',
  '/estoque/caminhoes': 'caminhoes',
  '/estoque/cadastrar-material': 'cadastrar-material',
  '/contratos/itens-contratuais/cadastro': 'itens-contratuais',
  '/contratos/criar': 'criar-contrato',
};

function normalizeRoleTokens(user: ManagedUser): string[] {
  return (user.role ?? []).flatMap((roleItem) => {
    const values = [
      roleItem?.roleId,
      roleItem?.label,
      (roleItem as unknown as { roleName?: string })?.roleName,
    ].filter(Boolean) as string[];
    return values.map((value) => String(value).toUpperCase());
  });
}

export default function Settings() {
  const navigate = useNavigate();
  const outlet = useOutlet();
  const { setPageContext, setOnboarding } = useAppStore();
  const { notify } = useNotify();
  const { user } = useAuthStore();
  const { status: notificationStatus, initialize: initializeNotifications, requestPermission } = useNotificationStore();

  const [activeStepIndex, setActiveStepIndex] = useState(0);
  const [fieldActivationDone, setFieldActivationDone] = useState(localStorage.getItem('isFinishedTeamInstruction') === 'true');
  const [embeddedExternalUrl, setEmbeddedExternalUrl] = useState<string | null>(null);
  useEffect(() => {
    setPageContext(['Primeiros passos'], 'Primeiros passos');
    initializeNotifications();
  }, [initializeNotifications, setPageContext]);

  const contractFilters = useMemo(() => ({
    contractor: null,
    startDate: new Date(new Date().setMonth(new Date().getMonth() - 6)),
    endDate: new Date(),
    status: null,
  }), []);

  const { data: referenceContractItems = [], isLoading: loadingReferenceItems } = useQuery({
    queryKey: contractKeys.referenceItems(),
    queryFn: contractsApi.getContractReferenceItems,
  });
  const { data: contracts = [], isLoading: loadingContracts } = useQuery({
    queryKey: contractKeys.list(contractFilters),
    queryFn: () => contractsApi.getAllContracts(contractFilters),
  });
  const { data: users = [], isLoading: loadingUsers } = useUsers();
  const { data: teams = [], isLoading: loadingTeams } = useTeams();

  const { data: stockists = [], isLoading: loadingStockists } = useStockists();
  const { data: deposits = [], isLoading: loadingDeposits } = useDeposits();
  const { data: materials = [], isLoading: loadingMaterials } = useCatalogue();

  const totals = useMemo(() => {
    const usersList = users as ManagedUser[];
    const adminUsers = usersList.filter((user) => normalizeRoleTokens(user).some((token) => token.includes('ADMIN'))).length;
    const operationalUsers = usersList.filter((user) => {
      const tokens = normalizeRoleTokens(user);
      return tokens.includes('ELETRICISTA') || tokens.includes('MOTORISTA');
    }).length;
    const stockistUsers = usersList.filter((user) => {
      const tokens = normalizeRoleTokens(user);
      return tokens.includes('ESTOQUISTA') || tokens.includes('ESTOQUISTA_CHEFE');
    }).length;

    return {
      referenceContractItems: referenceContractItems.length,
      totalContracts: contracts.length,
      totalUsers: usersList.length,
      adminUsers,
      operationalUsers,
      stockistUsers,
      teamsCount: teams.length,
      stockistsCount: stockists.length,
      depositsCount: (deposits as Array<{ isTruck: boolean }>).filter((deposit) => !deposit.isTruck).length,
      trucksCount: (deposits as Array<{ isTruck: boolean }>).filter((deposit) => deposit.isTruck).length,
      materialsCount: materials.length,
    };
  }, [contracts.length, deposits, materials.length, referenceContractItems.length, stockists.length, teams.length, users]);

  const onboardingSteps = useMemo<OnboardingStep[]>(() => {
    return [
      {
        id: 'users',
        title: 'Estruture os acessos',
        description: 'Cadastre perfis administrativos e operacionais para destravar os vínculos das próximas etapas.',
        helper: 'Sua operação precisa de estoquistas, eletricistas e motoristas previamente cadastrados.',
        icon: 'pi pi-users',
        route: '/configuracoes/usuarios',
        ctaLabel: totals.totalUsers === 0 ? 'Cadastrar usuários...' : 'Revisar usuários...',
        done: totals.totalUsers > 0 && totals.operationalUsers > 0 && totals.stockistUsers > 0,
        metric: `Usuários: ${totals.totalUsers}`,
        blockers: [
          totals.totalUsers === 0 ? 'Nenhum usuário cadastrado.' : '',
          totals.operationalUsers === 0 ? 'Cadastrar eletricistas e motoristas.' : '',
          totals.stockistUsers === 0 ? 'Cadastrar estoquistas.' : '',
        ].filter(Boolean),
        disabled: false,
      },
      {
        id: 'teams',
        title: 'Monte a equipe operacional',
        description: 'Crie equipes com colaboradores, região de atuação e vínculo de caminhão para liberar a operação em campo.',
        helper: 'Essa etapa destrava ordens de serviço e também reflete nos caminhões do estoque.',
        icon: 'pi pi-user-edit',
        route: '/configuracoes/equipes',
        ctaLabel: totals.teamsCount === 0 ? 'Cadastrar equipes...' : 'Gerenciar equipes...',
        done: totals.teamsCount > 0,
        metric: `Equipes: ${totals.teamsCount}`,
        blockers: [
          totals.operationalUsers === 0 ? 'Voltar ao passo anterior e cadastrar usuários operacionais.' : '',
          totals.teamsCount === 0 ? 'Cadastrar as equipes operacionais.' : '',
        ].filter(Boolean),
        disabled: totals.operationalUsers === 0,
      },
      {
        id: 'field-activation',
        title: 'Coloque a equipe em campo',
        description: 'Garanta que a equipe operacional tenha acesso ao aplicativo e esteja pronta para iniciar as atividades em campo.',
        helper: totals.teamsCount === 0
          ? 'Crie uma equipe operacional antes de iniciar a operação.'
          : 'Peça para a equipe baixar o app, fazer login e seguir as instruções iniciais.',
        icon: 'pi pi-mobile',
        route: 'https://lumosip.com.br/como-usar/07-operation/01-android-app-admin/',
        externalUrl: true,
        ctaLabel: 'Ver instruções...',
        done: fieldActivationDone,
        metric: fieldActivationDone ? 'Equipe pronta para operação' : 'Ativação pendente',
        blockers: [
          totals.operationalUsers === 0 ? 'Voltar ao passo 1 e cadastrar usuários operacionais.' : '',
          totals.teamsCount === 0 ? 'Voltar ao passo anterior e cadastrar as equipes operacionais.' : '',
          !fieldActivationDone ? 'Orientar a equipe a baixar o aplicativo e acessar o sistema.' : '',
        ].filter(Boolean),
        disabled: totals.operationalUsers === 0 || totals.teamsCount === 0,
      },
      {
        id: 'deposits',
        title: 'Prepare a base logística',
        description: 'Configure almoxarifados e caminhões para garantir origem, destino e rastreabilidade do material.',
        helper: 'Movimentação de estoque depende de pelo menos um almoxarifado e um caminhão.',
        icon: 'pi pi-truck',
        route: totals.depositsCount === 0 ? '/estoque/almoxarifados' : '/estoque/caminhoes',
        ctaLabel: totals.depositsCount === 0 ? 'Cadastrar almoxarifados...' : totals.trucksCount === 0 ? 'Cadastrar caminhões...' : 'Revisar logística...',
        done: totals.depositsCount > 0 && totals.trucksCount > 0,
        metric: `Almoxarifados: ${totals.depositsCount} • Caminhões: ${totals.trucksCount}`,
        blockers: [
          totals.depositsCount === 0 ? 'Cadastrar almoxarifados fixos.' : '',
          totals.trucksCount === 0 ? 'Cadastrar almoxarifados móveis/caminhões.' : '',
        ].filter(Boolean),
        disabled: false,
      },
      {
        id: 'stockists',
        title: 'Defina os estoquistas',
        description: 'Associe responsáveis pelo estoque para liberar o gerenciamento de reservas e expedições.',
        helper: 'Essa etapa é obrigatória para criação e acompanhamento de ordens com movimentação de material.',
        icon: 'pi pi-briefcase',
        route: '/configuracoes/estoquistas',
        ctaLabel: totals.stockistsCount === 0 ? 'Cadastrar estoquistas...' : 'Gerenciar estoquistas...',
        done: totals.stockistsCount > 0,
        metric: `Estoquistas: ${totals.stockistsCount}`,
        blockers: [
          totals.depositsCount === 0 ? 'Voltar ao passo anterior e cadastrar os almoxarifados.' : '',
          totals.stockistsCount === 0 ? 'Cadastrar os estoquistas.' : '',
        ].filter(Boolean),
        disabled: totals.depositsCount === 0,
      },
      {
        id: 'materials',
        title: 'Abasteça o catálogo de materiais',
        description: 'Cadastre materiais para que estoque, contratos e execuções consigam operar sem bloqueios.',
        helper: 'Sem catálogo não há movimentação, separação e apontamento de itens.',
        icon: 'pi pi-box',
        route: '/estoque/cadastrar-material',
        ctaLabel: totals.materialsCount === 0 ? 'Cadastrar materiais...' : 'Ver catálogo...',
        done: totals.materialsCount > 0,
        metric: `Materiais: ${totals.materialsCount}`,
        blockers: [totals.materialsCount === 0 ? 'Cadastrar o catálogo de materiais.' : ''].filter(Boolean),
        disabled: false,
      },
      {
        id: 'reference-items',
        title: 'Cadastre os itens contratuais',
        description: 'Crie os itens contratuais que serão usados como base para vincular contratos nas próximas etapas.',
        helper: 'Sem itens contratuais cadastrados, não é possível avançar na configuração de contratos.',
        icon: 'pi pi-file-edit',
        route: '/contratos/itens-contratuais/cadastro',
        ctaLabel: totals.referenceContractItems === 0 ? 'Cadastrar itens contratuais...' : 'Gerenciar itens...',
        done: totals.referenceContractItems > 0,
        metric: `Itens contratuais: ${totals.referenceContractItems}`,
        blockers: [totals.referenceContractItems === 0 ? 'Cadastrar o catálogo de itens contratuais.' : ''].filter(Boolean),
        disabled: false,
      },
      {
        id: 'contracts',
        title: 'Cadastre os contratos',
        description: 'Crie contratos para organizar e vincular seus itens contratuais e iniciar a operação.',
        helper: totals.referenceContractItems === 0
          ? 'Antes de cadastrar contratos, você precisa criar pelo menos um item contratual.'
          : 'Com os itens contratuais cadastrados, você já pode criar seus contratos.',
        icon: 'pi pi-briefcase',
        route: '/contratos/criar',
        ctaLabel: totals.totalContracts === 0 ? 'Cadastrar contratos...' : 'Gerenciar contratos...',
        done: totals.totalContracts > 0,
        metric: `Contratos: ${totals.totalContracts}`,
        blockers: [
          totals.referenceContractItems === 0 ? 'Voltar ao passo anterior e cadastrar o catálogo de itens contratuais.' : '',
          totals.totalContracts === 0 ? 'Cadastrar os contratos.' : '',
        ].filter(Boolean),
        disabled: totals.referenceContractItems === 0,
      },
      {
        id: 'notifications',
        title: 'Ative as notificações',
        description: 'Para não perder nenhum alerta importante na sua operação.',
        helper: ['default', 'denied'].includes(notificationStatus) ? 'Notificações desativadas.' : 'Notificações ativadas.',
        icon: 'pi pi-bell',
        route: '/contratos/criar',
        ctaLabel: ['default', 'denied'].includes(notificationStatus) ? 'Ativar notificações...' : 'Gerar primeira ordem de serviço...',
        done: notificationStatus === 'granted',
        metric: '',
        blockers: [['default', 'denied'].includes(notificationStatus) ? 'Ativar as notificações do sistema.' : ''].filter(Boolean),
        disabled: false,
      },
    ];
  }, [fieldActivationDone, notificationStatus, totals]);

  useEffect(() => {
    const firstPending = onboardingSteps.findIndex((step) => !step.done);
    setActiveStepIndex(firstPending >= 0 ? firstPending : 0);
  }, [onboardingSteps]);

  const totalSteps = onboardingSteps.length;
  const completedSteps = onboardingSteps.filter((step) => step.done).length;
  const pendingSteps = onboardingSteps.filter((step) => !step.done);
  const activeStep = onboardingSteps[activeStepIndex];
  const isComplete = pendingSteps.length === 0;
  const hasPreviousStep = activeStepIndex > 0;
  const hasNextStep = activeStepIndex < totalSteps - 1;
  const completionPercent = totalSteps === 0 ? 0 : Math.round((completedSteps / totalSteps) * 100);
  const loading = loadingReferenceItems || loadingContracts || loadingUsers || loadingTeams || loadingStockists || loadingDeposits || loadingMaterials;

  const heroTitle = isComplete ? 'Tudo pronto para começar' : 'Configure o sistema e comece a usar';
  const heroSubtitle = isComplete
    ? 'Tudo pronto! Agora é só colocar sua equipe em campo e começar a usar o sistema.'
    : 'Vamos finalizar sua configuração inicial. Comece pelo próximo passo.';

  const embeddedViewActive = Boolean(outlet || embeddedExternalUrl);

  useEffect(() => {
    if (isComplete) {
      localStorage.setItem('onboarding', 'finished');
      setOnboarding(false);
      return;
    }

    localStorage.removeItem('onboarding');
    setOnboarding(true);
  }, [isComplete, setOnboarding]);

  const handleNavigateStep = async () => {
    if (!activeStep || (activeStep.disabled && !isComplete)) {
      return;
    }

    if (isComplete) {
      navigate('/');
      return;
    }

    if (activeStep.id === 'notifications' && ['default', 'denied'].includes(notificationStatus)) {
      if (typeof Notification === 'undefined') {
        notify('Este navegador não suporta notificações.', 'warn');
        return;
      }
      try {
        const permission = await requestPermission(user?.roles ?? []);
        if (permission === 'granted') {
          notify('Notificações ativadas com sucesso.', 'success');
        } else {
          notify('Permissão de notificações não concedida.', 'warn');
        }
      } catch {
        notify('Não foi possível solicitar permissão de notificações.', 'error');
      }
      return;
    }

    if (activeStep.externalUrl) {
      setEmbeddedExternalUrl(activeStep.route);
      localStorage.setItem('isFinishedTeamInstruction', 'true');
      setFieldActivationDone(true);
      navigate('/configuracoes/onboarding');
      return;
    }

    const embeddedChildPath = EMBEDDED_ROUTE_MAP[activeStep.route];
    if (embeddedChildPath) {
      navigate(`/configuracoes/onboarding/${embeddedChildPath}`);
      return;
    }

    navigate(activeStep.route);
  };

  const closeEmbeddedView = () => {
    setEmbeddedExternalUrl(null);
    navigate('/configuracoes/onboarding');
  };

  return (
    <>
      <div className="min-h-full px-3 py-3 text-slate-900 dark:text-slate-100 sm:px-4 sm:py-4 lg:px-8">
        <div className="mx-auto flex w-full max-w-7xl flex-col gap-4 sm:gap-6">
          <section className="rounded-3xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900 sm:p-5">
            <div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between">
              <div className="min-w-0 max-w-2xl">
                <p className="text-[11px] font-semibold uppercase tracking-[0.22em] text-cyan-700 dark:text-cyan-300 sm:text-xs">
                  Configuração inicial
                </p>
                <h1 className="mt-2 text-xl font-semibold tracking-tight sm:text-2xl lg:text-3xl">
                  {heroTitle}
                </h1>
                <p className="mt-2 text-sm leading-5 text-slate-600 dark:text-slate-300 sm:leading-6">
                  {heroSubtitle}
                </p>
              </div>
              <div className="w-full rounded-2xl bg-slate-50 px-4 py-3 text-sm font-medium text-slate-600 dark:bg-slate-800 dark:text-slate-200 md:w-auto">
                {completedSteps} de {totalSteps} etapas concluídas
              </div>
            </div>
            <div className="mt-4 h-2.5 overflow-hidden rounded-full bg-slate-200 dark:bg-slate-800 sm:mt-5 sm:h-3">
              <div className="h-full rounded-full bg-gradient-to-r from-blue-600 to-cyan-500 transition-all" style={{ width: `${completionPercent}%` }} />
            </div>
          </section>

          {loading ? (
            <div className="grid gap-4 lg:grid-cols-[300px_minmax(0,1fr)] xl:grid-cols-[440px_minmax(0,1fr)] lg:gap-5">
              <div className="order-2 rounded-3xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900 lg:order-1">
                <div className="space-y-3">
                  {Array.from({ length: 6 }).map((_, index) => (
                    <div key={index} className="h-20 animate-pulse rounded-2xl bg-slate-100 dark:bg-slate-800" />
                  ))}
                </div>
              </div>
              <div className="order-1 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900 lg:order-2">
                <div className="space-y-4">
                  <div className="h-5 w-1/3 animate-pulse rounded bg-slate-100 dark:bg-slate-800" />
                  <div className="h-8 w-2/3 animate-pulse rounded bg-slate-100 dark:bg-slate-800" />
                  <div className="h-24 animate-pulse rounded-2xl bg-slate-100 dark:bg-slate-800" />
                  <div className="h-24 animate-pulse rounded-2xl bg-slate-100 dark:bg-slate-800" />
                </div>
              </div>
            </div>
          ) : (
            <div className="grid gap-4 lg:grid-cols-[300px_minmax(0,1fr)] xl:grid-cols-[440px_minmax(0,1fr)] lg:gap-5">
              <aside className="order-2 rounded-3xl border border-slate-200 bg-white p-3 shadow-sm dark:border-slate-800 dark:bg-slate-900 sm:p-4 lg:order-1">
                <div className="mb-3 sm:mb-4">
                  <h2 className="text-sm font-semibold sm:text-base">Etapas</h2>
                  <p className="mt-1 text-xs text-slate-500 dark:text-slate-400 sm:text-sm">Acompanhe o onboarding em ordem.</p>
                </div>
                <div className="flex flex-col gap-2">
                  {onboardingSteps.map((step, index) => {
                    const isActive = index === activeStepIndex;
                    const isDone = step.done;
                    return (
                      <button
                        key={step.id}
                        type="button"
                        onClick={() => setActiveStepIndex(index)}
                        className={[
                          'w-full rounded-2xl border p-3 text-left transition',
                          isActive
                            ? 'border-cyan-300 bg-cyan-50/95 dark:border-cyan-600/60 dark:bg-cyan-900/30'
                            : isDone
                              ? 'border-transparent bg-emerald-50/70 dark:bg-emerald-900/20'
                              : 'border-transparent hover:bg-slate-50 dark:hover:bg-slate-800',
                        ].join(' ')}
                      >
                        <div className="flex items-start gap-3">
                          <div className={[
                            'mt-0.5 inline-flex h-8 min-w-8 items-center justify-center rounded-full text-xs font-bold',
                            isActive
                              ? 'bg-cyan-600 text-white'
                              : isDone
                                ? 'bg-emerald-600 text-white'
                                : 'bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-200',
                          ].join(' ')}>
                            {isDone ? <i className="pi pi-check text-[10px]" /> : index + 1}
                          </div>
                          <div className="min-w-0 flex-1">
                            <p className="line-clamp-2 text-sm font-medium leading-5">{step.title}</p>
                            <p className="mt-1 text-xs leading-5 text-slate-500 dark:text-slate-400">{step.metric}</p>
                          </div>
                        </div>
                      </button>
                    );
                  })}
                </div>
              </aside>

              <section className="order-1 rounded-3xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900 sm:p-5 lg:order-2">
                {activeStep && (
                  <div className="flex flex-col gap-5 sm:gap-6">
                    <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
                      <div className="min-w-0">
                        <p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-slate-500 dark:text-slate-400 sm:text-xs">
                          Etapa {activeStepIndex + 1} de {totalSteps}
                        </p>
                        <h2 className="mt-2 text-xl font-semibold tracking-tight sm:text-2xl">{activeStep.title}</h2>
                        <p className="mt-3 text-sm leading-6 text-slate-600 dark:text-slate-300">{activeStep.description}</p>
                      </div>
                      <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-slate-900 text-white dark:bg-slate-100 dark:text-slate-900 sm:h-12 sm:w-12">
                        <i className={`${activeStep.icon} text-base sm:text-lg`} />
                      </div>
                    </div>

                    <div className="grid gap-3 sm:gap-4 md:grid-cols-2">
                      <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4 dark:border-slate-800 dark:bg-slate-950/60">
                        <p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-slate-500 dark:text-slate-400 sm:text-xs">Status atual</p>
                        <p className="mt-2 text-base font-semibold sm:text-lg">{activeStep.metric || 'Em andamento'}</p>
                        <p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300">{activeStep.helper}</p>
                      </div>
                      <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4 dark:border-slate-800 dark:bg-slate-950/60">
                        <p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-slate-500 dark:text-slate-400 sm:text-xs">Para avançar, você precisa:</p>
                        {activeStep.blockers.length > 0 ? (
                          <div className="mt-3 flex flex-col gap-2">
                            {activeStep.blockers.map((blocker) => (
                              <div key={blocker} className="flex items-start gap-2 rounded-xl border border-amber-200 bg-amber-50 px-3 py-2 text-sm leading-5 text-amber-800 dark:border-amber-900/60 dark:bg-amber-950/30 dark:text-amber-200">
                                <i className="pi pi-exclamation-circle mt-0.5 text-xs" />
                                <span>{blocker}</span>
                              </div>
                            ))}
                          </div>
                        ) : (
                          <div className="mt-3 flex items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 px-3 py-2 text-sm leading-5 text-emerald-800 dark:border-emerald-900/60 dark:bg-emerald-950/30 dark:text-emerald-200">
                            <i className="pi pi-check-circle text-sm" />
                            <span className="font-medium">Etapa concluída</span>
                          </div>
                        )}
                      </div>
                    </div>

                    <div className="rounded-2xl border border-cyan-100 bg-cyan-50 p-4 dark:border-cyan-900/60 dark:bg-cyan-950/20">
                      <p className="text-sm font-medium text-cyan-900 dark:text-cyan-200">Vamos continuar?</p>
                      <p className="mt-1 text-sm leading-6 text-cyan-800 dark:text-cyan-300">
                        {activeStep.done
                          ? 'Se quiser, você pode revisar esta configuração ou seguir para a próxima etapa.'
                          : 'Clique abaixo, complete o cadastro e siga para a próxima etapa.'}
                      </p>
                    </div>

                    <div className="flex flex-col gap-3 border-t border-slate-200 pt-4 dark:border-slate-800 sm:pt-5 xl:flex-row xl:items-center xl:justify-between">
                      <button
                        type="button"
                        disabled={!isComplete && activeStep.disabled}
                        onClick={() => void handleNavigateStep()}
                        title={!isComplete && activeStep.disabled ? activeStep.blockers[0] : ''}
                        className={[
                          'rounded-lg px-4 py-2 text-xs text-white transition',
                          !isComplete && activeStep.disabled ? 'cursor-not-allowed bg-blue-300' : 'bg-blue-600 hover:bg-blue-700',
                        ].join(' ')}
                      >
                        {isComplete ? 'Ir para o dashboard' : activeStep.ctaLabel}
                      </button>

                      <div className="grid grid-cols-2 gap-2 sm:flex sm:justify-between">
                        <button
                          type="button"
                          onClick={() => hasPreviousStep && setActiveStepIndex((previous) => previous - 1)}
                          disabled={!hasPreviousStep}
                          className="rounded-lg px-3 py-2 text-sm text-slate-600 transition hover:bg-slate-100 disabled:opacity-40 dark:text-slate-300 dark:hover:bg-slate-800"
                        >
                          <i className="pi pi-arrow-left mr-1 text-xs" />
                          Anterior
                        </button>
                        <button
                          type="button"
                          onClick={() => hasNextStep && setActiveStepIndex((previous) => previous + 1)}
                          disabled={!hasNextStep}
                          className="rounded-lg px-3 py-2 text-sm text-slate-600 transition hover:bg-slate-100 disabled:opacity-40 dark:text-slate-300 dark:hover:bg-slate-800"
                        >
                          Próxima
                          <i className="pi pi-arrow-right ml-1 text-xs" />
                        </button>
                      </div>
                    </div>
                  </div>
                )}
              </section>
            </div>
          )}
        </div>
      </div>

      {embeddedViewActive && (
        <>
          <div className="fixed inset-0 z-40 bg-slate-950/35 backdrop-blur-[2px]" onClick={closeEmbeddedView} />
          <section className="fixed inset-y-0 right-0 z-50 flex h-full w-full max-w-[96vw] flex-col bg-white shadow-2xl dark:bg-slate-900 lg:w-[min(1200px,92vw)]">
            <div className="flex flex-col gap-3 border-b border-slate-200 px-4 py-4 dark:border-slate-800 sm:flex-row sm:items-center sm:justify-between sm:px-5">
              <div>
                <p className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-500 dark:text-slate-400">Tela incorporada</p>
                <h3 className="mt-1 text-lg font-semibold text-slate-900 dark:text-slate-100">{activeStep?.title}</h3>
              </div>
              <button
                type="button"
                onClick={closeEmbeddedView}
                className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm text-slate-700 hover:bg-slate-100 dark:border-slate-700 dark:text-slate-200 dark:hover:bg-slate-800 sm:w-auto"
              >
                <i className="pi pi-times mr-1 text-xs" />
                Fechar
              </button>
            </div>
            <div className="flex-1 overflow-y-auto p-4 sm:p-5">
              {embeddedExternalUrl ? (
                <iframe
                  src={embeddedExternalUrl}
                  className="min-h-[70vh] w-full rounded-2xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-950"
                  referrerPolicy="strict-origin-when-cross-origin"
                  title="Conteúdo externo incorporado"
                />
              ) : (
                <Outlet />
              )}
            </div>
          </section>
        </>
      )}
    </>
  );
}

// angular-app/src/app/features/manage/settings/settings.component.ts
import { Component, OnInit } from '@angular/core';
import { NgClass, NgForOf, NgIf } from '@angular/common';
import { ActivatedRoute, NavigationEnd, Router, RouterOutlet } from '@angular/router';
import { forkJoin } from 'rxjs';
import { filter } from 'rxjs/operators';
import { DomSanitizer, SafeResourceUrl, Title } from '@angular/platform-browser';
import {Button, ButtonDirective} from 'primeng/button';
import { ProgressBar } from 'primeng/progressbar';
import { Tag } from 'primeng/tag';
import { Skeleton } from 'primeng/skeleton';
import { UserService } from '../user/user-service.service';
import { UtilsService } from '../../../core/service/utils.service';
import { AuthService } from '../../../core/auth/auth.service';
import { TeamService } from '../team/team-service.service';
import { StockService } from '../../stock/services/stock.service';
import { MaterialService } from '../../stock/services/material.service';
import { SharedState } from '../../../core/service/shared-state';
import { Utils } from '../../../core/service/utils';
import { ContractService } from '../../contract/services/contract.service';
import {FcmService} from '../../../core/service/fcm.service';

@Component({
    selector: 'app-settings',
    standalone: true,
    imports: [
        NgIf,
        NgForOf,
        NgClass,
        ButtonDirective,
        ProgressBar,
        Tag,
        Skeleton,
        RouterOutlet,
        Button
    ],
    templateUrl: './settings.component.html',
    styleUrl: './settings.component.scss'
})
export class SettingsComponent implements OnInit {
    loading = true;

    referenceContractItems = 0;
    totalContracts = 0;
    totalUsers = 0;
    operationalUsers = 0;
    stockistUsers = 0;
    adminUsers = 0;
    teamsCount = 0;
    stockistsCount = 0;
    depositsCount = 0;
    trucksCount = 0;
    materialsCount = 0;

    onboardingSteps: OnboardingStep[] = [];
    activeStepIndex = 0;
    fieldActivationDone = localStorage.getItem('isFinishedTeamInstruction') === 'true';
    embeddedViewActive = false;
    embeddedExternalUrl: SafeResourceUrl | null = null;
    embeddedExternalUrlRaw: string | null = null;
    notificationStatus = 'default';

    private readonly embeddedRouteMap: Record<string, string> = {
        '/configuracoes/usuarios': 'usuarios',
        '/configuracoes/equipes': 'equipes',
        '/configuracoes/estoquistas': 'estoquistas',
        '/estoque/almoxarifados': 'almoxarifados',
        '/estoque/caminhoes': 'caminhoes',
        '/estoque/cadastrar-material': 'cadastrar-material',
        '/contratos/itens-contratuais/cadastro': 'itens-contratuais',
        '/contratos/itens-contratuais/vinculos': 'itens-contratuais',
        '/contratos/criar': 'criar-contrato',
    };

    constructor(
        protected router: Router,
        private route: ActivatedRoute,
        private sanitizer: DomSanitizer,
        private userService: UserService,
        protected utils: UtilsService,
        protected authService: AuthService,
        private titleService: Title,
        private teamService: TeamService,
        private stockService: StockService,
        private materialService: MaterialService,
        private contractService: ContractService,
        private fcmService: FcmService,
    ) {
        this.titleService.setTitle('Lumos IP - Primeiros passos');
        SharedState.setCurrentPath(['Primeiros passos']);

        this.fcmService.notificationStatus$.subscribe(v => this.notificationStatus = v);
    }

    ngOnInit() {
        this.loadOnboarding();
        this.syncEmbeddedViewState();

        this.router.events
            .pipe(filter(event => event instanceof NavigationEnd))
            .subscribe(() => this.syncEmbeddedViewState());
    }

    private loadOnboarding() {
        this.loading = true;

        forkJoin({
            referenceContractItems: this.contractService.getContractReferenceItems(),
            contracts: this.contractService.getAllContracts(
                {
                    contractor: null,
                    startDate: new Date(new Date().setMonth(new Date().getMonth() - 6)),
                    endDate: new Date(),
                    status: null,
                }
            ),
            users: this.userService.getUsers(),
            teams: this.teamService.getTeams(),
            stockists: this.stockService.getStockists(),
            deposits: this.stockService.getDeposits(),
            materials: this.materialService.getCatalogue(),
        }).subscribe({
            next: ({ referenceContractItems, contracts, users, teams, stockists, deposits, materials }) => {
                this.referenceContractItems = referenceContractItems.length;
                this.totalContracts = contracts.length;

                this.totalUsers = users.length;
                this.adminUsers = users.filter(user => Array.isArray(user.role) && user.role.includes('ADMIN')).length;
                this.operationalUsers = users.filter(user => {
                    const roles = user.role.map(r => r.roleName);
                    return roles.includes('ELETRICISTA') || roles.includes('MOTORISTA')
                }).length;

                this.stockistUsers = users.filter(user => {
                    const roles = user.role.map(r => r.roleName);
                    return roles.includes('ESTOQUISTA') || roles.includes('ESTOQUISTA_CHEFE')
                }
                ).length;

                this.teamsCount = teams.length;
                this.stockistsCount = stockists.length;
                this.depositsCount = deposits.filter(deposit => !deposit.isTruck).length;
                this.trucksCount = deposits.filter(deposit => deposit.isTruck).length;
                this.materialsCount = materials.length;

                this.onboardingSteps = this.buildSteps();
                this.activeStepIndex = this.getInitialStepIndex();
                this.loading = false;
            },
            error: (err) => {
                Utils.handleHttpError(err, this.router);
                this.loading = false;
            }
        });
    }

    private buildSteps(): OnboardingStep[] {
        return [
            {
                id: 'users',
                title: 'Estruture os acessos',
                description: 'Cadastre perfis administrativos e operacionais para destravar os vínculos das próximas etapas.',
                helper: 'Sua operação precisa de estoquistas, eletricistas e motoristas previamente cadastrados.',
                icon: 'pi pi-users',
                route: '/configuracoes/usuarios',
                ctaLabel: this.totalUsers === 0 ? 'Cadastrar usuários...' : 'Revisar usuários...',
                ctaIcon: 'pi pi-user-plus',
                done: this.totalUsers > 0 && this.operationalUsers > 0 && this.stockistUsers > 0,
                metric: `Usuários: ${this.totalUsers}`,
                blockers: [
                    this.totalUsers === 0 ? 'Nenhum usuário cadastrado.' : '',
                    this.operationalUsers === 0 ? 'Cadastrar eletricistas e motoristas.' : '',
                    this.stockistUsers === 0 ? 'Cadastrar estoquistas.' : ''
                ].filter(Boolean),
                disabled: false
            },
            {
                id: 'teams',
                title: 'Monte a equipe operacional',
                description: 'Crie equipes com colaboradores, região de atuação e vínculo de caminhão para liberar a operação em campo.',
                helper: 'Essa etapa destrava ordens de serviço e também reflete nos caminhões do estoque.',
                icon: 'pi pi-user-edit',
                route: '/configuracoes/equipes',
                ctaLabel: this.teamsCount === 0 ? 'Cadastrar equipes...' : 'Gerenciar equipes...',
                ctaIcon: 'pi pi-users',
                done: this.teamsCount > 0,
                metric: `Equipes: ${this.teamsCount}`,
                blockers: [
                    this.operationalUsers === 0 ? 'Voltar ao passo anterior e cadastrar usuários operacionais.' : '',
                    this.teamsCount === 0 ? 'Cadastrar as equipes operacionais.' : ''
                ].filter(Boolean),
                disabled: this.operationalUsers === 0
            },

            {
                id: 'field-activation',
                title: 'Coloque a equipe em campo',
                description: 'Garanta que a equipe operacional tenha acesso ao aplicativo e esteja pronta para iniciar as atividades em campo.',
                helper: this.teamsCount === 0
                    ? 'Crie uma equipe operacional antes de iniciar a operação.'
                    : 'Peça para a equipe baixar o app, fazer login e seguir as instruções iniciais.',
                icon: 'pi pi-mobile',
                route: 'https://lumosip.com.br/como-usar/07-operation/01-android-app-admin/', // ou onde fizer sentido
                externalUrl: true,
                ctaLabel: 'Ver instruções...',
                ctaIcon: 'pi pi-external-link',
                done: this.fieldActivationDone,
                metric: this.fieldActivationDone
                    ? 'Equipe pronta para operação'
                    : 'Ativação pendente',
                blockers: [
                    this.operationalUsers === 0 ? 'Voltar ao passo 1 e cadastrar usuários operacionais.' : '',
                    this.teamsCount === 0 ? 'Voltar ao passo anterior e cadastrar as equipes operacionais.' : '',
                    !this.fieldActivationDone
                        ? 'Orientar a equipe a baixar o aplicativo e acessar o sistema.'
                        : ''
                ].filter(Boolean),
                disabled: this.operationalUsers === 0 || this.teamsCount === 0
            },
            {
                id: 'deposits',
                title: 'Prepare a base logística',
                description: 'Configure almoxarifados e caminhões para garantir origem, destino e rastreabilidade do material.',
                helper: 'Movimentação de estoque depende de pelo menos um almoxarifado e um caminhão.',
                icon: 'pi pi-truck',
                route: this.depositsCount === 0 ? '/estoque/almoxarifados' : '/estoque/caminhoes',
                ctaLabel: this.depositsCount === 0 ? 'Cadastrar almoxarifados...' : this.trucksCount === 0 ? 'Cadastrar caminhões...' : 'Revisar logística...',
                ctaIcon: this.depositsCount === 0 ? 'pi pi-home' : 'pi pi-truck',
                done: this.depositsCount > 0 && this.trucksCount > 0,
                metric: `Almoxarifados: ${this.depositsCount} • Caminhões: ${this.trucksCount}`,
                blockers: [
                    this.depositsCount === 0 ? 'Cadastrar almoxarifados fixos.' : '',
                    this.trucksCount === 0 ? 'Cadastrar almoxarifados móveis/caminhões.' : ''
                ].filter(Boolean),
                disabled: false
            },
            {
                id: 'stockists',
                title: 'Defina os estoquistas',
                description: 'Associe responsáveis pelo estoque para liberar o gerenciamento de reservas e expedições.',
                helper: 'Essa etapa é obrigatória para criação e acompanhamento de ordens com movimentação de material.',
                icon: 'pi pi-briefcase',
                route: '/configuracoes/estoquistas',
                ctaLabel: this.stockistsCount === 0 ? 'Cadastrar estoquistas...' : 'Gerenciar estoquistas...',
                ctaIcon: 'pi pi-briefcase',
                done: this.stockistsCount > 0,
                metric: `Estoquistas: ${this.stockistsCount}`,
                blockers: [
                    this.depositsCount === 0 ? 'Voltar ao passo anterior e cadastrar os almoxarifados.' : '',
                    this.stockistsCount === 0 ? 'Cadastrar os estoquistas.' : ''
                ].filter(Boolean),
                disabled: this.depositsCount === 0
            },
            {
                id: 'materials',
                title: 'Abasteça o catálogo de materiais',
                description: 'Cadastre materiais para que estoque, contratos e execuções consigam operar sem bloqueios.',
                helper: 'Sem catálogo não há movimentação, separação e apontamento de itens.',
                icon: 'pi pi-box',
                route: '/estoque/cadastrar-material',
                ctaLabel: this.materialsCount === 0 ? 'Cadastrar materiais...' : 'Ver catálogo...',
                ctaIcon: 'pi pi-box',
                done: this.materialsCount > 0,
                metric: `Materiais: ${this.materialsCount}`,
                blockers: [
                    this.materialsCount === 0 ? 'Cadastrar o catálogo de materiais.' : ''
                ].filter(Boolean),
                disabled: false
            },
            {
                id: 'reference-items',
                title: 'Cadastre os itens contratuais',
                description: 'Crie os itens contratuais que serão usados como base para vincular contratos nas próximas etapas.',
                helper: 'Sem itens contratuais cadastrados, não é possível avançar na configuração de contratos.',
                icon: 'pi pi-file-edit',
                route: '/contratos/itens-contratuais/cadastro',
                ctaLabel: this.referenceContractItems === 0
                    ? 'Cadastrar itens contratuais...'
                    : 'Gerenciar itens...',
                ctaIcon: this.referenceContractItems === 0
                    ? 'pi pi-plus'
                    : 'pi pi-pencil',
                done: this.referenceContractItems > 0,
                metric: `Itens contratuais: ${this.referenceContractItems}`,
                blockers: [
                    this.referenceContractItems === 0
                        ? 'Cadastrar o catálogo de itens contratuais.'
                        : ''
                ].filter(Boolean),
                disabled: false
            },

            {
                id: 'contracts',
                title: 'Cadastre os contratos',
                description: 'Crie contratos para organizar e vincular seus itens contratuais e iniciar a operação.',
                helper: this.referenceContractItems === 0
                    ? 'Antes de cadastrar contratos, você precisa criar pelo menos um item contratual.'
                    : 'Com os itens contratuais cadastrados, você já pode criar seus contratos.',

                icon: 'pi pi-briefcase',
                route: '/contratos/criar',
                ctaLabel: this.totalContracts === 0
                    ? 'Cadastrar contratos...'
                    : 'Gerenciar contratos...',
                ctaIcon: this.totalContracts === 0
                    ? 'pi pi-plus'
                    : 'pi pi-pencil',
                done: this.totalContracts > 0,
                metric: `Contratos: ${this.totalContracts}`,
                blockers: [
                    this.referenceContractItems === 0
                        ? 'Voltar ao passo anterior e cadastrar o catálogo de itens contratuais.'
                        : '',
                    this.totalContracts === 0
                        ? 'Cadastrar os contratos.'
                        : ''
                ].filter(Boolean),
                disabled: this.referenceContractItems === 0
            },
            {
                id: 'notifications',
                title: 'Ative as notificações',
                description: 'Para não perder nenhum alerta importante na sua operação',
                helper: ['default', 'denied'].includes(this.notificationStatus)
                    ? 'Notificações desativadas.'
                    : 'Notificações ativadas.',

                icon: 'pi pi-bell',
                route: '/contratos/criar',
                ctaLabel: ['default', 'denied'].includes(this.notificationStatus)
                    ? 'Ativar notificações...'
                    : 'Gerar primeira ordem de serviço...',
                ctaIcon: ['default', 'denied'].includes(this.notificationStatus)
                    ? 'pi pi-bell'
                    : 'pi pi-home',
                done: this.notificationStatus === 'granted',
                metric: '',
                blockers: [
                    ['default', 'denied'].includes(this.notificationStatus)
                        ? 'Ativar as notificações do sistema.'
                        : ''
                ].filter(Boolean),
                disabled: false
            },

        ];
    }

    private getInitialStepIndex(): number {
        const firstPendingIndex = this.onboardingSteps.findIndex(step => !step.done);
        return firstPendingIndex >= 0 ? firstPendingIndex : 0;
    }

    get completedSteps(): number {
        return this.onboardingSteps.filter(step => step.done).length;
    }

    get totalSteps(): number {
        return this.onboardingSteps.length;
    }

    get completionPercent(): number {
        if (this.totalSteps === 0) {
            return 0;
        }

        return Math.round((this.completedSteps / this.totalSteps) * 100);
    }

    get pendingSteps(): OnboardingStep[] {
        return this.onboardingSteps.filter(step => !step.done);
    }

    get activeStep(): OnboardingStep | undefined {
        return this.onboardingSteps[this.activeStepIndex];
    }

    get isComplete(): boolean {
        return this.pendingSteps.length === 0;
    }

    get hasPreviousStep(): boolean {
        return this.activeStepIndex > 0;
    }

    get hasNextStep(): boolean {
        return this.activeStepIndex < this.totalSteps - 1;
    }

    get nextPendingStep(): OnboardingStep | undefined {
        return this.pendingSteps[0];
    }

    get heroTitle(): string {
        return this.isComplete
            ? 'Tudo pronto para começar 🚀'
            : 'Configure o sistema e comece a usar';
    }

    get heroSubtitle(): string {
        return this.isComplete
            ? 'Tudo pronto! Agora é só colocar sua equipe em campo e começar a usar o sistema. Dica: gere sua primeira ordem de serviço para iniciar a operação.'
            : 'Vamos finalizar sua configuração inicial. Comece pelo próximo passo.';
    }

    get progressLabel(): string {
        return `${this.completedSteps} de ${this.totalSteps} etapas concluídas`;
    }

    get activeStepNumber(): number {
        return this.activeStepIndex + 1;
    }

    get activeStepActionLabel(): string {
        if (this.isComplete) {
            return 'Ir para o dashboard';
        }

        return this.activeStep?.ctaLabel ?? 'Continuar';
    }

    get cursorClass(): string {
        if (this.isComplete || !this.activeStep?.disabled) {
            return 'cursor-pointer';
        }

        return 'cursor-not-allowed';
    }

    get isDisabled(): boolean {
        if (this.isComplete) {
            return false;
        }

        return this.activeStep?.disabled ?? false;
    }

    get descriptionLabel(): string {
        if (this.isComplete || !this.activeStep?.disabled) {
            return '';
        }

        return this.activeStep?.blockers[0];
    }

    get activeStepActionRoute(): string {
        if (this.isComplete) {
            return '/dashboard';
        }

        return this.activeStep?.route ?? '/configuracoes/onboarding';
    }

    get isExternalUrl(): boolean {
        if (this.isComplete) {
            return false;
        }

        return this.activeStep?.externalUrl ?? false;
    }

    set isFinishedTeamInstruction(value: string) {
        localStorage.setItem('isFinishedTeamInstruction', value);
    }

    selectStep(index: number) {
        this.activeStepIndex = index;
    }

    goToPreviousStep() {
        if (this.hasPreviousStep) {
            this.activeStepIndex -= 1;
        }
    }

    goToNextStep() {
        if (this.hasNextStep) {
            this.activeStepIndex += 1;
        }
    }

    navigate(path: string, externalUrl: boolean) {
        if (externalUrl) {
            this.embeddedExternalUrlRaw = path;
            this.embeddedExternalUrl = this.sanitizer.bypassSecurityTrustResourceUrl(path);
            this.syncEmbeddedViewState();
            void this.router.navigate(['/configuracoes/onboarding']);
            this.isFinishedTeamInstruction = "true";
            this.fieldActivationDone = true;
            this.buildSteps();
            return;
        }

        this.embeddedExternalUrl = null;
        this.embeddedExternalUrlRaw = null;

        const embeddedChildPath = this.embeddedRouteMap[path];

        if (embeddedChildPath) {
            void this.router.navigate([embeddedChildPath], { relativeTo: this.route });
        } else {
            void this.router.navigate([path]);
        }
    }

    closeEmbeddedView() {
        this.embeddedExternalUrl = null;
        this.embeddedExternalUrlRaw = null;
        this.syncEmbeddedViewState();
        void this.router.navigate(['/configuracoes/onboarding']);
    }

    private syncEmbeddedViewState() {
        this.embeddedViewActive = !!this.route.firstChild || !!this.embeddedExternalUrl;
    }
}

interface OnboardingStep {
    id: string;
    title: string;
    description: string;
    helper: string;
    icon: string;
    route: string;
    ctaLabel: string;
    ctaIcon: string;
    done: boolean;
    metric: string;
    blockers: string[];
    externalUrl?: boolean;
    disabled: boolean;
}
