// angular-app/src/app/app-download/app-download.component.ts
import {Component} from '@angular/core';
import {Menubar} from 'primeng/menubar';

@Component({
  selector: 'app-app-download',
  standalone: true,
  imports: [
    Menubar,
  ],
  templateUrl: './app-download.component.html',
  styleUrl: './app-download.component.scss'
})
export class AppDownloadComponent {

// no seu componente .ts
  downloadApk() {
    const link = document.createElement('a');
    link.href = 'https://minio.thryon.com.br/apk/com.thryon.apps.android.release_3_2.1.0'; // link do arquivo que quer baixar
    link.download = 'com.thryon.apps.android.release_3_2.1.0.apk'; // nome que o arquivo terá ao baixar
    link.click();
  }

}

<div class="card pb-2">
  <p-menubar styleClass="h-12">
    <ng-template #start>
      <a href="/">
        <h3 class="bg-gradient-to-r  from-indigo-800 via-indigo-500 to-indigo-300 text-transparent bg-clip-text cursor-pointer">
          Thryon System™
        </h3>
      </a>

    </ng-template>

  </p-menubar>
</div>
<div class="border rounded min-h-[calc(100vh-66px)] flex items-center justify-center p-6">

  <div class="max-w-5xl w-full flex flex-col lg:flex-row items-center gap-48">

    <div class="text-center">
      <img src="public/ic_lumos.png" width="80" alt="Lumos App" class="mx-auto max-w-xs mb-6" />
      <h2 class="text-2xl font-semibold mb-4">Celular Android</h2>

      <p class="text-sm leading-normal mb-3 text-justify max-w-sm mx-auto">
        Para usar o app Lumos no seu celular Android, você precisa de um aparelho com Android 9.0 ou superior. O app funciona melhor em dispositivos atualizados, garantindo uma experiência rápida e segura.
      </p>

      <p class="text-sm leading-normal mb-3 text-justify max-w-sm mx-auto">
        Na primeira vez que você abre o app, é necessário estar conectado à internet para fazer login e carregar as informações iniciais. Após isso, o app continua funcionando normalmente mesmo sem conexão.
      </p>

      <p class="text-sm leading-normal mb-3 text-justify max-w-sm mx-auto">
        Os dados que você preenche ou atualiza ficam salvos no seu celular e são enviados para nossos servidores assim que a internet estiver disponível novamente. Você pode continuar usando o app, sem perder nada.
      </p>

      <p class="text-sm leading-normal mb-3 text-justify max-w-sm mx-auto">
        O app irá pedir permissões como acesso à localização ou ao câmera. Isso é esperado, necessário e ajuda o sistema a funcionar da melhor forma.
      </p>
    </div>





    <!-- Texto e instruções -->
    <div class="flex-1">
      <h1 class="text-3xl font-bold mb-6">
        Instalar o sistema Lumos no seu <span class="text-primary dark:text-primary">celular Android</span>
      </h1>

      <ul class="space-y-3 text-base">
        <li><i class="fa-solid fa-circle-down text-primary pr-2"></i> Clique no botão "Baixar" que aparece mais abaixo.</li>
        <li><i class="fa-solid fa-folder text-primary pr-2"></i> Busque o arquivo na seção de downloads do seu dispositivo.</li>
        <li><i class="fa-solid fa-circle-check text-primary pr-2"></i> Selecione-o, conceda as permissões necessárias e conclua a instalação.</li>
        <li><i class="fa-solid fa-rocket text-primary pr-2"></i> Pronto! Agora é só abrir o Lumos e aproveitar.</li>
      </ul>

      <!-- Botões -->
      <div class="mt-8 flex flex-wrap gap-4">
        <button
          class="btn btn-wide btn-primary text-white px-6 py-3 rounded-full font-medium"
          (click)="downloadApk()">
          Baixar
        </button>
      </div>
    </div>
  </div>
</div>

// react-app/src/features/app-download/pages/AppDownload.tsx
import { useEffect } from 'react';
import { useAppStore } from '@/store/use-app-store';

const APK_URL = 'https://api.thryon.com.br/minio/apk/com.thryon.apps.android.release_9_2.1.6.apk';
const APK_NAME = 'com.thryon.apps.android.release_9_2.1.6.apk';

export default function AppDownload() {
  const { setPageContext } = useAppStore();

  useEffect(() => {
    setPageContext(['Aplicativo', 'Download'], 'Instalar app no Android');
  }, [setPageContext]);

  const downloadApk = () => {
    const link = document.createElement('a');
    link.href = APK_URL;
    link.download = APK_NAME;
    link.click();
  };

  return (
    <section className="p-4 md:p-6">
      <div className="mx-auto max-w-6xl rounded-3xl border border-slate-200 bg-white p-6 shadow-sm dark:border-zinc-800 dark:bg-zinc-900 lg:p-10">
        <div className="grid gap-8 lg:grid-cols-[0.9fr_1.1fr] lg:gap-16">
          <article className="text-center lg:text-left">
            <img src="/ic_lumos.png" width="84" alt="Lumos App" className="mx-auto mb-6 lg:mx-0" />
            <h2 className="text-2xl font-semibold text-slate-900 dark:text-zinc-100">Celular Android</h2>

            <div className="mt-4 space-y-3 text-sm leading-7 text-slate-600 dark:text-zinc-300">
              <p>Para usar o app Lumos no seu celular Android, você precisa de um aparelho com Android 9.0 ou superior.</p>
              <p>Na primeira vez que você abre o app, é necessário estar conectado à internet para fazer login e carregar as informações iniciais.</p>
              <p>Os dados preenchidos ficam salvos no dispositivo e são enviados para o servidor quando a conexão retornar.</p>
              <p>O app irá solicitar permissões de localização e câmera para funcionamento da operação.</p>
            </div>
          </article>

          <article>
            <h1 className="text-3xl font-bold text-slate-900 dark:text-zinc-100">
              Instalar o Lumos no seu <span className="bg-gradient-to-r from-blue-600 to-cyan-500 bg-clip-text text-transparent">celular Android</span>
            </h1>

            <ol className="mt-6 space-y-3 text-base text-slate-700 dark:text-zinc-200">
              <li><i className="pi pi-download mr-2 text-blue-500" />Clique no botão <strong>Baixar APK</strong>.</li>
              <li><i className="pi pi-folder mr-2 text-blue-500" />Encontre o arquivo na pasta de downloads.</li>
              <li><i className="pi pi-check-circle mr-2 text-blue-500" />Abra o arquivo, conceda permissões e conclua a instalação.</li>
              <li><i className="pi pi-bolt mr-2 text-blue-500" />Abra o app Lumos e faça login.</li>
            </ol>

            <div className="mt-8">
              <button
                type="button"
                onClick={downloadApk}
                className="rounded-full bg-gradient-to-r from-blue-600 to-cyan-500 px-8 py-3 text-sm font-semibold text-white shadow-lg shadow-blue-500/25 hover:from-blue-500 hover:to-cyan-400"
              >
                <i className="pi pi-download mr-2" />Baixar APK
              </button>
            </div>
          </article>
        </div>
      </div>
    </section>
  );
}
