// angular-app/src/app/core/auth/pages/login/login.component.ts
import {Component} from '@angular/core';
import {NgIf, NgOptimizedImage} from '@angular/common';
import {FormsModule, NgForm} from '@angular/forms';
import {AuthService} from '../../auth.service';
import {Router} from '@angular/router';
import {Title} from '@angular/platform-browser';
import {map} from 'rxjs';
import {UtilsService} from '../../../service/utils.service';
import {ScreenMessageComponent} from '../../../../shared/components/screen-message/screen-message.component';
import {Toast} from 'primeng/toast';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [
    FormsModule,
    NgIf,
    Toast
  ],
  templateUrl: './login.component.html',
  styleUrl: './login.component.scss',
})
export class LoginComponent {
  username: string = '';
  password: string = '';
  showPassword: boolean = false;
  message: string = 'Foi enviada uma nova senha para seu email, por favor verifique sua caixa de entrada e spam.';

  constructor(private authService: AuthService, private router: Router, private titleService: Title, protected utils: UtilsService) {
    this.titleService.setTitle("Lumos - Login");

    this.authService.isLoggedIn$.pipe(
      map(isLoggedIn => {
        if (isLoggedIn) {
          this.router.navigate(['/']);
        }
        return isLoggedIn;
      })
    ).subscribe();
  }

  login(form: NgForm) {
    if (form.valid) {
      this.authService.login(this.username, this.password).subscribe(
        response => {
          if (response) {
            console.log('Login realizado com sucesso:', response);
            void this.router.navigate(['/']); // Redireciona após o login bem-sucedido
          } else {
            this.utils.showMessage("Email/Usuário ou senha incorretos", 'error');
          }
        },
        error => {
          this.utils.showMessage("Email/Usuário ou senha incorretos",  'error');
        }
      );
    }
  }

  togglePasswordVisibility() {
    this.showPassword = !this.showPassword;
  }

  loading = false;
  finished = false;

  forgetPassword(error: HTMLElement) {
    if (this.username.length == 0) {
      error.innerText = 'Campo obrigatório.';
      return;
    }

    this.loading = true;
    this.authService.forgetPassword(this.username).subscribe({
      next: (response) => {
        this.message = response.message;
        error.innerText = '';
        this.finished = true;
        this.loading = false;
      },
      error: error => {
        error.innerText = '';
        this.utils.showMessage("Serviço fora do ar - Solicite ao Administrador", 'error', "Lumos™");
        this.loading = false;
      }
    });
  }
}

<section class="login-shell relative min-h-screen w-full overflow-hidden bg-slate-950 text-surface-50">
  <img src="/public/lumos-login-bg.png" alt="Iluminação pública urbana"
    class="absolute inset-0 h-full w-full object-cover object-center opacity-20" />

  <div
    class="absolute inset-0 bg-[radial-gradient(circle_at_top_left,_rgba(59,130,246,0.25),_transparent_34%),radial-gradient(circle_at_bottom_right,_rgba(20,184,166,0.18),_transparent_30%)]">
  </div>
  <!-- <div class="absolute inset-0 bg-gradient-to-br from-slate-950 via-slate-900/[0.96] to-slate-950/[0.92]"></div> -->

  <div class="pointer-events-none absolute -left-24 top-24 h-72 w-72 rounded-full bg-primary/20 blur-3xl"></div>
  <div class="pointer-events-none absolute bottom-0 right-0 h-80 w-80 rounded-full bg-cyan-400/10 blur-3xl"></div>

  <div class="relative z-10 flex min-h-screen flex-col lg:flex-row">
    <aside class="hidden lg:flex lg:w-[54%] lg:items-center lg:justify-center lg:px-12 lg:py-10 xl:px-20">
      <div class="w-full max-w-xl rounded-[2rem] border border-white/10 bg-black/[0.16] p-10 backdrop-blur-2xl">
        <div
          class="mb-8 inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[0.06] px-4 py-2 text-sm text-slate-200">
          <i class="pi pi-lock text-primary-300"></i>
          Acesso seguro
        </div>

        <div class="space-y-4">
          <h2 class="text-4xl font-semibold leading-tight text-white xl:text-5xl">
            Entre na plataforma Lumos.
          </h2>
          <p class="max-w-lg text-base leading-7 text-slate-300">
            Gerencie suas execuções, vincule itens contratuais e consolide suas medições em um ambiente unificado.
          </p>
        </div>

        <div class="mt-10 grid gap-3">
          <div
            class="flex items-center gap-3 rounded-2xl border border-white/10 bg-white/[0.04] px-4 py-4 text-slate-200">
            <i class="pi pi-check-circle text-primary-300"></i>
            Gestão de execuções e instalações
          </div>
          <div
            class="flex items-center gap-3 rounded-2xl border border-white/10 bg-white/[0.04] px-4 py-4 text-slate-200">
            <i class="pi pi-link text-primary-300"></i>
            Vínculo de itens e regras contratuais
          </div>
          <div
            class="flex items-center gap-3 rounded-2xl border border-white/10 bg-white/[0.04] px-4 py-4 text-slate-200">
            <i class="pi pi-file-export text-primary-300"></i>
            Fechamento de medições para faturamento
          </div>
        </div>
      </div>
    </aside>

    <main class="flex min-h-screen items-center justify-center px-4 py-8 sm:px-6 lg:min-h-0 lg:w-[46%] lg:px-10">
      <div class="w-full max-w-lg">

        <div class="mb-8 text-center">
          <div
            class="mx-auto mb-4 flex h-[4.5rem] w-[4.5rem] items-center justify-center shadow-primary/20 backdrop-blur-xl">
            <img ngSrc="/public/icon-192.png" width="64" height="64" alt="Lumos" class="drop-shadow-lg" />
          </div>

          <div class="space-y-2">
            <h1 class="text-3xl font-semibold tracking-tight text-white sm:text-4xl">
              Lumos<span class="text-primary-300">™</span>
            </h1>
            <p class="mx-auto max-w-md text-sm leading-6 text-slate-300">
              Faça login para acessar a plataforma.
            </p>
          </div>
        </div>

        <div class="mb-6 flex w-full rounded-2xl border border-white/10 bg-black/20 p-1 backdrop-blur-xl" role="tablist"
          aria-label="Modos de acesso">
          <button type="button" role="tab" [attr.aria-selected]="activeTab === 'login'" (click)="activeTab = 'login'"
            [class.active]="activeTab === 'login'"
            class="tab-pill flex flex-col items-center justify-center gap-1 flex-1 py-3 text-xs sm:text-sm">
            <i class="pi pi-sign-in text-lg"></i>
            <span>Entrar</span>
          </button>

          <button type="button" role="tab" [attr.aria-selected]="activeTab === 'signup'" (click)="activeTab = 'signup'"
            [class.active]="activeTab === 'signup'"
            class="tab-pill flex flex-col items-center justify-center gap-1 flex-1 py-3 text-xs sm:text-sm">
            <i class="pi pi-user-plus text-lg"></i>
            <span>Teste</span>
          </button>

          <button type="button" role="tab" [attr.aria-selected]="activeTab === 'demo'" (click)="activeTab = 'demo'"
            [class.active]="activeTab === 'demo'"
            class="tab-pill flex flex-col items-center justify-center gap-1 flex-1 py-3 text-xs sm:text-sm">
            <i class="pi pi-star text-lg"></i>
            <span>Demo</span>
          </button>
        </div>

        <div *ngIf="activeTab === 'login'" class="login-card">
          <p-card
            class="block rounded-[2rem] border border-white/10 bg-white/10 shadow-2xl shadow-slate-950/30 backdrop-blur-2xl">
            <div class="mb-6 space-y-3">
              <div>
                <h3 class="text-2xl font-semibold text-white">Acessar conta</h3>
                <p class="mt-2 text-sm leading-6 text-slate-300">
                  Use seu usuário ou CPF e sua senha para entrar.
                </p>
              </div>
            </div>

            <form #form="ngForm" (ngSubmit)="login(form)" class="flex flex-col gap-5">
              <div class="flex flex-col gap-2">
                <label class="text-xs font-semibold uppercase tracking-[0.24em] text-slate-300">
                  Usuário ou CPF
                </label>

                <div class="relative">
                  <span class="login-input-icon">
                    <i class="pi pi-user"></i>
                  </span>
                  <input 
                    (keyup)="$event.key === 'Enter' && username && password && authLoading  ? submitBtn.click() : null"
                    pInputText type="text" name="username" [(ngModel)]="username" (blur)="normalizeUsername()"
                    placeholder="Digite seu usuário ou CPF" autocomplete="username" inputmode="text" required
                    class="login-input w-full rounded-2xl pl-11 pr-4 py-3.5" />
                </div>

              </div>

              <div class="flex flex-col gap-2">
                <div class="flex items-center justify-between gap-3">
                  <label class="text-xs font-semibold uppercase tracking-[0.24em] text-slate-300">
                    Senha
                  </label>

                  <button type="button" (click)="forgetPassword()"
                    class="text-xs font-medium text-primary-200 transition-colors hover:text-primary-100">
                    Esqueci minha senha
                  </button>
                </div>

                <div class="relative">
                  <span class="login-input-icon">
                    <i class="pi pi-key"></i>
                  </span>
                  <p-password 
                    (keyup)="$event.key === 'Enter' && username && password && authLoading  ? submitBtn.click() : null"
                    name="password" [(ngModel)]="password" placeholder="Digite sua senha"
                    autocomplete="current-password" required [toggleMask]="true" [feedback]="false" fluid
                    inputStyleClass="login-input w-full rounded-2xl pl-11 pr-12 py-3.5">
                  </p-password>
                </div>
              </div>

              <p-message *ngIf="finished" severity="success" [text]="message" styleClass="w-full">
              </p-message>

              <p-message *ngIf="authError" severity="error" [text]="authError" styleClass="w-full">
              </p-message>

              <button type="button" (click)="router.navigate(['/primeiro-acesso'])"
                class="text-sm font-medium text-primary-200 transition-colors hover:text-primary-100 text-left">
                Primeiro acesso? Ative sua conta aqui
              </button>

              <button type="submit" class="hidden" #submitBtn></button>

              <p-button label="Entrar na plataforma" type="submit" [loading]="authLoading"
                [disabled]="!username || !password || authLoading"
                styleClass="w-full !py-3.5 rounded-2xl font-semibold bg-gradient-to-r from-primary to-cyan-500 hover:from-primary-600 hover:to-cyan-500 text-white shadow-lg shadow-primary/20">
              </p-button>
            </form>

          </p-card>
        </div>

        <div *ngIf="activeTab === 'signup'" class="login-card">
          <p-card
            class="block rounded-[2rem] border border-white/10 bg-white/10 shadow-2xl shadow-slate-950/30 backdrop-blur-2xl">
            <div class="space-y-6">
              <div class="space-y-3">
                <div
                  class="inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/10 px-3 py-1 text-xs font-medium text-primary-100">
                  <i class="pi pi-star-fill text-[0.75rem]"></i>
                  Experimente com apoio da equipe
                </div>
                <div>
                  <h3 class="text-2xl font-semibold text-white">Comece um teste gratuito</h3>
                  <p class="mt-2 text-sm leading-6 text-slate-300">
                    Valide o Lumos com seu cenário real e conheça os módulos mais relevantes para sua operação.
                  </p>
                </div>
              </div>

              <div class="grid gap-3">
                <div class="rounded-2xl border border-primary/20 bg-primary/10 p-4">
                  <div class="flex items-start gap-3">
                    <i class="pi pi-gift mt-1 text-lg text-primary-200"></i>
                    <div>
                      <p class="font-semibold text-white">14 dias para explorar a plataforma</p>
                      <p class="mt-1 text-sm leading-6 text-slate-300">Teste os fluxos principais sem precisar de cartão
                        de crédito.</p>
                    </div>
                  </div>
                </div>

                <div class="rounded-2xl border border-white/10 bg-black/10 p-4">
                  <div class="flex items-start gap-3">
                    <i class="pi pi-send mt-1 text-lg text-emerald-200"></i>
                    <div>
                      <p class="font-semibold text-white">Ativação guiada</p>
                      <p class="mt-1 text-sm leading-6 text-slate-300">Receba suporte para cadastrar estrutura, equipes
                        e frentes de trabalho.</p>
                    </div>
                  </div>
                </div>

                <div class="rounded-2xl border border-white/10 bg-black/10 p-4">
                  <div class="flex items-start gap-3">
                    <i class="pi pi-shield mt-1 text-lg text-cyan-100"></i>
                    <div>
                      <p class="font-semibold text-white">Ambiente seguro desde o primeiro acesso</p>
                      <p class="mt-1 text-sm leading-6 text-slate-300">Controle de perfis e visibilidade dos dados
                        durante a avaliação.</p>
                    </div>
                  </div>
                </div>
              </div>

              <p-button label="Começar teste gratuito" type="button" icon="pi pi-arrow-right"
                (click)="openSubscriptionModal()"
                styleClass="mt-4 w-full !py-3.5 rounded-2xl font-semibold bg-gradient-to-r from-primary to-cyan-500 hover:from-primary-600 hover:to-cyan-500 text-white shadow-lg shadow-primary/20">
              </p-button>

              <p class="text-center text-xs text-slate-400">
                Já tem conta?
                <button type="button" (click)="activeTab = 'login'"
                  class="ml-1 font-semibold text-primary-200 transition-colors hover:text-primary-100">
                  Entrar agora
                </button>
              </p>
            </div>
          </p-card>
        </div>

        <div *ngIf="activeTab === 'demo'" class="login-card">
          <p-card
            class="block rounded-[2rem] border border-white/10 bg-white/10 shadow-2xl shadow-slate-950/30 backdrop-blur-2xl">
            <div class="space-y-6">
              <div class="space-y-3 text-center">
                <div
                  class="mx-auto flex h-16 w-16 items-center justify-center rounded-full border border-primary/[0.25] bg-primary/[0.12] text-primary-100">
                  <i class="pi pi-desktop text-2xl"></i>
                </div>
                <div>
                  <h3 class="text-2xl font-semibold text-white">Veja o Lumos em ação</h3>
                  <p class="mt-2 text-sm leading-6 text-slate-300">
                    Agende uma apresentação consultiva para entender como o produto se encaixa na sua operação.
                  </p>
                </div>
              </div>

              <div class="grid gap-3">
                <div class="rounded-2xl border border-white/10 bg-black/10 px-4 py-4">
                  <div class="flex items-center gap-3 text-sm text-slate-200">
                    <i class="pi pi-check text-primary-200"></i>
                    Apresentação focada nos fluxos mais críticos da sua equipe
                  </div>
                </div>

                <div class="rounded-2xl border border-white/10 bg-black/10 px-4 py-4">
                  <div class="flex items-center gap-3 text-sm text-slate-200">
                    <i class="pi pi-check text-primary-200"></i>
                    Discussão sobre implantação, governança e produtividade
                  </div>
                </div>

                <div class="rounded-2xl border border-white/10 bg-black/10 px-4 py-4">
                  <div class="flex items-center gap-3 text-sm text-slate-200">
                    <i class="pi pi-check text-primary-200"></i>
                    Próximos passos claros para piloto ou adoção completa
                  </div>
                </div>
              </div>

              <p-button label="Solicitar demonstração" type="button" icon="pi pi-calendar" (click)="openDemoModal()"
                styleClass="mt-4 w-full !py-3.5 rounded-2xl font-semibold bg-gradient-to-r from-primary to-cyan-500 hover:from-primary-600 hover:to-cyan-500 text-white shadow-lg shadow-primary/20">
              </p-button>

              <p class="text-center text-xs text-slate-400">
                Prefere explorar por conta própria?
                <button type="button" (click)="activeTab = 'signup'"
                  class="ml-1 font-semibold text-primary-200 transition-colors hover:text-primary-100">
                  Ativar teste
                </button>
              </p>
            </div>
          </p-card>
        </div>
      </div>
    </main>
  </div>

  <p-toast></p-toast>
</section>

// react-app/src/features/auth/pages/Login.tsx
import React, { useMemo, useState, useEffect } from 'react';
import { useLocation, useNavigate, useSearchParams, Link } from 'react-router-dom';
import { useAuthStore } from '../../../core/auth/useAuthStore';
import { useNotify } from '../../../shared/hooks/use-notify';
import { useAppStore } from '../../../store/use-app-store';
import api from '../../../core/auth/api';
import { checkOnboardingState } from '../../../core/onboarding/checkOnboardingState';

export default function Login() {
    const navigate = useNavigate();
    const location = useLocation();
    const [searchParams] = useSearchParams();
    const { login, isLoading, isLoggedIn, applyAuthResponse } = useAuthStore();
    const { toggleMenu, setOnboarding } = useAppStore();
    const { notify } = useNotify();

    // --- UI State ---
    const [activeTab, setActiveTab] = useState<'login' | 'signup' | 'demo'>('login');
    const [username, setUsername] = useState('');
    const [password, setPassword] = useState('');
    const [showPassword, setShowPassword] = useState(false);
    const [authError, setAuthError] = useState<string | null>(null);
    const [authLoading, setAuthLoading] = useState(false);
    const [finished, setFinished] = useState(false);
    const [message, setMessage] = useState('');

    const redirectPath = useMemo(() => {
        const redirectFromQuery = searchParams.get('redirect');
        if (redirectFromQuery) {
            return redirectFromQuery;
        }

        const from = (location.state as { from?: { pathname?: string; search?: string } } | null)?.from;
        if (from?.pathname) {
            return `${from.pathname}${from.search ?? ''}`;
        }

        return '/';
    }, [location.state, searchParams]);

    // --- Recuperação de Parâmetros da URL ---
    useEffect(() => {
        if (isLoggedIn) {
            navigate(redirectPath);
            return;
        }

        const token = searchParams.get('token');
        const activated = searchParams.get('activated');
        const redirect = searchParams.get('redirect');

        if (activated === '1') {
            setFinished(true);
            setMessage('Conta ativada com sucesso. Faça login com sua nova senha.');
        }

        if (token) {
            handleQrCodeLogin(token, redirect);
        }
    }, [isLoggedIn, navigate, redirectPath, searchParams]);

    const checkStateAndRedirect = async (targetPath: string) => {
        setAuthLoading(true);
        try {
            const isOnboardingPending = await checkOnboardingState();

            if (isOnboardingPending) {
                localStorage.removeItem('onboarding');
                setOnboarding(true);
                navigate('/configuracoes/onboarding');
                return;
            }

            localStorage.setItem('onboarding', 'finished');
            setOnboarding(false);
            navigate(targetPath);
        } catch {
            notify('Erro ao validar configuração inicial.', 'error');
            navigate(targetPath);
        } finally {
            setAuthLoading(false);
        }
    };

    // --- Handlers ---
    const handleQrCodeLogin = async (token: string, redirect: string | null) => {
        try {
            const response = await api.post('/api/auth/login-with-qrcode-token', null, {
                params: { token }
            });
            applyAuthResponse(response.data.accessToken);
            navigate(redirect || redirectPath);
        } catch (error) {
            notify('Erro ao autenticar via QR Code', 'error');
        }
    };

    const normalizeUsername = () => {
        const digits = username.replace(/\D/g, '');
        if (digits.length === 11) setUsername(digits);
    };

    const handleLogin = async (e: React.FormEvent) => {
        e.preventDefault();
        setAuthError(null);
        setFinished(false);
        normalizeUsername();
        setAuthLoading(true);

        try {
            await login(username, password);

            const authUser = useAuthStore.getState().user;
            const roles = authUser?.roles ?? [];
            const hasPermission = roles.includes('ADMIN') || roles.includes('ANALISTA') || roles.includes('RESPONSAVEL_TECNICO');

            localStorage.setItem('isSupport', authUser?.support ? 'true' : 'false');

            if (window.matchMedia('(min-width: 1280px)').matches) {
                localStorage.setItem('menuOpen', 'true');
                toggleMenu(true);
            }

            if (localStorage.getItem('onboarding') || !hasPermission) {
                navigate(redirectPath);
                return;
            }

            await checkStateAndRedirect(redirectPath);
        } catch (error: any) {
            const errorCode = error?.response?.data?.code || error?.response?.data?.error;

            if (errorCode === 'USER_NOT_ACTIVATED') {
                navigate(`/primeiro-acesso?cpf=${/^\d{11}$/.test(username) ? username : ''}`);
                return;
            }

            const msg = error?.response?.data?.message || 'Usuário ou senha inválidos.';
            setAuthError(msg);
        } finally {
            setAuthLoading(false);
        }
    };

    const forgetPassword = () => {
        setAuthError(null);
        setFinished(true);
        setMessage('Uma nova senha foi enviada para seu e-mail (verifique também o spam).');
    };

    return (
        <section className="relative min-h-screen w-full overflow-hidden bg-slate-950 text-slate-50">
            <img
                src="/lumos-login-bg.png"
                alt="Iluminação pública urbana"
                className="absolute inset-0 h-full w-full object-cover object-center opacity-20"
            />

            <div className="absolute inset-0 bg-[radial-gradient(circle_at_top_left,_rgba(59,130,246,0.25),_transparent_34%),radial-gradient(circle_at_bottom_right,_rgba(20,184,166,0.18),_transparent_30%)]" />
            <div className="pointer-events-none absolute -left-24 top-24 h-72 w-72 rounded-full bg-blue-600/20 blur-3xl" />
            <div className="pointer-events-none absolute bottom-0 right-0 h-80 w-80 rounded-full bg-cyan-400/10 blur-3xl" />

            <div className="relative z-10 flex min-h-screen flex-col md:flex-row">
                <aside className="hidden md:flex md:w-[54%] md:items-center md:justify-center md:px-12 md:py-10 md:px-20">
                    <div className="w-full max-w-xl rounded-[2rem] border border-white/10 bg-black/[0.16] p-10 backdrop-blur-2xl">
                        <div className="mb-8 inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[0.06] px-4 py-2 text-sm text-slate-200">
                            <i className="pi pi-lock text-blue-300" />
                            Acesso seguro
                        </div>

                        <div className="space-y-4">
                            <h2 className="text-4xl font-semibold leading-tight text-white xl:text-5xl">
                                Entre na plataforma Lumos.
                            </h2>
                            <p className="max-w-lg text-base leading-7 text-slate-300">
                                Gerencie suas execuções, vincule itens contratuais e consolide suas medições em um ambiente unificado.
                            </p>
                        </div>

                        <div className="mt-10 grid gap-3">
                            <div className="flex items-center gap-3 rounded-2xl border border-white/10 bg-white/[0.04] px-4 py-4 text-slate-200">
                                <i className="pi pi-check-circle text-blue-300" />
                                Gestão de execuções e instalações
                            </div>
                            <div className="flex items-center gap-3 rounded-2xl border border-white/10 bg-white/[0.04] px-4 py-4 text-slate-200">
                                <i className="pi pi-link text-blue-300" />
                                Vínculo de itens e regras contratuais
                            </div>
                            <div className="flex items-center gap-3 rounded-2xl border border-white/10 bg-white/[0.04] px-4 py-4 text-slate-200">
                                <i className="pi pi-file-export text-blue-300" />
                                Fechamento de medições para faturamento
                            </div>
                        </div>
                    </div>
                </aside>

                <main className="flex min-h-screen items-center justify-center px-4 py-2 sm:px-6 md:min-h-0 md:w-[46%] md:px-10">
                    <div className="w-full max-w-lg">
                        <div className="mb-8 text-center">
                            <div className="mx-auto mb-4 flex h-[4.5rem] w-[4.5rem] items-center justify-center">
                                <img src="/icon-192.png" width="64" height="64" alt="Lumos" className="drop-shadow-lg" />
                            </div>
                            <div className="space-y-2">
                                <h1 className="text-3xl font-semibold tracking-tight text-white sm:text-4xl">
                                    Lumos<span className="text-blue-300">™</span>
                                </h1>
                                <p className="mx-auto max-w-md text-sm leading-6 text-slate-300">
                                    Faça login para acessar a plataforma.
                                </p>
                            </div>
                        </div>

                        <div className="mb-6 flex w-full rounded-2xl border border-white/10 bg-black/20 p-1 backdrop-blur-xl">
                            {(['login', 'signup', 'demo'] as const).map((tab) => (
                                <button
                                    key={tab}
                                    type="button"
                                    onClick={() => setActiveTab(tab)}
                                    className={[
                                        'flex flex-1 flex-col items-center justify-center gap-1 rounded-2xl px-3 py-3 text-xs font-semibold transition-all sm:text-sm',
                                        activeTab === tab
                                            ? 'bg-gradient-to-br from-blue-500 to-cyan-500 text-white shadow-[0_14px_28px_rgba(14,165,233,0.18)]'
                                            : 'text-slate-400 hover:-translate-y-[1px] hover:text-slate-100',
                                    ].join(' ')}
                                >
                                    <i className={`pi ${tab === 'login' ? 'pi-sign-in' : tab === 'signup' ? 'pi-user-plus' : 'pi-star'} text-lg`} />
                                    <span>{tab === 'login' ? 'Entrar' : tab === 'signup' ? 'Teste' : 'Demo'}</span>
                                </button>
                            ))}
                        </div>

                        <div className="rounded-[2rem] border border-white/10 bg-white/10 p-1 shadow-2xl shadow-slate-950/30 backdrop-blur-2xl">
                            <div className="p-6 sm:p-8">
                                {activeTab === 'login' && (
                                    <div className="space-y-6">
                                        <div>
                                            <h3 className="text-2xl font-semibold text-white">Acessar conta</h3>
                                            <p className="mt-2 text-sm leading-6 text-slate-300">
                                                Use seu usuário ou CPF e sua senha para entrar.
                                            </p>
                                        </div>

                                        <form onSubmit={handleLogin} className="flex flex-col gap-5">
                                            <div className="flex flex-col gap-2">
                                                <label className="text-xs font-semibold uppercase tracking-[0.24em] text-slate-300">
                                                    Usuário ou CPF
                                                </label>
                                                <div className="relative">
                                                    <i className="pi pi-user pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" />
                                                    <input
                                                        type="text"
                                                        value={username}
                                                        onChange={(e) => setUsername(e.target.value)}
                                                        onBlur={normalizeUsername}
                                                        placeholder="Digite seu usuário ou CPF"
                                                        autoComplete="username"
                                                        required
                                                        className="w-full rounded-2xl border border-slate-400/25 bg-slate-900/60 py-3.5 pl-11 pr-4 text-slate-50 outline-none transition-all placeholder:text-slate-500 hover:border-slate-400/35 hover:bg-slate-900/70 focus:border-blue-400 focus:bg-slate-900/85 focus:ring-4 focus:ring-blue-500/15"
                                                    />
                                                </div>
                                            </div>

                                            <div className="flex flex-col gap-2">
                                                <div className="flex items-center justify-between gap-3">
                                                    <label className="text-xs font-semibold uppercase tracking-[0.24em] text-slate-300">
                                                        Senha
                                                    </label>
                                                    <button
                                                        type="button"
                                                        onClick={forgetPassword}
                                                        className="text-xs font-medium text-blue-200 transition-colors hover:text-blue-100"
                                                    >
                                                        Esqueci minha senha
                                                    </button>
                                                </div>
                                                <div className="relative">
                                                    <i className="pi pi-key pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" />
                                                    <input
                                                        type={showPassword ? 'text' : 'password'}
                                                        value={password}
                                                        onChange={(e) => setPassword(e.target.value)}
                                                        placeholder="Digite sua senha"
                                                        autoComplete="current-password"
                                                        required
                                                        className="w-full rounded-2xl border border-slate-400/25 bg-slate-900/60 py-3.5 pl-11 pr-12 text-slate-50 outline-none transition-all placeholder:text-slate-500 hover:border-slate-400/35 hover:bg-slate-900/70 focus:border-blue-400 focus:bg-slate-900/85 focus:ring-4 focus:ring-blue-500/15"
                                                    />
                                                    <button
                                                        type="button"
                                                        onClick={() => setShowPassword(!showPassword)}
                                                        className="absolute right-4 top-1/2 -translate-y-1/2 text-slate-400 transition-colors hover:text-slate-100"
                                                    >
                                                        <i className={`pi ${showPassword ? 'pi-eye-slash' : 'pi-eye'}`} />
                                                    </button>
                                                </div>
                                            </div>

                                            {finished && (
                                                <div className="rounded-2xl border-l-4 border-emerald-500 bg-emerald-500/12 p-3 text-sm text-emerald-300">
                                                    {message}
                                                </div>
                                            )}

                                            {authError && (
                                                <div className="rounded-2xl border-l-4 border-red-500 bg-red-500/12 p-3 text-sm text-red-300">
                                                    {authError}
                                                </div>
                                            )}

                                            <Link
                                                to="/primeiro-acesso"
                                                className="text-left text-sm font-medium text-green-400 transition-colors hover:text-blue-100"
                                            >
                                                Primeiro acesso? Ative sua conta aqui
                                            </Link>

                                            <button
                                                type="submit"
                                                disabled={isLoading || authLoading || !username || !password}
                                                className="flex w-full items-center justify-center gap-2 rounded-2xl bg-gradient-to-r from-blue-600 to-cyan-500 py-3.5 font-semibold text-white shadow-lg shadow-blue-500/20 transition-all hover:-translate-y-[1px] hover:brightness-105 disabled:cursor-not-allowed disabled:opacity-55"
                                            >
                                                {(isLoading || authLoading) && <i className="pi pi-spin pi-spinner" />}
                                                Entrar na plataforma
                                            </button>
                                        </form>
                                    </div>
                                )}

                                {activeTab === 'signup' && (
                                    <div className="space-y-6">
                                        <div className="space-y-3">
                                            <div className="inline-flex items-center gap-2 rounded-full border border-blue-500/20 bg-blue-500/10 px-3 py-1 text-xs font-medium text-blue-100">
                                                <i className="pi pi-star-fill text-[0.75rem]" />
                                                Experimente com apoio da equipe
                                            </div>
                                            <div>
                                                <h3 className="text-2xl font-semibold text-white">Comece um teste gratuito</h3>
                                                <p className="mt-2 text-sm leading-6 text-slate-300">
                                                    Valide o Lumos com seu cenário real e conheça os módulos mais relevantes para sua operação.
                                                </p>
                                            </div>
                                        </div>

                                        <div className="grid gap-3">
                                            <div className="rounded-2xl border border-blue-500/20 bg-blue-500/10 p-4">
                                                <div className="flex items-start gap-3">
                                                    <i className="pi pi-gift mt-1 text-lg text-blue-200" />
                                                    <div>
                                                        <p className="font-semibold text-white">14 dias para explorar a plataforma</p>
                                                        <p className="mt-1 text-sm leading-6 text-slate-300">
                                                            Teste os fluxos principais sem precisar de cartão de crédito.
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>

                                            <div className="rounded-2xl border border-white/10 bg-black/10 p-4">
                                                <div className="flex items-start gap-3">
                                                    <i className="pi pi-send mt-1 text-lg text-emerald-200" />
                                                    <div>
                                                        <p className="font-semibold text-white">Ativação guiada</p>
                                                        <p className="mt-1 text-sm leading-6 text-slate-300">
                                                            Receba suporte para cadastrar estrutura, equipes e frentes de trabalho.
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>

                                            <div className="rounded-2xl border border-white/10 bg-black/10 p-4">
                                                <div className="flex items-start gap-3">
                                                    <i className="pi pi-shield mt-1 text-lg text-cyan-100" />
                                                    <div>
                                                        <p className="font-semibold text-white">Ambiente seguro desde o primeiro acesso</p>
                                                        <p className="mt-1 text-sm leading-6 text-slate-300">
                                                            Controle de perfis e visibilidade dos dados durante a avaliação.
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <button
                                            type="button"
                                            onClick={() => window.location.href = 'https://lumosip.com.br/teste-gratis'}
                                            className="mt-4 flex w-full items-center justify-center gap-2 rounded-2xl bg-gradient-to-r from-blue-600 to-cyan-500 py-3.5 font-semibold text-white shadow-lg shadow-blue-500/20 transition-all hover:-translate-y-[1px] hover:brightness-105"
                                        >
                                            <i className="pi pi-arrow-right" />
                                            Começar teste gratuito
                                        </button>

                                        <p className="text-center text-xs text-slate-400">
                                            Já tem conta?
                                            <button
                                                type="button"
                                                onClick={() => setActiveTab('login')}
                                                className="ml-1 font-semibold text-blue-200 transition-colors hover:text-blue-100"
                                            >
                                                Entrar agora
                                            </button>
                                        </p>
                                    </div>
                                )}

                                {activeTab === 'demo' && (
                                    <div className="space-y-6">
                                        <div className="space-y-3 text-center">
                                            <div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full border border-blue-500/25 bg-blue-500/12 text-blue-100">
                                                <i className="pi pi-desktop text-2xl" />
                                            </div>
                                            <div>
                                                <h3 className="text-2xl font-semibold text-white">Veja o Lumos em ação</h3>
                                                <p className="mt-2 text-sm leading-6 text-slate-300">
                                                    Agende uma apresentação consultiva para entender como o produto se encaixa na sua operação.
                                                </p>
                                            </div>
                                        </div>

                                        <div className="grid gap-3">
                                            <div className="rounded-2xl border border-white/10 bg-black/10 px-4 py-4">
                                                <div className="flex items-center gap-3 text-sm text-slate-200">
                                                    <i className="pi pi-check text-blue-200" />
                                                    Apresentação focada nos fluxos mais críticos da sua equipe
                                                </div>
                                            </div>
                                            <div className="rounded-2xl border border-white/10 bg-black/10 px-4 py-4">
                                                <div className="flex items-center gap-3 text-sm text-slate-200">
                                                    <i className="pi pi-check text-blue-200" />
                                                    Discussão sobre implantação, governança e produtividade
                                                </div>
                                            </div>
                                            <div className="rounded-2xl border border-white/10 bg-black/10 px-4 py-4">
                                                <div className="flex items-center gap-3 text-sm text-slate-200">
                                                    <i className="pi pi-check text-blue-200" />
                                                    Próximos passos claros para piloto ou adoção completa
                                                </div>
                                            </div>
                                        </div>

                                        <button
                                            type="button"
                                            onClick={() => window.location.href = 'https://lumosip.com.br/demonstracao'}
                                            className="mt-4 flex w-full items-center justify-center gap-2 rounded-2xl bg-gradient-to-r from-blue-600 to-cyan-500 py-3.5 font-semibold text-white shadow-lg shadow-blue-500/20 transition-all hover:-translate-y-[1px] hover:brightness-105"
                                        >
                                            <i className="pi pi-calendar" />
                                            Solicitar demonstração
                                        </button>

                                        <p className="text-center text-xs text-slate-400">
                                            Prefere explorar por conta própria?
                                            <button
                                                type="button"
                                                onClick={() => setActiveTab('signup')}
                                                className="ml-1 font-semibold text-blue-200 transition-colors hover:text-blue-100"
                                            >
                                                Ativar teste
                                            </button>
                                        </p>
                                    </div>
                                )}
                            </div>
                        </div>
                    </div>
                </main>
            </div>
        </section>
    );
}
