// react-app/src/features/billing/pages/Billing.tsx
import { useEffect, useMemo, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { useMutation, useQuery } from '@tanstack/react-query';

import { useAppStore } from '@/store/use-app-store';
import { useNotify } from '@/shared/hooks/use-notify';
import { billingApi } from '@/features/billing/api/billingApi';
import { GlassListbox } from '@/shared/components/glass-list-box';

const reasonMap: Record<string, string> = {
  teste_finalizado: 'Seu período de teste foi finalizado.',
  expirado: 'Sua assinatura expirou.',
  cancelado: 'Sua assinatura foi cancelada.',
};

const statusTone: Record<string, string> = {
  ACTIVE: 'bg-emerald-100 text-emerald-700 dark:bg-emerald-500/20 dark:text-emerald-200',
  TRIAL: 'bg-sky-100 text-sky-700 dark:bg-sky-500/20 dark:text-sky-200',
  PAST_DUE: 'bg-amber-100 text-amber-700 dark:bg-amber-500/20 dark:text-amber-200',
  CANCELED: 'bg-rose-100 text-rose-700 dark:bg-rose-500/20 dark:text-rose-200',
  EXPIRED: 'bg-rose-100 text-rose-700 dark:bg-rose-500/20 dark:text-rose-200',
};

const BILLING_CYCLE_OPTIONS = [
  { value: 'MONTHLY', label: 'Mensal' },
  { value: 'YEARLY', label: 'Anual' },
];

export default function Billing() {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const { setPageContext } = useAppStore();
  const { notify } = useNotify();

  const [renewOpen, setRenewOpen] = useState(false);
  const [upgradeOpen, setUpgradeOpen] = useState(false);
  const [billingCycle, setBillingCycle] = useState<'MONTHLY' | 'YEARLY'>('MONTHLY');
  const [planName, setPlanName] = useState('');
  const [targetPlanName, setTargetPlanName] = useState('');

  const reasonCode = searchParams.get('motivo');
  const reasonMessage = reasonCode ? reasonMap[reasonCode] ?? 'Acesso indisponível.' : null;

  const subscriptionQuery = useQuery({
    queryKey: ['billing', 'subscription-status'],
    queryFn: billingApi.getSubscriptionStatus,
  });
  const paymentMutation = useMutation({
    mutationFn: billingApi.processPayment,
  });

  useEffect(() => {
    setPageContext(['Cobrança'], 'Gerenciar Assinatura');
  }, [setPageContext]);

  const subscription = subscriptionQuery.data;
  const busy = subscriptionQuery.isLoading || paymentMutation.isPending;

  const statusLabel = useMemo(() => subscription?.status ?? 'Desconhecido', [subscription?.status]);
  const statusClass = useMemo(
    () => statusTone[subscription?.status ?? ''] ?? 'bg-slate-200 text-slate-700 dark:bg-slate-700 dark:text-slate-100',
    [subscription?.status],
  );

  const accessClass = subscription?.accessAllowed
    ? 'bg-emerald-100 text-emerald-700 dark:bg-emerald-500/20 dark:text-emerald-200'
    : 'bg-rose-100 text-rose-700 dark:bg-rose-500/20 dark:text-rose-200';

  return (
    <section className="min-h-full bg-gradient-to-br from-blue-50 to-indigo-50 p-4 dark:from-slate-950 dark:to-slate-900 md:p-6">
      <div className="mx-auto max-w-6xl space-y-6">
        <header className="text-center">
          <h1 className="text-3xl font-bold text-slate-900 dark:text-slate-100">Gerenciar Assinatura</h1>
          <p className="mt-2 text-slate-600 dark:text-slate-400">Renove ou atualize seu plano de assinatura.</p>
        </header>

        {reasonMessage && (
          <div className="rounded-xl border-l-4 border-amber-500 bg-amber-50 p-4 text-amber-800 dark:bg-amber-500/10 dark:text-amber-200">
            <i className="pi pi-exclamation-triangle mr-2" />
            {reasonMessage}
          </div>
        )}

        {busy && (
          <div className="flex justify-center py-12">
            <i className="pi pi-spin pi-spinner text-2xl text-blue-500" />
          </div>
        )}

        {!busy && subscription && (
          <>
            <div className="grid grid-cols-1 gap-6 lg:grid-cols-3">
              <article className="rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900 lg:col-span-2">
                <div className="rounded-t-2xl bg-gradient-to-r from-blue-600 to-cyan-500 px-6 py-5 text-white">
                  <h2 className="text-xl font-semibold">Status da Assinatura</h2>
                </div>

                <div className="space-y-4 p-6 text-sm">
                  <div className="flex items-center justify-between border-b border-slate-200 pb-3 dark:border-slate-800">
                    <span className="text-slate-500 dark:text-slate-400">Status</span>
                    <span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${statusClass}`}>{statusLabel}</span>
                  </div>

                  <div className="flex items-center justify-between border-b border-slate-200 pb-3 dark:border-slate-800">
                    <span className="text-slate-500 dark:text-slate-400">Plano</span>
                    <span className="font-semibold text-slate-900 dark:text-slate-100">{subscription.planName ?? 'N/A'}</span>
                  </div>

                  {subscription.trialEndsAt && (
                    <div className="flex items-center justify-between border-b border-slate-200 pb-3 dark:border-slate-800">
                      <span className="text-slate-500 dark:text-slate-400">Fim do período de teste</span>
                      <span className="font-semibold text-slate-900 dark:text-slate-100">{new Date(subscription.trialEndsAt).toLocaleString('pt-BR')}</span>
                    </div>
                  )}

                  <div className="flex items-center justify-between border-b border-slate-200 pb-3 dark:border-slate-800">
                    <span className="text-slate-500 dark:text-slate-400">Acesso permitido</span>
                    <span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${accessClass}`}>
                      {subscription.accessAllowed ? 'Sim' : 'Não'}
                    </span>
                  </div>

                  {subscription.message && (
                    <div className="text-slate-700 dark:text-slate-300">
                      <span className="font-medium">Mensagem:</span> {subscription.message}
                    </div>
                  )}
                </div>

                <footer className="flex flex-col gap-3 border-t border-slate-200 p-6 dark:border-slate-800 sm:flex-row">
                  <button
                    type="button"
                    onClick={() => {
                      setRenewOpen((prev) => !prev);
                      setUpgradeOpen(false);
                    }}
                    className="flex-1 rounded-xl bg-blue-600 px-4 py-2 text-sm font-semibold text-white hover:bg-blue-500"
                  >
                    <i className="pi pi-refresh mr-2" />Renovar Assinatura
                  </button>
                  <button
                    type="button"
                    onClick={() => {
                      setUpgradeOpen((prev) => !prev);
                      setRenewOpen(false);
                    }}
                    className="flex-1 rounded-xl bg-emerald-600 px-4 py-2 text-sm font-semibold text-white hover:bg-emerald-500"
                  >
                    <i className="pi pi-arrow-up mr-2" />Fazer Upgrade
                  </button>
                </footer>
              </article>

              <aside className="space-y-4">
                <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900">
                  <h3 className="text-sm font-semibold text-slate-900 dark:text-slate-100">Ações rápidas</h3>
                  <div className="mt-4 space-y-2">
                    <button
                      type="button"
                      disabled={paymentMutation.isPending}
                      onClick={() => paymentMutation.mutate({}, {
                        onSuccess: () => notify('Pagamento processado com sucesso.', 'success'),
                        onError: (error: unknown) => {
                          const message = (error as { response?: { data?: { message?: string } } })?.response?.data?.message;
                          notify(message ?? 'Erro ao processar pagamento.', 'error');
                        },
                      })}
                      className="w-full rounded-xl bg-amber-500 px-4 py-2 text-sm font-semibold text-black hover:bg-amber-400 disabled:opacity-50"
                    >
                      <i className="pi pi-credit-card mr-2" />Processar Pagamento
                    </button>
                    <button
                      type="button"
                      onClick={() => navigate('/dashboard')}
                      className="w-full rounded-xl border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50 dark:border-slate-700 dark:text-slate-200 dark:hover:bg-slate-800"
                    >
                      <i className="pi pi-home mr-2" />Voltar ao Dashboard
                    </button>
                  </div>
                </article>

                <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900">
                  <h3 className="text-sm font-semibold text-slate-900 dark:text-slate-100">Precisa de ajuda?</h3>
                  <p className="mt-2 text-sm text-slate-500 dark:text-slate-400">Entre em contato com o suporte para dúvidas sobre assinatura.</p>
                  <a
                    href="mailto:support@lumos.com?subject=Suporte%20Lumos&body=Ol%C3%A1%2C%20preciso%20de%20suporte%20com%20minha%20assinatura."
                    className="mt-3 inline-flex text-sm font-semibold text-blue-600 hover:text-blue-500"
                  >
                    Contatar suporte
                  </a>
                </article>
              </aside>
            </div>

            {(renewOpen || upgradeOpen) && (
              <div className="grid grid-cols-1 gap-6 md:grid-cols-2">
                {renewOpen && (
                  <article className="rounded-2xl border-2 border-blue-500 bg-white p-6 shadow-sm dark:bg-slate-900">
                    <h3 className="text-lg font-semibold text-slate-900 dark:text-slate-100">Renovar assinatura</h3>
                    <div className="mt-4 space-y-4">
                      <div className="space-y-1">
                        <label className="text-xs font-medium text-slate-500 dark:text-slate-400">Ciclo de cobrança</label>
                        <GlassListbox
                          value={billingCycle}
                          onChange={(value) => setBillingCycle(value as 'MONTHLY' | 'YEARLY')}
                          options={BILLING_CYCLE_OPTIONS}
                        />
                      </div>
                      <div className="space-y-1">
                        <label className="text-xs font-medium text-slate-500 dark:text-slate-400">Plano (opcional)</label>
                        <input
                          value={planName}
                          onChange={(event) => setPlanName(event.target.value)}
                          placeholder="Deixe em branco para manter o plano atual"
                          className="w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm text-slate-800 outline-none focus:border-blue-400 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-100"
                        />
                      </div>
                      <div className="rounded-xl bg-slate-100 p-3 text-xs text-slate-600 dark:bg-slate-800 dark:text-slate-300">
                        Renovação disponível na API. A chamada será habilitada após confirmação de regras comerciais.
                      </div>
                    </div>
                  </article>
                )}

                {upgradeOpen && (
                  <article className="rounded-2xl border-2 border-emerald-500 bg-white p-6 shadow-sm dark:bg-slate-900">
                    <h3 className="text-lg font-semibold text-slate-900 dark:text-slate-100">Fazer upgrade</h3>
                    <div className="mt-4 space-y-4">
                      <div className="space-y-1">
                        <label className="text-xs font-medium text-slate-500 dark:text-slate-400">Novo plano</label>
                        <input
                          value={targetPlanName}
                          onChange={(event) => setTargetPlanName(event.target.value)}
                          placeholder="Digite o nome do novo plano"
                          className="w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm text-slate-800 outline-none focus:border-blue-400 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-100"
                        />
                      </div>
                      <div className="rounded-xl bg-slate-100 p-3 text-xs text-slate-600 dark:bg-slate-800 dark:text-slate-300">
                        Upgrade disponível na API. A chamada será habilitada após confirmação de regras comerciais.
                      </div>
                    </div>
                  </article>
                )}
              </div>
            )}
          </>
        )}
      </div>
    </section>
  );
}

// angular-app/src/app/billing/billing.component.ts
import {Component, OnInit, OnDestroy} from '@angular/core';
import {CommonModule} from '@angular/common';
import {FormsModule, ReactiveFormsModule, FormBuilder, FormGroup, Validators} from '@angular/forms';
import {ActivatedRoute, Router} from '@angular/router';
import {BillingService} from './services/billing.service';
import {
    SubscriptionStatusResponse,
    BillingCycle,
    SubscriptionStatus
} from '../models/billing.model';
import {Subject, takeUntil} from 'rxjs';

// PrimeNG
import { ButtonModule } from 'primeng/button';
import { InputGroupModule } from 'primeng/inputgroup';
import { InputTextModule } from 'primeng/inputtext';
import { DropdownModule } from 'primeng/dropdown';
import { CardModule } from 'primeng/card';
import { ProgressSpinnerModule } from 'primeng/progressspinner';
import { ToastModule } from 'primeng/toast';
import { MessageService } from 'primeng/api';
import { TabViewModule } from 'primeng/tabview';
import { DividerModule } from 'primeng/divider';
import { TagModule } from 'primeng/tag';
import {DatePipe} from '@angular/common';
import { Utils } from '../core/service/utils';

@Component({
    selector: 'app-billing',
    standalone: true,
    imports: [
        CommonModule,
        FormsModule,
        ReactiveFormsModule,
        ButtonModule,
        InputGroupModule,
        InputTextModule,
        DropdownModule,
        CardModule,
        ProgressSpinnerModule,
        ToastModule,
        TabViewModule,
        DividerModule,
        TagModule,
        DatePipe
    ],
    providers: [MessageService],
    templateUrl: './billing.component.html',
    styleUrls: ['./billing.component.scss']
})
export class BillingComponent implements OnInit, OnDestroy {
  subscriptionStatus: SubscriptionStatusResponse | null = null;
  loading = true;
  error: string | null = null;
  actionInProgress = false;
  showRenewForm = false;
  showUpgradeForm = false;

  renewForm: FormGroup;
  upgradeForm: FormGroup;

  billingCycleOptions = [
    { label: 'Mensal', value: BillingCycle.MONTHLY },
    { label: 'Anual', value: BillingCycle.YEARLY }
  ];

  reasonCode: string | null = null;
  reasonMap: Record<string, string> = {
    'teste_finalizado': 'Seu período de teste foi finalizado',
    'expirado': 'Sua assinatura expirou',
    'cancelado': 'Sua assinatura foi cancelada'
  };

  private destroy$ = new Subject<void>();

  constructor(
    private billingService: BillingService,
    private route: ActivatedRoute,
    private router: Router,
    private fb: FormBuilder,
    private messageService: MessageService
  ) {
    this.renewForm = this.fb.group({
      billingCycle: [BillingCycle.MONTHLY, Validators.required],
      planName: [null]
    });

    this.upgradeForm = this.fb.group({
      targetPlanName: ['', Validators.required]
    });
  }

  openSupportEmail(): void {
    Utils.openEmail('support@lumos.com', 'Suporte Lumos', 'Olá, preciso de suporte com minha assinatura.');
  }

  ngOnInit(): void {
    this.route.queryParams.pipe(takeUntil(this.destroy$)).subscribe(params => {
      this.reasonCode = params['motivo'] || null;
    });

    this.loadSubscriptionStatus();
  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }

  loadSubscriptionStatus(): void {
    this.loading = true;
    this.error = null;

    this.billingService.getSubscriptionStatus()
      .pipe(takeUntil(this.destroy$))
      .subscribe({
        next: (data) => {
          this.subscriptionStatus = data;
          this.loading = false;
        },
        error: (err) => {
          console.error('Erro ao carregar status da assinatura:', err);
          this.error = 'Não foi possível carregar o status da sua assinatura. Tente novamente.';
          this.messageService.add({
            severity: 'error',
            summary: 'Erro',
            detail: this.error
          });
          this.loading = false;
        }
      });
  }

  onRenewSubmit(): void {
    if (this.renewForm.invalid) return;

    this.actionInProgress = true;
    const request = {
      billingCycle: this.renewForm.get('billingCycle')?.value,
      planName: this.renewForm.get('planName')?.value
    };

    // this.billingService.renewSubscription(request)
    //   .pipe(takeUntil(this.destroy$))
    //   .subscribe({
    //     next: (response) => {
    //       this.subscriptionStatus = {
    //         ...this.subscriptionStatus,
    //         ...response
    //       };
    //       this.messageService.add({
    //         severity: 'success',
    //         summary: 'Sucesso',
    //         detail: 'Assinatura renovada com sucesso!'
    //       });
    //       this.actionInProgress = false;
    //     },
    //     error: (err) => {
    //       console.error('Erro ao renovar assinatura:', err);
    //       const errorMsg = err.error?.message || 'Erro ao renovar assinatura. Tente novamente.';
    //       this.messageService.add({
    //         severity: 'error',
    //         summary: 'Erro',
    //         detail: errorMsg
    //       });
    //       this.actionInProgress = false;
    //     }
    //   });
  }

  onUpgradeSubmit(): void {
    if (this.upgradeForm.invalid) return;

    this.actionInProgress = true;
    const request = {
      targetPlanName: this.upgradeForm.get('targetPlanName')?.value
    };

    // this.billingService.upgradeSubscription(request)
    //   .pipe(takeUntil(this.destroy$))
    //   .subscribe({
    //     next: (response) => {
    //       this.subscriptionStatus = {
    //         ...this.subscriptionStatus,
    //         ...response
    //       };
    //       this.messageService.add({
    //         severity: 'success',
    //         summary: 'Sucesso',
    //         detail: 'Plano atualizado com sucesso!'
    //       });
    //       this.actionInProgress = false;
    //     },
    //     error: (err) => {
    //       console.error('Erro ao fazer upgrade:', err);
    //       const errorMsg = err.error?.message || 'Erro ao fazer upgrade. Tente novamente.';
    //       this.messageService.add({
    //         severity: 'error',
    //         summary: 'Erro',
    //         detail: errorMsg
    //       });
    //       this.actionInProgress = false;
    //     }
    //   });
  }

  processPayment(): void {
    this.actionInProgress = true;
    this.billingService.processPayment({})
      .pipe(takeUntil(this.destroy$))
      .subscribe({
        next: (response) => {
          console.log('Pagamento processado:', response);
          this.messageService.add({
            severity: 'success',
            summary: 'Sucesso',
            detail: 'Pagamento processado com sucesso!'
          });
          this.actionInProgress = false;
        },
        error: (err) => {
          console.error('Erro ao processar pagamento:', err);
          const errorMsg = err.error?.message || 'Erro ao processar pagamento. Tente novamente.';
          this.messageService.add({
            severity: 'error',
            summary: 'Erro',
            detail: errorMsg
          });
          this.actionInProgress = false;
        }
      });
  }

  goToDashboard(): void {
    this.router.navigate(['/dashboard']);
  }

  getReason(): string {
    return this.reasonCode ? this.reasonMap[this.reasonCode] || 'Acesso indisponível' : '';
  }

  getStatusSeverity(): "success" | "info" | "danger" | "secondary" | "warn" | "contrast"  {
    const status = this.subscriptionStatus?.status?.toLowerCase() || 'unknown';
    const severityMap: Record<string, "success" | "info" | "danger" | "secondary" | "warn" | "contrast"> = {
      'active': 'success',
      'trial': 'info',
      'past_due': 'warn',
      'canceled': 'danger',
      'expired': 'danger',
      'unknown': 'secondary'
    };
    return severityMap[status] || 'secondary';
  }

  getAccessSeverity(): 'success' | 'danger' {
    return this.subscriptionStatus?.accessAllowed ? 'success' : 'danger';
  }

  toggleRenewForm(): void {
    this.showRenewForm = !this.showRenewForm;
    this.showUpgradeForm = false;
  }

  toggleUpgradeForm(): void {
    this.showUpgradeForm = !this.showUpgradeForm;
    this.showRenewForm = false;
  }
}

<div class="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-50 dark:from-slate-950 dark:to-slate-900 p-4 md:p-8">
  <p-toast position="top-right"></p-toast>

  <div class="max-w-6xl mx-auto">
    <!-- Header -->
    <div class="mb-8 text-center">
      <h1 class="text-3xl md:text-4xl font-bold text-gray-900 dark:text-white mb-2">
        Gerenciar Assinatura
      </h1>
      <p class="text-lg text-gray-600 dark:text-gray-400">
        Renove ou atualize seu plano de assinatura
      </p>
    </div>

    <!-- Warning Alert -->
    <div *ngIf="reasonCode"
         class="mb-6 p-4 rounded-lg bg-yellow-50 dark:bg-yellow-900/20 border-l-4 border-yellow-400 dark:border-yellow-600">
      <div class="flex items-start">
        <svg class="w-5 h-5 text-yellow-600 dark:text-yellow-500 mt-0.5 mr-3 flex-shrink-0" fill="currentColor"
             viewBox="0 0 20 20">
          <path fill-rule="evenodd"
                d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z"
                clip-rule="evenodd"/>
        </svg>
        <p class="text-yellow-800 dark:text-yellow-200 font-medium">{{ getReason() }}</p>
      </div>
    </div>

    <!-- Loading State -->
    <div *ngIf="loading" class="flex justify-center items-center py-16">
      <div class="text-center">
        <p-progressSpinner
          [style]="{'width': '50px', 'height': '50px'}"
          strokeWidth="4"
          fill="transparent"
          animationDuration="1">
        </p-progressSpinner>
        <p class="mt-4 text-gray-600 dark:text-gray-400">Carregando informações de assinatura...</p>
      </div>
    </div>

    <!-- Main Content -->
    <div *ngIf="!loading && subscriptionStatus" class="grid grid-cols-1 lg:grid-cols-3 gap-6">
      <!-- Status Card -->
      <div class="lg:col-span-2">
        <p-card class="shadow-lg">
          <ng-template pTemplate="header">
            <div
              class="bg-gradient-to-r from-blue-500 to-indigo-600 dark:from-blue-600 dark:to-indigo-700 h-32 flex items-end px-6 pb-6">
              <h2 class="text-white text-2xl font-bold">Status da Assinatura</h2>
            </div>
          </ng-template>

          <div class="space-y-6">
            <!-- Status Row -->
            <div class="flex items-center justify-between pb-4 border-b border-gray-200 dark:border-gray-700">
              <span class="text-gray-600 dark:text-gray-400 font-medium">Status</span>
              <p-tag
                [value]="subscriptionStatus.status || 'Desconhecido'"
                [severity]="getStatusSeverity()"
                styleClass="text-sm"
              ></p-tag>
            </div>

            <!-- Plan Row -->
            <div class="flex items-center justify-between pb-4 border-b border-gray-200 dark:border-gray-700">
              <span class="text-gray-600 dark:text-gray-400 font-medium">Plano</span>
              <span
                class="text-gray-900 dark:text-white font-semibold">{{ subscriptionStatus.planName || 'N/A' }}</span>
            </div>

            <!-- Trial Date Row -->
            <div *ngIf="subscriptionStatus.trialEndsAt"
                 class="flex items-center justify-between pb-4 border-b border-gray-200 dark:border-gray-700">
              <span class="text-gray-600 dark:text-gray-400 font-medium">Período de Teste Termina</span>
              <span
                class="text-gray-900 dark:text-white font-semibold">{{ subscriptionStatus.trialEndsAt | date: 'short' }}</span>
            </div>

            <!-- Access Row -->
            <div class="flex items-center justify-between pb-4 border-b border-gray-200 dark:border-gray-700">
              <span class="text-gray-600 dark:text-gray-400 font-medium">Acesso Permitido</span>
              <p-tag
                [value]="subscriptionStatus.accessAllowed ? 'Sim' : 'Não'"
                [severity]="getAccessSeverity()"
              ></p-tag>
            </div>

            <!-- Message Row -->
            <div *ngIf="subscriptionStatus.message" class="flex items-center justify-between">
              <span class="text-gray-600 dark:text-gray-400 font-medium">Mensagem</span>
              <span class="text-gray-900 dark:text-white">{{ subscriptionStatus.message }}</span>
            </div>
          </div>

          <ng-template pTemplate="footer">
            <div class="flex gap-3 flex-col sm:flex-row">
              <button
                pButton
                type="button"
                label="Renovar Assinatura"
                icon="pi pi-refresh"
                [loading]="actionInProgress"
                (click)="toggleRenewForm()"
                class="flex-1"
              ></button>
              <button
                pButton
                type="button"
                label="Fazer Upgrade"
                icon="pi pi-arrow-up"
                severity="success"
                [loading]="actionInProgress"
                (click)="toggleUpgradeForm()"
                class="flex-1"
              ></button>
            </div>
          </ng-template>
        </p-card>
      </div>

      <!-- Quick Actions Sidebar -->
      <div class="space-y-4">
        <p-card class="shadow-lg">
          <ng-template pTemplate="header">
            <div
              class="bg-gradient-to-r from-green-500 to-emerald-600 dark:from-green-600 dark:to-emerald-700 h-24 flex items-end px-6 pb-4">
              <h3 class="text-white font-bold">Ações Rápidas</h3>
            </div>
          </ng-template>

          <div class="flex flex-col gap-3">
            <button
              pButton
              type="button"
              label="Processar Pagamento"
              icon="pi pi-credit-card"
              severity="warn"
              [loading]="actionInProgress"
              (click)="processPayment()"
              class="w-full"
            ></button>
            <p-divider layout="horizontal"></p-divider>
            <button
              pButton
              type="button"
              label="Voltar ao Dashboard"
              icon="pi pi-home"
              severity="secondary"
              (click)="goToDashboard()"
              class="w-full"
            ></button>
          </div>
        </p-card>

        <!-- Info Card -->
        <p-card class="shadow-lg">
          <ng-template pTemplate="header">
            <div
              class="bg-gradient-to-r from-blue-500 to-blue-600 dark:from-blue-600 dark:to-blue-700 h-20 flex items-end px-6 pb-4">
              <h3 class="text-white font-bold">Precisa de Ajuda?</h3>
            </div>
          </ng-template>

          <p class="text-sm text-gray-600 dark:text-gray-400 mb-4">
            Entre em contato com nosso suporte para dúvidas sobre sua assinatura.
          </p>
          <a href="mailto:support@lumos.com"
             class="text-blue-600 dark:text-blue-400 hover:underline text-sm font-semibold">
            Contatar Suporte →
          </a>
        </p-card>
      </div>
    </div>

    <!-- Forms Section -->
    <div *ngIf="!loading && subscriptionStatus" class="grid grid-cols-1 md:grid-cols-2 gap-6 mt-8">
      <!-- Renew Form -->
      <p-card *ngIf="showRenewForm" class="shadow-lg border-2 border-blue-500 dark:border-blue-600">
        <ng-template pTemplate="header">
          <div
            class="bg-gradient-to-r from-blue-500 to-indigo-600 dark:from-blue-600 dark:to-indigo-700 h-20 flex items-end px-6 pb-4">
            <h3 class="text-white font-bold">Renovar Assinatura</h3>
          </div>
        </ng-template>

        <form [formGroup]="renewForm" (ngSubmit)="onRenewSubmit()" class="space-y-4">
          <div>
            <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              Ciclo de Cobrança
            </label>
            <p-dropdown
              formControlName="billingCycle"
              [options]="billingCycleOptions"
              optionLabel="label"
              optionValue="value"
              [showClear]="false"
              class="w-full"
              styleClass="w-full"
            ></p-dropdown>
          </div>

          <div>
            <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              Plano (Opcional)
            </label>
            <input
              pInputText
              type="text"
              formControlName="planName"
              placeholder="Deixe em branco para manter o plano atual"
              class="w-full"
            />
          </div>

          <p-divider layout="horizontal"></p-divider>

          <div class="flex gap-3">
            <button
              pButton
              type="submit"
              label="Confirmar Renovação"
              icon="pi pi-check"
              [disabled]="renewForm.invalid || actionInProgress"
              [loading]="actionInProgress"
              class="flex-1"
            ></button>
            <button
              pButton
              type="button"
              label="Cancelar"
              icon="pi pi-times"
              severity="secondary"
              (click)="toggleRenewForm()"
              class="flex-1"
            ></button>
          </div>
        </form>
      </p-card>

      <!-- Upgrade Form -->
      <p-card *ngIf="showUpgradeForm" class="shadow-lg border-2 border-green-500 dark:border-green-600">
        <ng-template pTemplate="header">
          <div
            class="bg-gradient-to-r from-green-500 to-emerald-600 dark:from-green-600 dark:to-emerald-700 h-20 flex items-end px-6 pb-4">
            <h3 class="text-white font-bold">Fazer Upgrade</h3>
          </div>
        </ng-template>

        <form [formGroup]="upgradeForm" (ngSubmit)="onUpgradeSubmit()" class="space-y-4">
          <div>
            <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              Novo Plano
            </label>
            <input
              pInputText
              type="text"
              formControlName="targetPlanName"
              placeholder="Digite o nome do novo plano"
              class="w-full"
              required
            />
            <small *ngIf="upgradeForm.get('targetPlanName')?.invalid && upgradeForm.get('targetPlanName')?.touched"
                   class="text-red-600 dark:text-red-400">
              Campo obrigatório
            </small>
          </div>

          <p-divider layout="horizontal"></p-divider>

          <div class="flex gap-3">
            <button
              pButton
              type="submit"
              label="Confirmar Upgrade"
              icon="pi pi-check"
              severity="success"
              [disabled]="upgradeForm.invalid || actionInProgress"
              [loading]="actionInProgress"
              class="flex-1"
            ></button>
            <button
              pButton
              type="button"
              label="Cancelar"
              icon="pi pi-times"
              severity="secondary"
              (click)="toggleUpgradeForm()"
              class="flex-1"
            ></button>
          </div>
        </form>
      </p-card>
    </div>
  </div>
</div>

<!-- Subscription Status -->
<div *ngIf="!loading && subscriptionStatus" class="subscription-card">
  <div class="status-header">
    <h2>Status da Assinatura</h2>
    <span class="status-badge" [ngClass]="'status-' + (subscriptionStatus.status?.toLowerCase() || 'unknown')">
        {{ subscriptionStatus.status || 'Desconhecido' }}
      </span>
  </div>

  <div class="status-details">
    <div class="detail-row">
      <label>Plano:</label>
      <span>{{ subscriptionStatus.planName || 'N/A' }}</span>
    </div>

    <div class="detail-row" *ngIf="subscriptionStatus.trialEndsAt">
      <label>Período de Teste Termina:</label>
      <span>{{ subscriptionStatus.trialEndsAt | date: 'short' }}</span>
    </div>

    <div class="detail-row">
      <label>Acesso Permitido:</label>
      <span class="access-status" [ngClass]="subscriptionStatus.accessAllowed ? 'granted' : 'denied'">
          {{ subscriptionStatus.accessAllowed ? 'Sim' : 'Não' }}
        </span>
    </div>

    <div class="detail-row" *ngIf="subscriptionStatus.message">
      <label>Mensagem:</label>
      <span>{{ subscriptionStatus.message }}</span>
    </div>
  </div>

  <!-- Action Buttons -->
  <div class="action-buttons">
    <button
      (click)="toggleRenewForm()"
      [disabled]="actionInProgress"
      class="btn btn-primary">
      {{ showRenewForm ? 'Cancelar Renovação' : 'Renovar Assinatura' }}
    </button>

    <button
      (click)="toggleUpgradeForm()"
      [disabled]="actionInProgress"
      class="btn btn-secondary">
      {{ showUpgradeForm ? 'Cancelar Upgrade' : 'Fazer Upgrade' }}
    </button>

    <button
      (click)="processPayment()"
      [disabled]="actionInProgress"
      class="btn btn-tertiary">
      {{ actionInProgress ? 'Processando...' : 'Processar Pagamento' }}
    </button>

    <button
      (click)="goToDashboard()"
      [disabled]="actionInProgress"
      class="btn btn-outline">
      Voltar ao Dashboard
    </button>
  </div>
</div>

<!-- Renew Form -->
<div *ngIf="!loading && showRenewForm" class="form-card">
  <h3>Renovar Assinatura</h3>
  <form [formGroup]="renewForm" (ngSubmit)="onRenewSubmit()">
    <div class="form-group">
      <label for="billingCycle">Ciclo de Cobrança:</label>
      <select
        id="billingCycle"
        formControlName="billingCycle"
        class="form-control">
        <option value="MONTHLY">Mensal</option>
        <option value="YEARLY">Anual</option>
      </select>
    </div>

    <div class="form-group">
      <label for="planName">Plano (opcional):</label>
      <input
        id="planName"
        type="text"
        formControlName="planName"
        class="form-control"
        placeholder="Deixe em branco para manter o plano atual">
    </div>

    <div class="form-actions">
      <button
        type="submit"
        [disabled]="renewForm.invalid || actionInProgress"
        class="btn btn-primary">
        {{ actionInProgress ? 'Processando...' : 'Confirmar Renovação' }}
      </button>
      <button
        type="button"
        (click)="toggleRenewForm()"
        class="btn btn-outline">
        Cancelar
      </button>
    </div>
  </form>
</div>

<!-- Upgrade Form -->
<div *ngIf="!loading && showUpgradeForm" class="form-card">
  <h3>Fazer Upgrade do Plano</h3>
  <form [formGroup]="upgradeForm" (ngSubmit)="onUpgradeSubmit()">
    <div class="form-group">
      <label for="targetPlanName">Novo Plano:</label>
      <input
        id="targetPlanName"
        type="text"
        formControlName="targetPlanName"
        class="form-control"
        placeholder="Digite o nome do novo plano"
        required>
    </div>

    <div class="form-actions">
      <button
        type="submit"
        [disabled]="upgradeForm.invalid || actionInProgress"
        class="btn btn-primary">
        {{ actionInProgress ? 'Processando...' : 'Confirmar Upgrade' }}
      </button>
      <button
        type="button"
        (click)="toggleUpgradeForm()"
        class="btn btn-outline">
        Cancelar
      </button>
    </div>
  </form>
</div>
