// angular-app/src/app/billing/unavailable-access.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule, Location } from '@angular/common';
import { Router } from '@angular/router';
import { AuthService } from '../core/auth/auth.service';

// PrimeNG
import { ButtonModule } from 'primeng/button';
import { CardModule } from 'primeng/card';
import { DividerModule } from 'primeng/divider';
import { SharedState } from '../core/service/shared-state';
import { Title } from '@angular/platform-browser';
import { Utils } from '../core/service/utils';

@Component({
  selector: 'app-unavailable-access',
  standalone: true,
  imports: [CommonModule, ButtonModule, CardModule, DividerModule],
  templateUrl: './unavailable-access.component.html',
  styleUrls: ['./unavailable-access.component.scss']
})
export class UnavailableAccessComponent implements OnInit {
  isAdmin = false;
  loggingOut = false;

  constructor(
    protected router: Router,
    private authService: AuthService,
    private location: Location,
    private title: Title
  ) { }

  ngOnInit(): void {
    SharedState.setCurrentPath(["Acesso Indisponível"]);
    this.title.setTitle('Acesso Indisponível - Lumos');

    const isLocked = localStorage.getItem('isLocked') !== null;
    if (!isLocked) {
      if (window.history.length > 1) {
        this.location.back();
      } else {
        void this.router.navigate(['/dashboard']);
      }
    }
  }

  goToBilling(): void {
    void this.router.navigate(['/cobranca']);
  }

  logout(): void {
    this.loggingOut = true;
    this.authService.logout().subscribe({
      next: () => {
        void this.router.navigate(['/auth/login']);
      },
      error: (err) => {
        console.error('Erro ao fazer logout:', err);
        sessionStorage.clear();
        localStorage.clear();
        void this.router.navigate(['/auth/login']);
      }
    });
  }

  openSupportEmail(): void {
    Utils.openEmail('support@lumos.com', 'Suporte Lumos', 'Olá, preciso de suporte para acessar minha conta.');
  }
}

<div class="flex items-center justify-center p-4">
  <!-- Main Container -->
  <div class="w-full max-w-md">
    <p-card class="shadow-2xl border-0">
      <!-- Header with Background -->
      <ng-template pTemplate="header">
        <div class="bg-gradient-to-r from-blue-500 via-indigo-500 to-violet-500 dark:from-blue-600 dark:via-indigo-600 dark:to-violet-600 h-40 flex flex-col items-center justify-center">
<!--          <i class="pi pi-lock text-white text-5xl"></i>-->
          <img src="/public/icon-512.png" alt="Lumos Logo" width="64">
          <h2 class="text-neutral-100 font-semibold text-lg ">Lumos</h2>
        </div>
      </ng-template>

      <!-- Content -->
      <div class="text-center space-y-6 py-4">
        <div>
          <h1 class="text-3xl md:text-4xl font-bold text-gray-900 dark:text-white mb-2">
            Acesso temporariamente indisponível
          </h1>
          <p class="text-gray-600 dark:text-gray-400 text-lg">
            Fale com um usuário administrador no sistema para obter mais informações.
          </p>
        </div>

        <!-- Reasons List -->
        <div class="bg-blue-50 dark:bg-blue-900/20 rounded-lg p-4 text-left border-l-4 border-blue-500 dark:border-blue-400">
          <p class="text-sm font-semibold text-gray-900 dark:text-white mb-3">Isso pode ocorrer quando:</p>
          <ul class="space-y-2 text-sm text-gray-700 dark:text-gray-300">
            <li class="flex items-start">
              <span class="text-blue-600 dark:text-blue-400 mr-2">•</span>
              <span>Seu período de teste foi finalizado</span>
            </li>
            <li class="flex items-start">
              <span class="text-blue-600 dark:text-blue-400 mr-2">•</span>
              <span>Sua assinatura expirou</span>
            </li>
            <li class="flex items-start">
              <span class="text-blue-600 dark:text-blue-400 mr-2">•</span>
              <span>Sua assinatura foi cancelada</span>
            </li>
            <li class="flex items-start">
              <span class="text-blue-600 dark:text-blue-400 mr-2">•</span>
              <span>Há um problema com o pagamento</span>
            </li>
          </ul>
        </div>

      </div>

      <!-- Footer with Actions -->
      <ng-template pTemplate="footer">
        <div class="space-y-3">

          <button
            pButton
            type="button"
            label="Tentar novamente"
            icon="pi pi-replay"
            severity="primary"
            (click)="router.navigate(['']);"
            [loading]="loggingOut"
            class="w-full"
          ></button>

          <p-divider layout="horizontal"></p-divider>

          <button
            pButton
            type="button"
            label="Fazer Logout"
            icon="pi pi-sign-out"
            severity="secondary"
            (click)="logout()"
            [loading]="loggingOut"
            class="w-full"
          ></button>
        </div>
      </ng-template>
    </p-card>

    <!-- Support Footer -->
    <div class="mt-6 text-center text-sm text-gray-600 dark:text-gray-400">
      <p>Precisa de ajuda?</p>
      <a href="mailto:support@lumos.com" class="text-blue-600 dark:text-blue-400 hover:underline font-semibold">
        Contate nosso suporte
      </a>
    </div>
  </div>
</div>

// react-app/src/features/billing/pages/UnavailableAccess.tsx
import { useEffect } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';

import { useAppStore } from '@/store/use-app-store';
import { useAuthStore } from '@/core/auth/useAuthStore';

export default function UnavailableAccess() {
  const navigate = useNavigate();
  const location = useLocation();
  const { logout, isLoading } = useAuthStore();
  const { setPageContext } = useAppStore();

  useEffect(() => {
    setPageContext(['Acesso indisponível'], 'Acesso indisponível');

    const isLocked = localStorage.getItem('isLocked') !== null;
    if (!isLocked) {
      navigate('/dashboard', { replace: true });
    }
  }, [navigate, setPageContext]);

  return (
    <section className="relative flex min-h-[calc(100vh-52px)] items-center justify-center overflow-hidden bg-slate-950 px-4 py-8">
      <div className="absolute -left-20 top-10 h-72 w-72 rounded-full bg-blue-500/20 blur-3xl" />
      <div className="absolute -right-20 bottom-10 h-72 w-72 rounded-full bg-cyan-400/20 blur-3xl" />

      <article className="relative z-10 w-full max-w-2xl rounded-3xl border border-white/10 bg-slate-900/70 p-8 text-center shadow-2xl backdrop-blur-xl">
        <div className="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-2xl border border-white/15 bg-white/5">
          <i className="pi pi-lock text-xl text-amber-300" />
        </div>

        <p className="text-xs font-semibold uppercase tracking-[0.24em] text-cyan-200">Acesso indisponível</p>
        <h1 className="mt-2 text-3xl font-semibold text-white">Acesso temporariamente indisponível</h1>
        <p className="mt-4 text-sm leading-7 text-slate-300">
          No momento, não foi possível liberar seu acesso ao sistema. Em caso de dúvidas,
          fale com um usuário administrador.
        </p>

        <div className="mt-6 grid gap-3 sm:grid-cols-2">
          <button
            type="button"
            onClick={() => navigate(location.state?.from?.pathname ?? '/dashboard')}
            className="rounded-xl bg-gradient-to-r from-blue-600 to-cyan-500 px-4 py-2.5 text-sm font-semibold text-white hover:from-blue-500 hover:to-cyan-400"
          >
            <i className="pi pi-replay mr-2" />Tentar novamente
          </button>

          <button
            type="button"
            onClick={() => void logout()}
            disabled={isLoading}
            className="rounded-xl border border-white/20 px-4 py-2.5 text-sm font-semibold text-white hover:bg-white/10 disabled:opacity-50"
          >
            {isLoading ? <i className="pi pi-spin pi-spinner mr-2" /> : <i className="pi pi-sign-out mr-2" />}Fazer logout
          </button>
        </div>

        <a
          href="mailto:support@lumos.com?subject=Suporte%20Lumos&body=Ol%C3%A1%2C%20preciso%20de%20suporte%20para%20acessar%20minha%20conta."
          className="mt-6 inline-flex text-sm font-medium text-cyan-200 hover:text-cyan-100"
        >
          Precisa de ajuda? Contate nosso suporte.
        </a>
      </article>
    </section>
  );
}
