// angular-app/src/app/shared/components/account-drawer/account-drawer.component.ts
import {Component} from '@angular/core';
import {Drawer} from 'primeng/drawer';
import {SharedState} from '../../../core/service/shared-state';
import {AsyncPipe, NgForOf, NgIf, NgOptimizedImage} from '@angular/common';
import {SidebarComponent} from '../sidebar/sidebar.component';
import {Router} from '@angular/router';
import {Avatar} from 'primeng/avatar';
import {Badge} from 'primeng/badge';
import {Menu} from 'primeng/menu';
import {Ripple} from 'primeng/ripple';
import {MenuItem} from 'primeng/api';
import {AuthService} from '../../../core/auth/auth.service';

@Component({
    selector: 'app-account-drawer',
    standalone: true,
    imports: [
        Drawer,
        AsyncPipe,
        SidebarComponent,
        NgOptimizedImage,
        Avatar,
        Badge,
        Menu,
        NgForOf,
        NgIf,
        Ripple
    ],
    templateUrl: './account-drawer.component.html',
    styleUrl: './account-drawer.component.scss'
})
export class AccountDrawerComponent {
    options: MenuItem[] = [
        {
            label: 'Perfil',
            icon: 'pi pi-search',
            badge: '3',
            items: [
                {
                    label: 'Configurações',
                    icon: 'pi pi-cog',
                    command: () => {
                        void this.router.navigate(['/configuracoes/conta']);
                    }
                },
                {
                    label: 'Sair',
                    icon: 'pi pi-sign-out',
                    command: () => {
                        this.logout();
                    }
                },
                {
                    separator: true,
                },
            ],
        },
    ];

    protected readonly SharedState = SharedState;

    constructor(protected router: Router, protected authService: AuthService,) {

    }

    onDrawerChange(open: boolean) {
        SharedState.showAccountDrawer$.next(open);
    }

    logout() {
        this.authService.logout().subscribe();
        SharedState.showAccountDrawer$.next(false);
    }

    navigate(path: string) {
        void this.router.navigate([path]);
        SharedState.showAccountDrawer$.next(false);
    }
}

<div class="card flex justify-center">
  <p-drawer
    position="right"
    [visible]="(SharedState.showAccountDrawer$ | async) ?? false"
    (visibleChange)="onDrawerChange($event)"
    [closable]="false"
    styleClass="w-80 max-w-full">

    <!-- HEADER -->
    <ng-template #header>
      <div class="flex items-center gap-3 px-4 py-3 border-b border-neutral-200 dark:border-neutral-800">
        <p-avatar
          [label]="authService.getUser().fullName.charAt(0).toUpperCase()"
          image="https://primefaces.org/cdn/primeng/images/demo/avatar/amyelsner.png"
          shape="circle"
          size="large"
          class="bg-gray-200 dark:bg-gray-700 text-gray-800 dark:text-white">
        </p-avatar>

        <div class="flex flex-col min-w-0">
        <span class="font-semibold truncate">
          {{ authService.getUser().fullName }}
        </span>
          <span class="text-sm text-gray-500 truncate">
          {{ authService.getUser().username }}
        </span>
        </div>
      </div>
    </ng-template>

    <!-- CONTENT -->
    <div class="flex flex-col py-2">

      <!-- SECTION -->
      <div class="px-4 py-2 text-xs uppercase tracking-wide text-gray-400">
        Conta
      </div>

      <button
        (click)="navigate('/configuracoes/conta')"
        pRipple
        class="flex items-center gap-3 px-4 py-3 hover:bg-surface-100 dark:hover:bg-surface-800 transition">
        <i class="pi pi-user text-sm"></i>
        <span>Perfil</span>
      </button>

      <button
        pRipple
        class="flex items-center gap-3 px-4 py-3 hover:bg-surface-100 dark:hover:bg-surface-800 transition">
        <i class="pi pi-cog text-sm"></i>
        <span>Configurações</span>
      </button>

      <!-- DIVIDER -->
      <div class="my-2 border-t border-neutral-200 dark:border-neutral-800"></div>

      <!-- SECTION -->
      <div class="px-4 py-2 text-xs uppercase tracking-wide text-gray-400">
        Segurança
      </div>

      <button
        pRipple
        class="flex items-center gap-3 px-4 py-3 hover:bg-surface-100 dark:hover:bg-surface-800 transition">
        <i class="pi pi-shield text-sm"></i>
        <span>Alterar senha</span>
      </button>

      <button
        (click)="logout()"
        pRipple
        class="flex items-center gap-3 px-4 py-3 text-red-600 hover:bg-red-50 dark:hover:bg-red-900/20 transition">
        <i class="pi pi-sign-out text-sm"></i>
        <span>Sair</span>
      </button>

    </div>

    <!-- FOOTER -->
    <ng-template #footer>
      <div class="px-4 py-2 text-xs text-gray-400 border-t border-neutral-200 dark:border-neutral-800">
        Lumos © 2026 · v1.0.0
      </div>
    </ng-template>

  </p-drawer>

</div>

// react-app/src/shared/layout/account-drawer.tsx
import { createPortal } from 'react-dom';
import { useNavigate } from 'react-router-dom';
import { useAuthStore } from '../../core/auth/useAuthStore';
import { useAppStore } from '../../store/use-app-store';

export function AccountDrawer() {
  const navigate = useNavigate();
  const { user, logout } = useAuthStore();
  const { showAccountDrawer, setShowAccountDrawer } = useAppStore();

  const initial = user?.fullName?.charAt(0)?.toUpperCase() || 'U';

  const onNavigate = (path: string) => {
    navigate(path);
    setShowAccountDrawer(false);
  };

  const onLogout = async () => {
    await logout();
    setShowAccountDrawer(false);
  };

  return createPortal(
    <>
      <div
        className={[
          'fixed inset-0 z-[300] bg-black/40 transition-opacity duration-300',
          showAccountDrawer ? 'opacity-100 pointer-events-auto' : 'opacity-0 pointer-events-none',
        ].join(' ')}
        onClick={() => setShowAccountDrawer(false)}
      />

      <aside
        className={[
          'fixed right-0 top-0 z-[310] h-screen w-full max-w-[20rem] transform border-l border-white/10 bg-white dark:bg-zinc-950 shadow-2xl transition-transform duration-300',
          showAccountDrawer ? 'translate-x-0' : 'translate-x-full',
        ].join(' ')}
        aria-hidden={!showAccountDrawer}
      >
        <div className="flex h-full flex-col">
          <header className="flex items-center gap-3 border-b border-slate-200 px-4 py-4 dark:border-zinc-800">
            <div className="flex h-10 w-10 items-center justify-center rounded-full bg-gradient-to-br from-blue-600 to-cyan-500 text-sm font-semibold text-white">
              {initial}
            </div>
            <div className="min-w-0">
              <p className="truncate text-sm font-semibold text-slate-800 dark:text-zinc-100">{user?.fullName}</p>
              <p className="truncate text-xs text-slate-500 dark:text-zinc-400">{user?.username}</p>
            </div>
          </header>

          <div className="flex-1 py-2">
            <p className="px-4 py-2 text-[11px] uppercase tracking-[0.14em] text-slate-400">Conta</p>
            <button
              type="button"
              onClick={() => onNavigate('/configuracoes/conta')}
              className="flex w-full items-center gap-3 px-4 py-3 text-sm text-slate-700 transition-colors hover:bg-slate-100 dark:text-zinc-200 dark:hover:bg-zinc-900"
            >
              <i className="pi pi-user text-xs" />
              Perfil
            </button>

            <button
              type="button"
              onClick={() => onNavigate('/configuracoes')}
              className="flex w-full items-center gap-3 px-4 py-3 text-sm text-slate-700 transition-colors hover:bg-slate-100 dark:text-zinc-200 dark:hover:bg-zinc-900"
            >
              <i className="pi pi-cog text-xs" />
              Configurações
            </button>

            <div className="my-2 border-t border-slate-200 dark:border-zinc-800" />

            <p className="px-4 py-2 text-[11px] uppercase tracking-[0.14em] text-slate-400">Segurança</p>
            <button
              type="button"
              onClick={onLogout}
              className="flex w-full items-center gap-3 px-4 py-3 text-sm text-red-600 transition-colors hover:bg-red-50 dark:text-red-400 dark:hover:bg-red-950/30"
            >
              <i className="pi pi-sign-out text-xs" />
              Sair
            </button>
          </div>

          <footer className="border-t border-slate-200 px-4 py-3 text-[11px] text-slate-400 dark:border-zinc-800">
            Lumos © 2026
          </footer>
        </div>
      </aside>
    </>,
    document.body,
  );
}
